import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../src/main/store';
import {accountLoginPassword,connectArticleAccount} from '../src/main/article-connections';
import type {Account,SecretStore,Site} from '../src/shared/types';
const one='11111111-1111-4111-8111-111111111111',two='22222222-2222-4222-8222-222222222222',stamp=new Date().toISOString();
function fixture(){const store=new Store(':memory:'),secrets=new Map<string,string>();const vault:SecretStore={get:async key=>secrets.get(key),set:async(key,value)=>{secrets.set(key,value)},delete:async key=>{secrets.delete(key)}};store.update(s=>{s.settings.autoRun=false;s.sites=[one,two].map((id,index):Site=>({id,url:`https://site${index}.example.com/`,domain:`site${index}.example.com`,name:'Fixture',email:'owner@example.com',description:'Educational publication',category:'content',language:'en',monthlyTarget:2,status:'ready',createdAt:stamp}))});return {store,secrets,vault}}
for(const channelId of ['paper-wf','hive'] as const){
 const connector=async(vault:SecretStore,id:string,username:string,credential:string)=>{await vault.set('account:'+id,credential);return {username,url:channelId==='hive'?`https://hive.blog/@${username}`:`https://paper.wf/${username}/`}};
 test(`${channelId} reconnect preserves identity and existing bindings; explicit edit replaces selection`,async()=>{const {store,vault}=fixture();try{const input={channelId,username:'fixture',credential:'synthetic-secret',siteIds:[one]};const first=await connectArticleAccount(store,vault,input,connector),second=await connectArticleAccount(store,vault,{...input,siteIds:[two]},connector);assert.equal(first.id,second.id);assert.equal(first.credentialKind,'api_token');assert.deepEqual(store.read().accountBindings.map(x=>x.siteId),[one,two]);await connectArticleAccount(store,vault,{...input,accountId:first.id,siteIds:[two]},connector);assert.deepEqual(store.read().accountBindings.map(x=>x.siteId),[two]);}finally{store.close()}});
 test(`${channelId} invalid sites fail before credential use`,async()=>{const {store,vault,secrets}=fixture();let calls=0;try{await assert.rejects(connectArticleAccount(store,vault,{channelId,username:'fixture',credential:'synthetic-secret',siteIds:['missing']},async(...args)=>{calls++;return connector(...args)}));assert.equal(calls,0);assert.equal(secrets.size,0);assert.equal(store.read().accounts.length,0);}finally{store.close()}});
 test(`${channelId} unconfirmed remote receipt prevents rebinding and rolls back account and secret`,async()=>{const {store,vault,secrets}=fixture();try{const input={channelId,username:'fixture',credential:'old-synthetic-secret',siteIds:[one]};const account=await connectArticleAccount(store,vault,input,connector);store.update(s=>s.tasks.push({id:'33333333-3333-4333-8333-333333333333',siteId:two,channelId,accountId:'old-account',sourceDomain:channelId==='hive'?'hive.blog':'paper.wf',status:'needs_input',checkpoint:channelId==='hive'?'hive_publish_submitting':'paper_publish_submitting',createdAt:stamp,updatedAt:stamp,scheduledAt:stamp,attempts:1,message:'unknown',...(channelId==='hive'?{hive:{author:'old-author',permlink:'old-post',contentHash:'a'.repeat(64),stage:'submitting' as const}}:{paper:{username:'old-author',slug:'old-post',contentHash:'a'.repeat(64),stage:'submitting' as const}})}));const before=store.read();await assert.rejects(connectArticleAccount(store,vault,{...input,accountId:account.id,credential:'new-synthetic-secret',siteIds:[one,two]},connector),/待核验/);assert.deepEqual(store.read(),before);assert.equal(secrets.get('account:'+account.id),'old-synthetic-secret');}finally{store.close()}});
 test(`${channelId} mismatched returned identity leaves no orphan secret or account`,async()=>{const {store,vault,secrets}=fixture();try{await assert.rejects(connectArticleAccount(store,vault,{channelId,username:'fixture',credential:'synthetic-secret',siteIds:[one]},async(...args)=>({...await connector(...args),username:'someone-else'})),/不一致/);assert.equal(secrets.size,0);assert.equal(store.read().accounts.length,0);assert.equal(store.read().accountBindings.length,0);}finally{store.close()}});
}

const revealAccount={id:'paper-test',channelId:'paper-wf',username:'fixture',credentialKind:'api_token',status:'needs_verification',hasPassword:true,source:'generated',email:'',createdAt:stamp,updatedAt:stamp} satisfies Account;
test('Paper reveal returns only same-identity login password, never its publishing token',()=>{
 const secret=JSON.stringify({version:1,username:'fixture',password:'synthetic-login-password',token:'synthetic-api-token'});
 assert.equal(accountLoginPassword(revealAccount,secret),'synthetic-login-password');
 for(const raw of [undefined,'synthetic-api-token','null',JSON.stringify({version:1,username:'other',password:'p'}),JSON.stringify({version:2,username:'fixture',password:'p'}),JSON.stringify({version:1,username:'fixture',token:'token'})])assert.throws(()=>accountLoginPassword(revealAccount,raw),/登录资料无效/);
});
test('Password reveal still refuses Hive and other API/OAuth keys',()=>{
 for(const channelId of ['hive','github-gist','nostr','paragraph'])assert.throws(()=>accountLoginPassword({...revealAccount,channelId},'synthetic-key'),/令牌不支持/);
 assert.throws(()=>accountLoginPassword({...revealAccount,channelId:'blogger',credentialKind:'oauth'},'synthetic-key'),/令牌不支持/);
 assert.equal(accountLoginPassword({...revealAccount,channelId:'custom-site',credentialKind:'password'},'synthetic-login-password'),'synthetic-login-password');
});
