import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import test from 'node:test';
import {marked} from 'marked';
import {CHANNELS} from '../src/integrations/catalog';
import type {DocsMdTransport} from '../src/integrations/docs-md';
import {ARTICLE_REVIEW_CONTRACT_VERSION,articleContentHash,articleContextHash} from '../src/main/article-review';
import {Controller,isConfirmedDocsMdResultUrl} from '../src/main/controller';
import {validateBackup} from '../src/main/backup-validation';
import {docsMdTaskIdentity,parseDocsMdPublicationSecret} from '../src/main/docs-md-publication';
import {Store,emptyState} from '../src/main/store';
import {hasExternalAttempt} from '../src/main/task-recovery';
import {reservesSlot} from '../src/shared/publication';
import type {Vault} from '../src/main/vault';
import type {Site,Task} from '../src/shared/types';

const stamp='2026-10-09T00:00:00.000Z';
const taskId='11111111-1111-4111-8111-111111111111';
const siteId='22222222-2222-4222-8222-222222222222';
const publicId='docs-cycle-51';
const publicUrl=`https://docs-md.com/${publicId}`;
const rawUrl=`https://docs-md.com/raw/${publicId}`;
const editToken=Buffer.alloc(24,51).toString('base64url');
const draft={title:'A reviewed Docs MD guide',description:'Fixture',body:'A complete reviewed Markdown guide with the original [source](https://example.test/guide).'};

function channel(){const value=CHANNELS.find(item=>item.id==='docs-md');assert.ok(value);return value}
async function enabled<T>(run:()=>Promise<T>):Promise<T>{const value=channel(),before=value.enabled;value.enabled=true;try{return await run()}finally{value.enabled=before}}
function site():Site{return {id:siteId,domain:'example.test',url:'https://example.test/',email:'owner@example.test',name:'Example',description:'Independent guides',category:'content',language:'en',monthlyTarget:1,articleReviewMode:'manual',status:'ready',createdAt:stamp,analyzedAt:stamp,topicsCheckedAt:new Date().toISOString(),topics:[{url:'https://example.test/guide',discoveredAt:stamp}]}}
function task(extra:Partial<Task>={}):Task{return {id:taskId,siteId,channelId:'docs-md',sourceDomain:'docs-md.com',status:'queued',createdAt:stamp,scheduledAt:stamp,updatedAt:stamp,attempts:0,message:'fixture',topicUrl:'https://example.test/guide',draft,draftRevision:1,articleApprovedAt:stamp,health:'pending',...extra}}
function configure(store:Store,taskValue=task()){const state=emptyState();state.settings.autoRun=true;state.settings.notify=false;state.settings.articleReviewMode='manual';state.settings.timezone='UTC';state.settings.channelOverrides=Object.fromEntries(CHANNELS.map(item=>[item.id,item.id==='docs-md']));state.sites=[site()];state.tasks=[taskValue];store.update(current=>Object.assign(current,state))}
function vault(store:Store,options:{available?:boolean;failEncryption?:boolean}={}):Vault{const available=options.available??true;return {ready:available,available:()=>available,get:async(key:string)=>store.getCipher(key),set:async(key:string,value:string)=>store.setCipher(key,value),delete:async(key:string)=>store.deleteCipher(key),encryptSecrets:(values:Record<string,string>)=>{if(options.failEncryption)throw Error(`secret-${editToken}`);return Object.fromEntries(Object.entries(values).map(([key,value])=>[key,`enc:${Buffer.from(value).toString('base64url')}`]))}} as unknown as Vault}
function fixture(taskValue=task()){const directory=mkdtempSync(join(tmpdir(),'linkflow-docs-md-controller-')),path=join(directory,'state.sqlite'),store=new Store(path);configure(store,taskValue);return {directory,path,store,cleanup(){try{store.close()}catch{}rmSync(directory,{recursive:true,force:true})}}}
function publicHtml(valid=false){const source=valid?docsMdTaskIdentity(task())!.source:'# A reviewed Docs MD guide\n\nDifferent public body.';const rendered=String(marked.parse(source,{async:false,gfm:true})).replaceAll('<a href=',`<a rel="nofollow ugc noopener noreferrer" href=`);return `<!doctype html><html><head><link rel="canonical" href="${publicUrl}"></head><body><main><section><div>Permanent link</div></section><section><article><div><h1>publication.md</h1><a href="${rawUrl}">Raw</a></div><div id="markdown-content"><div class="markdown-content">${rendered}</div></div></article></section><section><p>This link does not expire.</p></section></main></body></html>`}
function transport(store:Store,requests:Array<{method:string;url:string;body?:string}>,validPublic=false,unknownPost=false):DocsMdTransport{return async(url,init)=>{const method=init.method??'GET',body=typeof init.body==='string'?init.body:undefined;requests.push({method,url,...(body?{body}:{})});if(method==='POST'){const saved=store.read().tasks[0];assert.equal(saved.articleApprovedAt,stamp);assert.equal(saved.checkpoint,'docs_md_share_submitting');assert.equal(saved.docsMd?.stage,'submitting');assert.equal(saved.submittedAt,saved.docsMd?.createdAt);assert.deepEqual(JSON.parse(body!),{content:docsMdTaskIdentity(saved)!.source,filename:'publication.md',expiry:'never'});if(unknownPost)return new Response('upstream unknown',{status:503,headers:{'content-type':'text/plain'}});return new Response(JSON.stringify({success:true,id:publicId,url:publicUrl,rawUrl,editToken,expiresAt:0,rateLimit:{remaining:19}}),{status:200,headers:{'content-type':'application/json'}})}if(url===rawUrl)return new Response(docsMdTaskIdentity(store.read().tasks[0])!.source,{status:200,headers:{'content-type':'text/markdown'}});if(url==='https://docs-md.com/robots.txt')return new Response('User-agent: *\nAllow: /\nDisallow: /api/',{status:200,headers:{'content-type':'text/plain'}});assert.equal(url,publicUrl);return new Response(publicHtml(validPublic),{status:200,headers:{'content-type':'text/html'}})}}
function plaintextSecret(store:Store):string|undefined{const cipher=store.getCipher('publication:'+taskId);return cipher?.startsWith('enc:')?Buffer.from(cipher.slice(4),'base64url').toString():undefined}

test('manual URL adoption accepts only the exact source-bound Docs MD receipt',()=>{const pending=task({status:'review',submittedAt:stamp,checkpoint:'docs_md_api_receipt',publicUrl,health:'pending'}),identity=docsMdTaskIdentity(pending);assert.ok(identity);pending.docsMd={operationId:'docs_md_11111111111141118111111111111111',sourceHash:identity.sourceHash,requestHash:identity.requestHash,createdAt:stamp,stage:'api_receipt',id:publicId};assert.equal(isConfirmedDocsMdResultUrl(pending,publicUrl),true);for(const changed of [{...pending,publicUrl:'https://docs-md.com/other'},{...pending,checkpoint:'docs_md_share_submitting'},{...pending,accountId:'33333333-3333-4333-8333-333333333333'},{...pending,docsMd:{...pending.docsMd!,id:'other'}},{...pending,docsMd:{...pending.docsMd!,sourceHash:'0'.repeat(64)}},{...pending,draft:{...pending.draft!,body:pending.draft!.body+' changed'}}])assert.equal(isConfirmedDocsMdResultUrl(changed,publicUrl),false);assert.equal(isConfirmedDocsMdResultUrl(pending,'https://docs-md.com/other'),false)});

test('Docs MD intent is shared remote state that reserves the original planning slot',()=>{const value=task({status:'needs_input',submittedAt:stamp,checkpoint:'docs_md_share_submitting'}),identity=docsMdTaskIdentity(value);assert.ok(identity);value.docsMd={operationId:'docs_md_11111111111141118111111111111111',sourceHash:identity.sourceHash,requestHash:identity.requestHash,createdAt:stamp,stage:'submitting'};assert.equal(hasExternalAttempt(value),true);assert.equal(reservesSlot(value,new Date(stamp)),true)});

test('disabled Docs MD cannot be scheduled even when settings request it',async()=>{const f=fixture(),value=channel(),before=value.enabled;value.enabled=false;try{const controller=new Controller(f.store,vault(f.store),'fixture');controller.runtime.aiReady=true;await controller.tick();const saved=f.store.read().tasks[0];assert.equal(saved.status,'skipped');assert.equal(saved.submittedAt,undefined);assert.equal(saved.docsMd,undefined)}finally{value.enabled=before;f.cleanup()}});

test('shared publication cadence defers Docs MD before any remote intent or POST',async()=>enabled(async()=>{const f=fixture(),requests:string[]=[],now=new Date();f.store.update(state=>{state.tasks.push({...task(),id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',status:'live',topicUrl:'https://example.test/prior',publicUrl:'https://docs-md.com/prior',firstLiveAt:now.toISOString(),verifiedAt:now.toISOString(),lastCheckedAt:now.toISOString(),nextCheckAt:new Date(now.getTime()+86400000).toISOString(),health:'healthy',linkCheck:'found',linkRel:'nofollow ugc noopener noreferrer'})});const controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:async url=>{requests.push(url);throw Error('cadence must stop before transport')}}});controller.runtime.aiReady=true;try{await controller.tick();const saved=f.store.read().tasks.find(value=>value.id===taskId)!;assert.equal(requests.length,0);assert.equal(saved.status,'queued');assert.equal(saved.docsMd,undefined);assert.equal(saved.submittedAt,undefined);assert.ok(Date.parse(saved.scheduledAt)>now.getTime())}finally{f.cleanup()}}));

test('bounded AI review retry and system wait remain restorable before one first intent',async t=>enabled(async()=>{t.mock.timers.enable({apis:['Date'],now:Date.parse('2026-10-09T01:00:00.000Z')});const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],baseFetch=transport(f.store,requests);let reviews=0;f.store.update(state=>{state.settings.articleReviewMode='ai';state.sites[0].articleReviewMode='ai'});const controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:async(url,init)=>{if(init.method==='POST')assert.equal(f.store.read().tasks[0].nextCheckAt,undefined);return baseFetch(url,init)}},reviewArticle:async(current,currentSite,currentChannel,settings)=>{reviews++;const base={reviewContractVersion:ARTICLE_REVIEW_CONTRACT_VERSION,reviewedAt:new Date().toISOString(),draftRevision:current.draftRevision??0,contentHash:articleContentHash(current),contextHash:articleContextHash(currentSite,currentChannel,settings),evidenceUrls:[currentSite.url,currentChannel.evidenceSources![0].url]};return reviews<=2?{...base,status:'failed' as const,reasonCode:'ai_unavailable' as const,reason:'Synthetic temporary provider failure'}:{...base,status:'passed' as const,reasonCode:'passed' as const,reason:'Synthetic accepted independent review',checks:{factualAccuracy:'pass' as const,authorRelationship:'pass' as const,affiliateDisclosure:'pass' as const,independentValue:'pass' as const,financialSafety:'pass' as const,channelRules:'unknown' as const}}}});controller.runtime.aiReady=true;try{await controller.tick();let saved=f.store.read().tasks[0];assert.equal(requests.length,0);assert.equal(reviews,1);assert.equal(saved.status,'queued');assert.equal(saved.checkpoint,'article_review');assert.equal(saved.nextCheckAt,saved.scheduledAt);assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}));t.mock.timers.setTime(Date.parse(saved.scheduledAt)+1);await controller.tick();saved=f.store.read().tasks[0];assert.equal(reviews,2);assert.equal(requests.filter(item=>item.method==='POST').length,0);assert.equal(saved.status,'failed');assert.equal(saved.checkpoint,'system_wait');assert.equal(saved.recoveryEligible,true);assert.ok(saved.nextCheckAt);assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}));t.mock.timers.setTime(Date.parse(saved.nextCheckAt!)+1);await controller.tick();saved=f.store.read().tasks[0];assert.equal(reviews,3);assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(saved.docsMd?.stage,'api_receipt')}finally{controller.stop();f.cleanup();t.mock.timers.reset()}}));

test('a due receipt-free local schedule is consumed before the first intent',async()=>enabled(async()=>{const scheduled=task({nextCheckAt:stamp}),f=fixture(scheduled),requests:Array<{method:string;url:string;body?:string}>=[],baseFetch=transport(f.store,requests),controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:async(url,init)=>{if(init.method==='POST')assert.equal(f.store.read().tasks[0].nextCheckAt,undefined);return baseFetch(url,init)}}});controller.runtime.aiReady=true;try{assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}));await controller.tick();assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(f.store.read().tasks[0].docsMd?.stage,'api_receipt')}finally{f.cleanup()}}));

test('two concurrent Controller callers still produce at most one POST in real SQLite',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests)}});controller.runtime.aiReady=true;try{await Promise.all([controller.tick(),controller.tick()]);assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(f.store.read().tasks[0].docsMd?.stage,'api_receipt')}finally{f.cleanup()}}));

test('the dispatcher durably binds one response, encrypts its token, and leaves unaccepted HTML pending',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests)}});controller.runtime.aiReady=true;try{await controller.tick();const saved=f.store.read().tasks[0],secret=plaintextSecret(f.store);assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(requests.filter(item=>item.method==='GET').length,3);assert.equal(saved.status,'review');assert.equal(saved.health,'pending');assert.equal(saved.linkCheck,undefined);assert.equal(saved.firstLiveAt,undefined);assert.equal(saved.checkpoint,'docs_md_api_receipt');assert.equal(saved.docsMd?.stage,'api_receipt');assert.equal(saved.publicUrl,publicUrl);assert.ok(secret);const envelope=parseDocsMdPublicationSecret(secret!);assert.ok(envelope);assert.equal(envelope.editToken,editToken);assert.equal(JSON.stringify(saved).includes(editToken),false);assert.equal(f.store.read().events.some(event=>event.message.includes(editToken)),false);assert.equal(isConfirmedDocsMdResultUrl(saved,publicUrl),true)}finally{f.cleanup()}}));

test('exact raw and visible HTML promote the same receipt and pass strict backup restore',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests,true)}});controller.runtime.aiReady=true;try{await controller.tick();const saved=f.store.read().tasks[0],secret=plaintextSecret(f.store);assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(requests.filter(item=>item.method==='GET').length,3);assert.equal(saved.status,'live');assert.equal(saved.health,'healthy');assert.equal(saved.linkCheck,'found');assert.equal(saved.checkpoint,'docs_md_published');assert.equal(saved.docsMd?.stage,'published');assert.equal(saved.publicUrl,publicUrl);assert.match(saved.linkRel??'',/nofollow/);const restored=validateBackup({state:f.store.read(),secrets:{['publication:'+taskId]:secret!}});assert.equal(restored.state.tasks[0].docsMd?.stage,'published');assert.equal(restored.state.tasks[0].status,'live')}finally{f.cleanup()}}));

test('SQLite restart reconciles a known ID with GET only and can later promote it',async()=>enabled(async()=>{const f=fixture(),first:Array<{method:string;url:string;body?:string}>=[];let reopened:Store|undefined;try{const initial=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:transport(f.store,first)}});initial.runtime.aiReady=true;await initial.tick();f.store.close();reopened=new Store(f.path);const second:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(reopened,vault(reopened),'fixture',{docsMdDependencies:{fetch:transport(reopened,second,true)}});controller.runtime.aiReady=true;await controller.tick();const saved=reopened.read().tasks[0];assert.equal(first.filter(item=>item.method==='POST').length,1);assert.equal(second.filter(item=>item.method==='POST').length,0);assert.ok(second.length>=3);assert.ok(second.every(item=>item.method==='GET'));assert.equal(saved.docsMd?.stage,'published');assert.equal(saved.status,'live')}finally{try{reopened?.close()}catch{}rmSync(f.directory,{recursive:true,force:true})}}));

test('an unknown POST outcome without an ID gets three local recovery decisions and never re-POSTs',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests,false,true)}});controller.runtime.aiReady=true;try{await controller.tick();for(let index=0;index<3;index++){f.store.update(state=>{const current=state.tasks[0];current.reconcileAfter=undefined});await controller.tick()}const saved=f.store.read().tasks[0];assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(requests.filter(item=>item.method==='GET').length,0);assert.equal(saved.docsMd?.stage,'submitting');assert.equal(saved.docsMd?.id,undefined);assert.equal(saved.reconcileAttempts,3);assert.equal(saved.status,'needs_input');assert.match(saved.message,/不会重发|不能重发/)}finally{f.cleanup()}}));

test('a receipt is retained when token encryption fails without leaking the token',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(f.store,vault(f.store,{failEncryption:true}),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests)}});controller.runtime.aiReady=true;try{await controller.tick();const saved=f.store.read().tasks[0];assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(saved.docsMd?.stage,'api_receipt');assert.equal(saved.publicUrl,publicUrl);assert.equal(f.store.getCipher('publication:'+taskId),undefined);assert.equal(JSON.stringify(saved).includes(editToken),false);assert.equal(f.store.read().events.some(event=>event.message.includes(editToken)),false)}finally{f.cleanup()}}));

test('a response receipt survives one persistence exception without bypassing the bound intent',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],original=f.store.update.bind(f.store);let failed=false;(f.store as unknown as {update:Store['update']}).update=(mutate=>{if(!failed&&f.store.read().tasks[0]?.docsMd?.stage==='submitting'){failed=true;throw Error('synthetic receipt commit failure')}return original(mutate)}) as Store['update'];const controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests)}});controller.runtime.aiReady=true;try{await controller.tick();const saved=f.store.read().tasks[0];assert.equal(failed,true);assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(saved.docsMd?.stage,'api_receipt');assert.equal(saved.docsMd?.id,publicId);assert.equal(saved.publicUrl,publicUrl);assert.equal(f.store.getCipher('publication:'+taskId),undefined)}finally{f.cleanup()}}));

test('Vault readiness blocks the POST before any durable remote intent',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[],controller=new Controller(f.store,vault(f.store,{available:false}),'fixture',{docsMdDependencies:{fetch:transport(f.store,requests)}});controller.runtime.aiReady=true;try{await controller.tick();const saved=f.store.read().tasks[0];assert.equal(requests.length,0);assert.equal(saved.docsMd,undefined);assert.equal(saved.submittedAt,undefined);assert.equal(saved.status,'needs_input');assert.equal(saved.checkpoint,'system_vault_unavailable')}finally{f.cleanup()}}));

test('a late verifier result cannot promote a replaced draft or receipt',async()=>enabled(async()=>{
  const pending=task({status:'review',submittedAt:stamp,checkpoint:'docs_md_api_receipt',publicUrl,health:'pending'}),identity=docsMdTaskIdentity(pending);assert.ok(identity);
  pending.docsMd={operationId:'docs_md_11111111111141118111111111111111',sourceHash:identity.sourceHash,requestHash:identity.requestHash,createdAt:stamp,stage:'api_receipt',id:publicId};
  const f=fixture(pending),controller=new Controller(f.store,vault(f.store),'fixture',{verifyDocsMd:async()=>{f.store.update(state=>{state.tasks[0].draft!.body+=' changed while verifying'});return {found:true,outcome:'found',url:publicUrl,rel:'nofollow ugc noopener noreferrer',reason:'synthetic visible match'}}});controller.runtime.aiReady=true;
  try{await controller.verify(taskId);const saved=f.store.read().tasks[0];assert.equal(saved.status,'review');assert.equal(saved.docsMd?.stage,'api_receipt');assert.equal(saved.checkpoint,'docs_md_api_receipt');assert.equal(saved.firstLiveAt,undefined);assert.equal(saved.linkCheck,undefined);assert.equal(f.store.read().events.some(event=>event.taskId===taskId&&event.message.includes('外链已核验生效')),false)}finally{f.cleanup()}
}));

test('successful verification settles its future reconciliation plan and keeps attempt history restorable',async()=>enabled(async()=>{const pending=task({status:'review',submittedAt:stamp,checkpoint:'docs_md_api_receipt',publicUrl,health:'pending',reconcileAttempts:1,reconcileAfter:'2099-10-10T00:00:00.000Z'}),identity=docsMdTaskIdentity(pending);assert.ok(identity);pending.docsMd={operationId:'docs_md_11111111111141118111111111111111',sourceHash:identity.sourceHash,requestHash:identity.requestHash,createdAt:stamp,stage:'api_receipt',id:publicId};const f=fixture(pending),controller=new Controller(f.store,vault(f.store),'fixture',{verifyDocsMd:async()=>({found:true,outcome:'found',url:publicUrl,rel:'nofollow ugc noopener noreferrer',reason:'synthetic exact acceptance'})});controller.runtime.aiReady=true;try{assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}));await controller.verify(taskId);const saved=f.store.read().tasks[0];assert.equal(saved.docsMd?.stage,'published');assert.equal(saved.status,'live');assert.equal(saved.reconcileAttempts,1);assert.equal(saved.reconcileAfter,undefined);assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}))}finally{f.cleanup()}}));

test('an unreachable read after a recorded loss preserves loss history in a restorable published state',async()=>enabled(async()=>{const prior=task({status:'needs_input',submittedAt:stamp,checkpoint:'docs_md_published',publicUrl,health:'missing',linkCheck:'absent',linkRel:'nofollow ugc noopener noreferrer',firstLiveAt:stamp,verifiedAt:stamp,lastCheckedAt:stamp,nextCheckAt:'2026-10-10T00:00:00.000Z',lostAt:stamp,reviewKind:'lost_link',consecutiveMissing:1}),identity=docsMdTaskIdentity(prior);assert.ok(identity);prior.docsMd={operationId:'docs_md_11111111111141118111111111111111',sourceHash:identity.sourceHash,requestHash:identity.requestHash,createdAt:stamp,stage:'published',id:publicId};const f=fixture(prior),controller=new Controller(f.store,vault(f.store),'fixture',{verifyDocsMd:async()=>({found:false,outcome:'unreachable',url:publicUrl,rel:'',reason:'synthetic read unavailable'})});controller.runtime.aiReady=true;try{assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}));await controller.verify(taskId);const saved=f.store.read().tasks[0];assert.equal(saved.docsMd?.stage,'published');assert.equal(saved.status,'needs_input');assert.equal(saved.health,'unknown');assert.equal(saved.linkCheck,'unreachable');assert.equal(saved.lostAt,stamp);assert.equal(saved.reviewKind,'lost_link');assert.equal(saved.consecutiveMissing,1);assert.doesNotThrow(()=>validateBackup({state:f.store.read(),secrets:{}}))}finally{f.cleanup()}}));

test('a draft replacement after the POST rejects late receipt attachment and never retries the POST',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[];let release:(value:Response)=>void=()=>{};const response=new Promise<Response>(resolve=>{release=resolve});let started!:()=>void;const began=new Promise<void>(resolve=>{started=resolve});const fetch:DocsMdTransport=async(url,init)=>{const method=init.method??'GET';requests.push({method,url,body:typeof init.body==='string'?init.body:undefined});if(method==='POST'){started();return response}throw Error('late receipt must not reach verification')};const controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch}});controller.runtime.aiReady=true;try{const running=controller.tick();await began;f.store.update(state=>{state.tasks[0].draft!.body+=' replaced'});release(new Response(JSON.stringify({success:true,id:publicId,url:publicUrl,rawUrl,editToken,expiresAt:0,rateLimit:{remaining:19}}),{status:200,headers:{'content-type':'application/json'}}));await running;const saved=f.store.read().tasks[0];assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(saved.docsMd?.stage,'submitting');assert.equal(saved.publicUrl,undefined);assert.equal(f.store.getCipher('publication:'+taskId),undefined);assert.notEqual(saved.status,'queued')}finally{f.cleanup()}}));

test('a site pause after the POST preserves only the durable intent and cannot re-POST on resume',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[];let release:(value:Response)=>void=()=>{};const response=new Promise<Response>(resolve=>{release=resolve});let started!:()=>void;const began=new Promise<void>(resolve=>{started=resolve});const fetch:DocsMdTransport=async(url,init)=>{const method=init.method??'GET';requests.push({method,url,body:typeof init.body==='string'?init.body:undefined});if(method==='POST'){started();return response}throw Error('an intent without an ID cannot perform a public read')};const controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch}});controller.runtime.aiReady=true;try{const running=controller.tick();await began;controller.sitePause(siteId,true);await running;release(new Response(JSON.stringify({success:true,id:publicId,url:publicUrl,rawUrl,editToken,expiresAt:0,rateLimit:{remaining:19}}),{status:200,headers:{'content-type':'application/json'}}));await new Promise(resolve=>setImmediate(resolve));let saved=f.store.read().tasks[0];assert.equal(f.store.read().sites[0].status,'paused');assert.equal(saved.docsMd?.stage,'submitting');assert.equal(saved.publicUrl,undefined);assert.equal(f.store.getCipher('publication:'+taskId),undefined);assert.equal(requests.filter(item=>item.method==='POST').length,1);f.store.update(state=>{state.sites[0].status='ready';state.tasks[0].reconcileAfter=undefined});await controller.tick();saved=f.store.read().tasks[0];assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(requests.filter(item=>item.method==='GET').length,0);assert.equal(saved.docsMd?.stage,'submitting')}finally{f.cleanup()}}));

test('deleting the site during a POST removes the task and rejects the late response without an orphan token',async()=>enabled(async()=>{const f=fixture(),requests:Array<{method:string;url:string;body?:string}>=[];let release:(value:Response)=>void=()=>{};const response=new Promise<Response>(resolve=>{release=resolve});let started!:()=>void;const began=new Promise<void>(resolve=>{started=resolve});const fetch:DocsMdTransport=async(url,init)=>{const method=init.method??'GET';requests.push({method,url,body:typeof init.body==='string'?init.body:undefined});if(method==='POST')started();return response};const controller=new Controller(f.store,vault(f.store),'fixture',{docsMdDependencies:{fetch}});controller.runtime.aiReady=true;try{const running=controller.tick();await began;controller.deleteSite(siteId);await running;release(new Response(JSON.stringify({success:true,id:publicId,url:publicUrl,rawUrl,editToken,expiresAt:0,rateLimit:{remaining:19}}),{status:200,headers:{'content-type':'application/json'}}));await new Promise(resolve=>setImmediate(resolve));assert.equal(requests.filter(item=>item.method==='POST').length,1);assert.equal(f.store.read().sites.length,0);assert.equal(f.store.read().tasks.length,0);assert.equal(f.store.getCipher('publication:'+taskId),undefined)}finally{f.cleanup()}}));
