import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { Store, emptyState } from '../src/main/store';
import { dateKey, monthKey, makePlan, nextTask, markVerified, recoverInterrupted, expireReviews, liveThisMonth } from '../src/main/planner';
import type { Channel, Site, Task } from '../src/shared/types';

const now=new Date('2026-09-26T04:00:00Z');
function fixture(){const s=emptyState();s.settings.timezone='Asia/Singapore';const site:Site={id:randomUUID(),domain:'example.com',url:'https://example.com',email:'hello@example.com',name:'Example',description:'A software tool',category:'software',language:'en',monthlyTarget:2,status:'ready',createdAt:now.toISOString(),analyzedAt:now.toISOString()};s.sites.push(site);const matches=Array.from({length:6},(_,i)=>({channel:{id:'c'+i,domain:`channel${i}.com`,automation:'browser',free:'yes',enabled:true} as Channel,score:90,reason:'Relevant'}));return {s,site,matches}}
test('natural month follows configured timezone, including UTC boundary',()=>{assert.equal(dateKey('2026-09-30T20:00:00Z','Asia/Singapore'),'2026-10-01');assert.equal(monthKey('2026-10-01T01:00:00Z','America/Los_Angeles'),'2026-09')});
test('default quota creates exactly two distinct sources within current month',()=>{const {s,site,matches}=fixture();const made=makePlan(s,site,matches,now);assert.equal(made.length,2);assert.equal(new Set(made.map(t=>t.sourceDomain)).size,2);assert(made.every(t=>monthKey(t.scheduledAt,s.settings.timezone)==='2026-09'))});
test('repeated planner calls and app ticks are idempotent',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);makePlan(s,site,matches,now);assert.equal(s.tasks.length,2)});
test('pending reviews reserve next-month slots without duplicated tasks',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);for(const t of s.tasks){t.status='review';t.reviewUntil='2026-10-20T00:00:00Z'}assert.equal(makePlan(s,site,matches,new Date('2026-10-01T00:00:00Z')).length,0)});
test('verification counts once in first-live month even on later reverification',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);const t=s.tasks[0];markVerified(t,new Date('2026-10-02T00:00:00Z'),'https://channel0.com/page','nofollow');markVerified(t,new Date('2026-11-02T00:00:00Z'),'https://channel0.com/page','nofollow');assert.equal(liveThisMonth(site.id,s.tasks,new Date('2026-10-05'),s.settings.timezone),1);assert.equal(liveThisMonth(site.id,s.tasks,new Date('2026-11-05'),s.settings.timezone),0)});
test('expired review releases slot but source remains used',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);s.tasks[0].status='review';s.tasks[0].reviewUntil='2026-09-25T00:00:00Z';const source=s.tasks[0].sourceDomain;expireReviews(s,now);assert.equal(s.tasks[0].status,'expired');const made=makePlan(s,site,matches,now);assert.equal(made.length,1);assert.notEqual(made[0].sourceDomain,source)});
test('paused sites and unknown-priced/manual channels do not enter auto queue',()=>{const {s,site,matches}=fixture();site.status='paused';assert.equal(makePlan(s,site,matches,now).length,0);site.status='ready';matches[0].channel.free='unknown';matches[1].channel.automation='manual';matches[2].channel.enabled=false;s.settings.channelOverrides.c3=false;const made=makePlan(s,site,matches,now);assert.deepEqual(made.map(t=>t.channelId),['c4','c5'])});
test('interrupted final submission never retries automatically',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);s.tasks[0].status='running';s.tasks[0].checkpoint='submitting';s.tasks[1].status='running';recoverInterrupted(s,now);assert.equal(s.tasks[0].status,'needs_input');assert.equal(s.tasks[1].status,'queued')});
test('lowered quota respects outstanding review before queued task',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);site.monthlyTarget=1;s.tasks[0].status='review';s.tasks[1].scheduledAt=now.toISOString();assert.equal(nextTask(s,now),undefined)});
test('finished quota and pause stop new claims',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);assert(nextTask(s,now));s.settings.autoRun=false;assert.equal(nextTask(s,now),undefined);s.settings.autoRun=true;site.monthlyTarget=1;markVerified(s.tasks[0],now,'https://channel0.com/a','');assert.equal(nextTask(s,new Date('2026-09-30')),undefined)});
test('attempt limit and future schedule cannot be claimed',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);s.tasks[0].attempts=s.settings.maxAttempts;assert.equal(nextTask(s,now),undefined)});
test('missed months do not multiply quota debt',()=>{const {s,site,matches}=fixture();assert.equal(makePlan(s,site,matches,new Date('2027-02-15')).length,2)});
test('SQLite update rollback leaves unchanged state on callback error',()=>{const store=new Store(':memory:');assert.throws(()=>store.update(s=>{s.settings.dailyAiLimit=1;throw Error('reject')}));assert.equal(store.read().settings.dailyAiLimit,40);store.close()});
test('SQLite snapshot is independent and secrets never enter state',()=>{const store=new Store(':memory:');store.setCipher('apiKey','encrypted-cipher');const snapshot=store.read();snapshot.settings.model='edited';assert.equal(store.read().settings.model,'');assert(!JSON.stringify(store.read()).includes('encrypted-cipher'));assert.equal(store.getCipher('apiKey'),'encrypted-cipher');store.close()});
test('restored queued final submission is quarantined before task claim',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);s.tasks[0].submittedAt=now.toISOString();s.tasks[0].checkpoint='submitting';recoverInterrupted(s,now);assert.equal(s.tasks[0].status,'needs_input');assert.equal(nextTask(s,now),undefined)});
test('restart before final write restores the reserved retry attempt',()=>{const {s,site,matches}=fixture();makePlan(s,site,matches,now);s.tasks[0].status='running';s.tasks[0].attempts=s.settings.maxAttempts;recoverInterrupted(s,now);assert.equal(s.tasks[0].attempts,s.settings.maxAttempts-1);assert.equal(nextTask(s,now)?.id,s.tasks[0].id)});
