import test from 'node:test';
import assert from 'node:assert/strict';
import {discoverTechnicalMaterial} from '../src/integrations/technical-material';
const site={url:'https://example.com/',domain:'example.com'};
const tool='<main><h1>计算公式与输入参数</h1><p>'+('解释实际计算方法和适用条件。'.repeat(40))+'</p><input type="number"><input type="number"><button>计算</button></main>';
function transport(pages:Record<string,string>){const calls:string[]=[];return {calls,fetch:(async(url:string)=>{calls.push(url);if(!(url in pages))throw Error('not found');return {url,html:pages[url]}}) as any}}
test('finds real first-party calculator without inventing developer ownership',async()=>{const io=transport({'https://example.com/':'<a href="/tools/fees/">费用工具</a>','https://example.com/tools/fees/':tool});assert.equal(await discoverTechnicalMaterial(site,undefined,io.fetch),'https://example.com/tools/fees/');assert.equal(io.calls.length,2)});
test('ignores external repository, contact forms and tool-name-only pages',async()=>{const io=transport({'https://example.com/':'<a href="https://github.com/other/project">代码工具</a><a href="/tools/">tools</a>','https://example.com/tools/':'<main><h1>工具</h1><form><input><button>联系我们</button></form></main>'});assert.equal(await discoverTechnicalMaterial(site,undefined,io.fetch),undefined);assert.equal(io.calls.length,2)});
test('does not infer permission from offsite redirect or scripts hidden in navigation',async()=>{const result=await discoverTechnicalMaterial(site,undefined,(async()=>({url:'https://foreign.example/tools/',html:tool})) as any);assert.equal(result,undefined)});
test('bounds candidate requests and stops after cancellation',async()=>{const io=transport({'https://example.com/':Array.from({length:20},(_,i)=>`<a href="/tools/${i}">tool</a>`).join(''),'https://example.com/tools/0':'<p>empty</p>','https://example.com/tools/1':'<p>empty</p>','https://example.com/tools/2':'<p>empty</p>'});assert.equal(await discoverTechnicalMaterial(site,undefined,io.fetch),undefined);assert.equal(io.calls.length,4);const abort=new AbortController();abort.abort();assert.equal(await discoverTechnicalMaterial(site,abort.signal,io.fetch),undefined)});
