import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash,generateKeyPairSync,sign} from 'node:crypto';
import {createReadStream} from 'node:fs';
import {cp,lstat,mkdir,mkdtemp,readFile,readdir,realpath,rename,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {UpdateManager,recoveryCommandFailure} from '../src/main/update-manager';
import type {UpdateHelperJob} from '../src/main/update-install';
import {UPDATE_MANIFEST_URL,UPDATE_SIGNATURE_URL} from '../src/main/update-network';
import {hashUpdateTree} from '../src/main/update-tree';

function fixture(version:string,asset:Buffer){
 const {privateKey,publicKey}=generateKeyPairSync('ed25519'),assetUrl=`https://github.com/xiaogan123/linkflow-desktop/releases/download/v${version}/Linkflow-${version}-windows-x64-setup.exe`,manifest={schemaVersion:1 as const,version,publishedAt:'2026-09-28T00:00:00.000Z',releaseNotes:'修复已知问题',assets:{'win32-x64':{url:assetUrl,size:asset.length,sha256:createHash('sha256').update(asset).digest('hex'),format:'nsis' as const}}},bytes=Buffer.from(JSON.stringify(manifest)),signature=Buffer.from(sign(null,bytes,privateKey).toString('base64')+'\n');
 const request=(async(input:RequestInfo|URL)=>{const url=String(input);if(url===UPDATE_MANIFEST_URL)return new Response(Uint8Array.from(bytes));if(url===UPDATE_SIGNATURE_URL)return new Response(Uint8Array.from(signature));if(url===assetUrl)return new Response(Uint8Array.from(asset),{headers:{'content-length':String(asset.length)}});return new Response(null,{status:404})}) as typeof fetch;
 return {publicKey,request,manifest};
}
function macFixture(version:string,asset:Buffer){
 const {privateKey,publicKey}=generateKeyPairSync('ed25519'),assetUrl=`https://github.com/xiaogan123/linkflow-desktop/releases/download/v${version}/Linkflow-${version}-mac-arm64.zip`,manifest={schemaVersion:1 as const,version,publishedAt:'2026-10-02T00:00:00.000Z',releaseNotes:'macOS 正式发布',assets:{'darwin-arm64':{url:assetUrl,size:asset.length,sha256:createHash('sha256').update(asset).digest('hex'),format:'zip' as const}}},bytes=Buffer.from(JSON.stringify(manifest)),signature=Buffer.from(sign(null,bytes,privateKey).toString('base64')+'\n');
 const request=(async(input:RequestInfo|URL)=>{const url=String(input);if(url===UPDATE_MANIFEST_URL)return new Response(Uint8Array.from(bytes));if(url===UPDATE_SIGNATURE_URL)return new Response(Uint8Array.from(signature));if(url===assetUrl)return new Response(Uint8Array.from(asset),{headers:{'content-length':String(asset.length)}});return new Response(null,{status:404})}) as typeof fetch;
 return {publicKey,request,manifest,bytes,signature,assetUrl,asset};
}
function options(directory:string,data:Pick<ReturnType<typeof fixture>,'publicKey'|'request'>){const applicationPath=join(directory,'installed');return {currentVersion:'1.1.0',platform:'win32' as const,arch:'x64',packaged:true,updatesDirectory:join(directory,'updates'),applicationPath,executablePath:join(applicationPath,'外链助手.exe'),helperPath:join(applicationPath,'resources','app.asar','dist-electron','update-helper.cjs'),publicKey:data.publicKey,request:data.request,pid:999999}}

async function recoveryFixture(directory:string){
 const root=await realpath(directory),parent=join(root,'Applications'),applicationPath=join(parent,'外链助手.app'),executablePath=join(applicationPath,'Contents','MacOS','外链助手'),helperPath=join(applicationPath,'Contents','Resources','app.asar','dist-electron','update-helper.cjs'),updatesDirectory=join(root,'user-data','updates'),artifactPath=join(updatesDirectory,'Linkflow-1.2.3-darwin-arm64.zip'),artifact=Buffer.from('signed archive'),jobPath=join(updatesDirectory,'install-recovery.json'),backupPath=join(parent,'.外链助手.app.linkflow-backup-recovery'),helperRuntimePath=join(updatesDirectory,'helper-runtime-recovery'),stageRoot=join(parent,'.linkflow-update-1.2.3'),stagedApplicationPath=join(stageRoot,'外链助手.app'),mountRoot=join(root,'AppTranslocation','test'),runtimeApplicationPath=join(mountRoot,'d','外链助手.app'),runtimeExecutablePath=join(runtimeApplicationPath,'Contents','MacOS','外链助手'),token='00000000-0000-4000-8000-000000000001';
 await mkdir(join(applicationPath,'Contents','MacOS'),{recursive:true});await mkdir(join(applicationPath,'Contents','Resources','app.asar','dist-electron'),{recursive:true});await writeFile(executablePath,'new application',{mode:0o755});await writeFile(helperPath,'helper');await mkdir(join(backupPath,'Contents','MacOS'),{recursive:true});await writeFile(join(backupPath,'Contents','MacOS','外链助手'),'old application',{mode:0o755});await mkdir(helperRuntimePath,{recursive:true});await mkdir(updatesDirectory,{recursive:true});await writeFile(artifactPath,artifact);await mkdir(join(runtimeApplicationPath,'..'),{recursive:true});await cp(applicationPath,runtimeApplicationPath,{recursive:true});const stagedTreeSha256=await hashUpdateTree(applicationPath);
 const job:UpdateHelperJob={schemaVersion:1,token,platform:'darwin-arm64',oldPid:123,targetVersion:'1.2.3',updatesDirectory,artifactPath,artifactSize:artifact.length,artifactSha256:createHash('sha256').update(artifact).digest('hex'),applicationPath,executablePath,backupPath,helperRuntimePath,readyPath:jobPath+'.ready',armPath:jobPath+'.armed',startupRequestPath:join(updatesDirectory,'startup-request.json'),startupAckPath:join(updatesDirectory,'startup-ack'),stagedApplicationPath,stagedTreeSha256,receiptPath:join(updatesDirectory,'installed.json'),errorPath:join(updatesDirectory,'install-error.json')};
 await writeFile(jobPath,JSON.stringify(job));await writeFile(job.startupRequestPath,JSON.stringify({schemaVersion:1,targetVersion:job.targetVersion,token}));await writeFile(job.errorPath,JSON.stringify({schemaVersion:1,targetVersion:job.targetVersion,failedAt:'2026-10-02T00:00:00.000Z',message:'preserved',recoveryJobPath:jobPath}));
 let installedVerified=false,runtimeVerified=false;const guardedRm=(async(path:Parameters<typeof rm>[0],value?:Parameters<typeof rm>[1])=>{if(String(path)===backupPath)assert(installedVerified&&runtimeVerified,'rollback copy was removed before both application trees were verified');return rm(path,value)}) as typeof rm;
 const data=fixture('1.3.0',Buffer.from('installer')),config={...options(root,data),currentVersion:'1.2.3',platform:'darwin' as const,arch:'arm64',updatesDirectory,applicationPath,executablePath,helperPath,runtimeApplicationPath,runtimeExecutablePath,pid:456,files:{rm:guardedRm},recoveryPorts:{isAlive:(pid:number)=>pid===456,hashTree:async(path:string)=>{const digest=await hashUpdateTree(path);if(path===applicationPath)installedVerified=true;if(path===runtimeApplicationPath)runtimeVerified=true;return digest},execute:async(file:string,args:string[])=>{if(file==='/bin/ps')return `${runtimeExecutablePath} --type=browser\n`;if(file==='/sbin/mount')return `synthetic on ${mountRoot} (nullfs, read-only, nobrowse)\n`;if(file==='/usr/bin/plutil')return args[1]==='CFBundleIdentifier'?'com.linkflow.personal\n':'1.2.3\n';if(file==='/usr/bin/lipo')return 'arm64\n';if(file==='/usr/bin/xattr')return '0081;test;Linkflow;\n';if(file==='/usr/bin/codesign')return '';throw Error(`unexpected command ${file}`)}}};
 return {config,job,jobPath,backupPath,updatesDirectory,verification:()=>({installedVerified,runtimeVerified})};
}

type SupersedeRuntimeMode='persistent'|'translocated';
async function supersedeFixture(directory:string,runtimeMode:SupersedeRuntimeMode='persistent'){
 const root=await realpath(directory),parent=join(root,'Applications'),applicationPath=join(parent,'外链助手.app'),executablePath=join(applicationPath,'Contents','MacOS','外链助手'),helperPath=join(applicationPath,'Contents','Resources','app.asar','dist-electron','update-helper.cjs'),updatesDirectory=join(root,'user-data','updates'),oldArtifactPath=join(updatesDirectory,'Linkflow-1.2.3-darwin-arm64.zip'),oldArtifact=Buffer.from('old signed archive'),jobPath=join(updatesDirectory,'install-supersede.json'),backupPath=join(parent,'.外链助手.app.linkflow-backup-supersede'),helperRuntimePath=join(updatesDirectory,'helper-runtime-supersede'),stagedApplicationPath=join(parent,'.linkflow-update-1.2.3','外链助手.app'),mountRoot=join(root,'AppTranslocation','supersede'),runtimeApplicationPath=runtimeMode==='persistent'?applicationPath:join(mountRoot,'d','外链助手.app'),runtimeExecutablePath=runtimeMode==='persistent'?executablePath:join(runtimeApplicationPath,'Contents','MacOS','外链助手'),officialTemplate=join(root,'official','外链助手.app'),token='00000000-0000-4000-8000-000000000002',currentArtifact=Buffer.from('current signed mac archive'),data=macFixture('1.2.4',currentArtifact);
 await mkdir(join(applicationPath,'Contents','MacOS'),{recursive:true});await mkdir(join(applicationPath,'Contents','Resources','app.asar','dist-electron'),{recursive:true});await writeFile(executablePath,'current application',{mode:0o755});await writeFile(helperPath,'current helper');await mkdir(join(backupPath,'Contents','MacOS'),{recursive:true});await writeFile(join(backupPath,'Contents','MacOS','外链助手'),'old application',{mode:0o755});await mkdir(helperRuntimePath,{recursive:true});await mkdir(updatesDirectory,{recursive:true});await writeFile(oldArtifactPath,oldArtifact);if(runtimeMode==='translocated'){await mkdir(join(runtimeApplicationPath,'..'),{recursive:true});await cp(applicationPath,runtimeApplicationPath,{recursive:true})}await mkdir(join(root,'official'),{recursive:true});await cp(applicationPath,officialTemplate,{recursive:true});
 const job:UpdateHelperJob={schemaVersion:1,token,platform:'darwin-arm64',oldPid:123,targetVersion:'1.2.3',updatesDirectory,artifactPath:oldArtifactPath,artifactSize:oldArtifact.length,artifactSha256:createHash('sha256').update(oldArtifact).digest('hex'),applicationPath,executablePath,backupPath,helperRuntimePath,readyPath:jobPath+'.ready',armPath:jobPath+'.armed',startupRequestPath:join(updatesDirectory,'startup-request.json'),startupAckPath:join(updatesDirectory,'startup-ack'),stagedApplicationPath,stagedTreeSha256:'a'.repeat(64),receiptPath:join(updatesDirectory,'installed.json'),errorPath:join(updatesDirectory,'install-error.json')};
 await writeFile(jobPath,JSON.stringify(job));await writeFile(job.startupRequestPath,JSON.stringify({schemaVersion:1,targetVersion:job.targetVersion,token}));await writeFile(job.errorPath,JSON.stringify({schemaVersion:1,targetVersion:job.targetVersion,failedAt:'2026-10-02T00:00:00.000Z',message:'preserved',cleanupPath:helperRuntimePath,recoveryJobPath:jobPath}));
 let mountChecks=0,requestImplementation=data.request;const hashedPaths:string[]=[],requestLog:string[]=[],streamedPaths:string[]=[],readPaths:string[]=[],lstatPaths:string[]=[],renamedPaths:Array<{from:string;to:string}>=[],commandLog:Array<{file:string;args:string[]}>=[];
 let executeImplementation=async(file:string,args:string[])=>{if(file==='/usr/bin/ditto'){const destination=args.at(-1)!;await cp(officialTemplate,join(destination,'外链助手.app'),{recursive:true});return ''}if(file==='/bin/ps'&&args[0]==='-axo')return `456 ${runtimeExecutablePath}\n`;if(file==='/bin/ps')return `${runtimeExecutablePath} --type=browser\n`;if(file==='/sbin/mount'){mountChecks+=1;return `synthetic on ${mountRoot} (nullfs, read-only, nobrowse)\n`}if(file==='/usr/bin/plutil')return args[1]==='CFBundleIdentifier'?'com.linkflow.personal\n':'1.2.4\n';if(file==='/usr/bin/lipo')return 'arm64\n';if(file==='/usr/bin/xattr')return '0081;test;Linkflow;\n';if(file==='/usr/bin/codesign')return '';throw Error(`unexpected command ${file}`)};
 const request=(async(input:RequestInfo|URL,init?:RequestInit)=>{requestLog.push(String(input));return requestImplementation(input,init)}) as typeof fetch,execute=async(file:string,args:string[])=>{commandLog.push({file,args:[...args]});return executeImplementation(file,args)},trackedReadFile=((...args:Parameters<typeof readFile>)=>{readPaths.push(String(args[0]));return readFile(...args)}) as typeof readFile,trackedLstat=((...args:Parameters<typeof lstat>)=>{lstatPaths.push(String(args[0]));return lstat(...args)}) as typeof lstat,trackedCreateReadStream=((path:string)=>{streamedPaths.push(path);return createReadStream(path)}) as typeof createReadStream,trackedRename=(async(from:Parameters<typeof rename>[0],to:Parameters<typeof rename>[1])=>{renamedPaths.push({from:String(from),to:String(to)});return rename(from,to)}) as typeof rename;
 const config={...options(root,data),request,currentVersion:'1.2.4',platform:'darwin' as const,arch:'arm64',updatesDirectory,applicationPath,executablePath,helperPath,runtimeApplicationPath,runtimeExecutablePath,pid:456,files:{readFile:trackedReadFile,lstat:trackedLstat,createReadStream:trackedCreateReadStream,rename:trackedRename},recoveryPorts:{isAlive:(pid:number)=>pid===456,hashTree:async(path:string)=>{hashedPaths.push(path);return hashUpdateTree(path)},execute}};
 return {config,data,job,jobPath,backupPath,updatesDirectory,applicationPath,runtimeApplicationPath,officialTemplate,hashedPaths,requestLog,streamedPaths,readPaths,lstatPaths,renamedPaths,commandLog,mountChecks:()=>mountChecks,getRequest:()=>requestImplementation,setRequest:(value:typeof fetch)=>{requestImplementation=value},getExecute:()=>executeImplementation,setExecute:(value:typeof executeImplementation)=>{executeImplementation=value}};
}

test('manager checks, streams, verifies, persists, and restores a prepared update',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),asset=Buffer.alloc(128*1024,7),data=fixture('1.2.0',asset);try{
  const manager=new UpdateManager(options(directory,data));assert.equal((await manager.initialize()).phase,'idle');const available=await manager.check();assert.equal(available.phase,'available');assert.equal(available.releaseNotes,'修复已知问题');
  const promise=manager.download();assert.equal(manager.status().phase,'downloading');const prepared=await promise;assert.equal(prepared.phase,'prepared');assert.equal(prepared.progress?.percent,100);
  const restored=new UpdateManager(options(directory,data));assert.equal((await restored.initialize()).phase,'prepared');
  const stored=JSON.parse(await readFile(join(directory,'updates','prepared.json'),'utf8'));assert.equal(stored.manifest,Buffer.from(JSON.stringify(data.manifest)).toString('base64'));
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('hash mismatch never reaches prepared and exposes no source URL or local path',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),signed=Buffer.from('signed payload'),served=Buffer.from('tampered data');
 try{
  // Use a valid signed manifest request, then swap only the asset response.
  const valid=fixture('1.2.0',signed),request=(async(input:RequestInfo|URL,init?:RequestInit)=>String(input)===valid.manifest.assets['win32-x64'].url?new Response(Uint8Array.from(served),{headers:{'content-length':String(served.length)}}):valid.request(input,init)) as typeof fetch,manager=new UpdateManager({...options(directory,valid),request});
  assert.equal((await manager.check()).phase,'available');const failed=await manager.download();assert.equal(failed.phase,'failed');assert.equal(failed.retryable,true);assert(!failed.error?.includes(directory));assert(!failed.error?.includes('github.com'));
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('temporary-file cleanup failures cannot leave download state stuck',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),signed=Buffer.from('signed payload'),served=Buffer.from('tampered data'),data=fixture('1.2.0',signed),base=data.request;let blockCleanup=false;try{
  const request=(async(input:RequestInfo|URL,init?:RequestInit)=>String(input)===data.manifest.assets['win32-x64'].url?new Response(Uint8Array.from(served),{headers:{'content-length':String(served.length)}}):base(input,init)) as typeof fetch,guardedRm=(async(path:Parameters<typeof rm>[0],options?:Parameters<typeof rm>[1])=>{if(blockCleanup&&String(path).endsWith('.part'))throw Error('synthetic antivirus lock');return rm(path,options)}) as typeof rm,manager=new UpdateManager({...options(directory,data),request,files:{rm:guardedRm}});await manager.initialize();await manager.check();blockCleanup=true;const failed=await manager.download();assert.equal(failed.phase,'failed');assert.equal(failed.retryable,true);assert.notEqual(manager.status().phase,'downloading');
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('cancel aborts an active stream and returns to a retryable available state',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),asset=Buffer.alloc(100,1),data=fixture('1.2.0',asset),base=data.request;let assetStarted=()=>{};const started=new Promise<void>(done=>{assetStarted=done});
 const request=(async(input:RequestInfo|URL,init?:RequestInit)=>{if(String(input)!==data.manifest.assets['win32-x64'].url)return base(input,init);return new Response(new ReadableStream<Uint8Array>({start(controller){controller.enqueue(asset.subarray(0,1));assetStarted();init?.signal?.addEventListener('abort',()=>controller.error(Error('aborted')),{once:true})}}))}) as typeof fetch;
 try{const manager=new UpdateManager({...options(directory,data),request});await manager.check();const completion=manager.download();await started;assert.equal(manager.cancel().phase,'downloading');const state=await completion;assert.equal(state.phase,'available');assert.equal(state.error,'下载已取消');assert.equal(state.retryable,true)}finally{await rm(directory,{recursive:true,force:true})}
});

test('install returns only after helper readiness handshake and keeps userdata outside replacement',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),asset=Buffer.from('installer'),data=fixture('1.2.0',asset);try{
  const config=options(directory,data);await mkdir(join(config.applicationPath,'resources','app.asar','dist-electron'),{recursive:true});await writeFile(config.executablePath,'old app');await writeFile(config.helperPath,'helper');const manager=new UpdateManager({...config,launchHelper:(_exe,args)=>{void (async()=>{const job=JSON.parse(await readFile(args[1],'utf8'));await writeFile(job.readyPath,job.token)})();return {pid:321,once:()=>{},unref:()=>{}}}});
  await manager.initialize();await manager.check();await manager.download();const handoff=await manager.install();assert.equal(handoff.accepted,true);assert.equal(manager.status().phase,'installing');assert.equal(await readFile(config.executablePath,'utf8'),'old app');
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('install re-hashes the prepared artifact immediately before helper handoff',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),asset=Buffer.from('installer'),data=fixture('1.2.0',asset);try{
  const config=options(directory,data),manager=new UpdateManager(config);await manager.initialize();await manager.check();await manager.download();await writeFile(join(config.updatesDirectory,'Linkflow-1.2.0-win32-x64.exe'),Buffer.from('tampered!'));await assert.rejects(manager.install(),/完整性/);assert.equal(manager.status().phase,'failed');
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('helper is never armed when readiness cleanup fails',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),asset=Buffer.from('installer'),data=fixture('1.2.0',asset);try{
  const config=options(directory,data);await mkdir(join(config.applicationPath,'resources','app.asar','dist-electron'),{recursive:true});await writeFile(config.executablePath,'old app');await writeFile(config.helperPath,'helper');const guardedRm=(async(path:Parameters<typeof rm>[0],options?:Parameters<typeof rm>[1])=>{if(String(path).endsWith('.ready')){const error=Error('synthetic lock') as NodeJS.ErrnoException;error.code='EPERM';throw error}return rm(path,options)}) as typeof rm,manager=new UpdateManager({...config,files:{rm:guardedRm},launchHelper:(_exe,args)=>{void (async()=>{const job=JSON.parse(await readFile(args[1],'utf8'));await writeFile(job.readyPath,job.token)})();return {pid:321,once:()=>{},unref:()=>{}}}});await manager.initialize();await manager.check();await manager.download();await assert.rejects(manager.install());assert.equal(manager.status().phase,'prepared');assert.equal((await readdir(config.updatesDirectory)).some(name=>name.endsWith('.armed')),false);
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('helper arm commit is atomic when the final rename fails',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),asset=Buffer.from('installer'),data=fixture('1.2.0',asset);try{
  const config=options(directory,data);await mkdir(join(config.applicationPath,'resources','app.asar','dist-electron'),{recursive:true});await writeFile(config.executablePath,'old app');await writeFile(config.helperPath,'helper');const guardedRename=(async(from:Parameters<typeof rename>[0],to:Parameters<typeof rename>[1])=>{if(String(to).endsWith('.armed')){const error=Error('synthetic rename failure') as NodeJS.ErrnoException;error.code='EPERM';throw error}return rename(from,to)}) as typeof rename,manager=new UpdateManager({...config,files:{rename:guardedRename},launchHelper:(_exe,args)=>{void (async()=>{const job=JSON.parse(await readFile(args[1],'utf8'));await writeFile(job.readyPath,job.token)})();return {pid:321,once:()=>{},unref:()=>{}}}});await manager.initialize();await manager.check();await manager.download();await assert.rejects(manager.install());assert.equal(manager.status().phase,'prepared');const names=await readdir(config.updatesDirectory);assert.equal(names.some(name=>name.endsWith('.armed')),false);assert.equal(names.some(name=>name.endsWith('.armed.tmp')),false);
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('only the running target version can acknowledge a GUI startup request',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),data=fixture('1.3.0',Buffer.from('installer')),config={...options(directory,data),currentVersion:'1.2.0'},token='00000000-0000-4000-8000-000000000001';try{
  await mkdir(config.updatesDirectory,{recursive:true});await writeFile(join(config.updatesDirectory,'startup-request.json'),JSON.stringify({schemaVersion:1,targetVersion:'1.2.0',token}));const manager=new UpdateManager(config);assert.equal(await manager.acknowledgeStartup(),true);assert.equal(await readFile(join(config.updatesDirectory,'startup-ack'),'utf8'),token);assert.equal(manager.status().phase,'installed');
  await writeFile(join(config.updatesDirectory,'startup-request.json'),JSON.stringify({schemaVersion:1,targetVersion:'9.9.9',token}));assert.equal(await manager.acknowledgeStartup(),false);
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('a late startup cannot claim an uncertain preserved Mac transaction was installed',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),data=fixture('1.3.0',Buffer.from('installer')),config={...options(directory,data),currentVersion:'1.2.0',platform:'darwin' as const,arch:'arm64'},token='00000000-0000-4000-8000-000000000001';try{
  await mkdir(config.updatesDirectory,{recursive:true});await writeFile(join(config.updatesDirectory,'startup-request.json'),JSON.stringify({schemaVersion:1,targetVersion:'1.2.0',token}));await writeFile(join(config.updatesDirectory,'install-error.json'),JSON.stringify({schemaVersion:1,targetVersion:'1.2.0',failedAt:new Date().toISOString(),message:'preserved',recoveryJobPath:join(config.updatesDirectory,'install-job.json')}));const manager=new UpdateManager(config);assert.equal(await manager.acknowledgeStartup(),false);await assert.rejects(readFile(join(config.updatesDirectory,'startup-ack')));
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('late Gatekeeper approval commits only the authenticated translocated Mac transaction',{skip:process.platform==='darwin'?false:'macOS-only recovery protocol'},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-late-recovery-'));try{const recovery=await recoveryFixture(directory),manager=new UpdateManager(recovery.config);const initial=await manager.initialize();assert.equal(initial.phase,'failed');assert.equal(initial.retryable,false);assert.equal(await manager.acknowledgeStartup(),true);assert.equal(manager.status().phase,'installed');assert.deepEqual(recovery.verification(),{installedVerified:true,runtimeVerified:true});assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);assert.equal((await lstat(recovery.jobPath)).isFile(),true);await assert.rejects(lstat(join(recovery.updatesDirectory,'install-error.json')));const receipt=JSON.parse(await readFile(join(recovery.updatesDirectory,'installed.json'),'utf8'));assert.equal(receipt.recoveryJobCleanupPath,recovery.jobPath);const restarted=new UpdateManager(recovery.config);assert.equal((await restarted.initialize()).phase,'installed');await assert.rejects(lstat(recovery.backupPath));await assert.rejects(lstat(recovery.jobPath));await assert.rejects(lstat(join(recovery.updatesDirectory,'startup-request.json')));await assert.rejects(lstat(join(recovery.updatesDirectory,'installed.json')))
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('late Mac recovery stays locked for forged, stale, unsigned or incomplete state',{skip:process.platform==='darwin'?false:'macOS-only recovery protocol'},async t=>{
 const cases:Array<{name:string;mutate:(value:Awaited<ReturnType<typeof recoveryFixture>>)=>Promise<void>}>= [
  {name:'wrong request token',mutate:async value=>{await writeFile(value.job.startupRequestPath,JSON.stringify({schemaVersion:1,targetVersion:value.job.targetVersion,token:'00000000-0000-4000-8000-000000000099'}))}},
  {name:'wrong executable path',mutate:async value=>{value.job.executablePath=join(value.job.applicationPath,'Contents','MacOS','other');await writeFile(value.jobPath,JSON.stringify(value.job))}},
  {name:'old backup is the live process',mutate:async value=>{value.config.runtimeApplicationPath=value.backupPath;value.config.runtimeExecutablePath=join(value.backupPath,'Contents','MacOS','外链助手')}},
  {name:'wrong installed tree hash',mutate:async value=>{value.job.stagedTreeSha256='0'.repeat(64);await writeFile(value.jobPath,JSON.stringify(value.job))}},
  {name:'wrong target version',mutate:async value=>{value.job.targetVersion='9.9.9';await writeFile(value.jobPath,JSON.stringify(value.job))}},
  {name:'live bundle reports an old version',mutate:async value=>{const run=value.config.recoveryPorts.execute;value.config.recoveryPorts.execute=async(file,args)=>file==='/usr/bin/plutil'&&args[1]==='CFBundleShortVersionString'?'1.2.2\n':run(file,args)}},
  {name:'live bundle reports the wrong architecture',mutate:async value=>{const run=value.config.recoveryPorts.execute;value.config.recoveryPorts.execute=async(file,args)=>file==='/usr/bin/lipo'?'x86_64\n':run(file,args)}},
  {name:'code signature verification fails',mutate:async value=>{const run=value.config.recoveryPorts.execute;value.config.recoveryPorts.execute=async(file,args)=>{if(file==='/usr/bin/codesign')throw Error('invalid signature');return run(file,args)}}},
  {name:'durable app lost quarantine',mutate:async value=>{const run=value.config.recoveryPorts.execute;value.config.recoveryPorts.execute=async(file,args)=>file==='/usr/bin/xattr'?'0000;test;Linkflow;\n':run(file,args)}},
  {name:'wrong artifact hash',mutate:async value=>{value.job.artifactSha256='f'.repeat(64);await writeFile(value.jobPath,JSON.stringify(value.job))}},
  {name:'incomplete job',mutate:async value=>{const incomplete={...value.job} as Partial<UpdateHelperJob>;delete incomplete.stagedTreeSha256;await writeFile(value.jobPath,JSON.stringify(incomplete))}}
 ];
 for(const scenario of cases)await t.test(scenario.name,async()=>{const directory=await mkdtemp(join(tmpdir(),'linkflow-late-recovery-reject-'));try{const recovery=await recoveryFixture(directory);await scenario.mutate(recovery);const manager=new UpdateManager(recovery.config),initial=await manager.initialize();assert.equal(initial.phase,'failed');assert.equal(initial.retryable,false);assert.equal(await manager.acknowledgeStartup(),false);assert.equal(manager.status().phase,'failed');assert.equal(manager.status().retryable,false);assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);assert.equal((await lstat(recovery.jobPath)).isFile(),true);assert.equal((await lstat(join(recovery.updatesDirectory,'install-error.json'))).isFile(),true);await assert.rejects(lstat(join(recovery.updatesDirectory,'startup-ack')));await assert.rejects(lstat(join(recovery.updatesDirectory,'installed.json')));assert.deepEqual(await manager.check(),manager.status())}finally{await rm(directory,{recursive:true,force:true})}})
});

test('a newer running Mac release supersedes an older frozen transaction only after signed three-tree verification',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-recovery-'));try{
  const recovery=await supersedeFixture(directory),progress:string[]=[],manager=new UpdateManager({...recovery.config,emit:state=>{if(state.phase==='checking'&&state.recoveryPending)progress.push(state.error??'')}}),initial=await manager.initialize();assert.equal(initial.recoveryPending,true);assert.equal(initial.targetVersion,'1.2.3');
  assert.equal(await manager.acknowledgeStartup(),false);await assert.rejects(lstat(join(recovery.updatesDirectory,'startup-ack')));
  const state=await manager.supersedeRecovery();assert.equal(state.phase,'up-to-date');assert.equal(state.currentVersion,'1.2.4');assert.equal(state.targetVersion,'1.2.4');assert.equal(state.recoveryPending,false);
  assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);assert.equal((await lstat(recovery.jobPath)).isFile(),true);assert.equal((await lstat(recovery.job.artifactPath)).isFile(),true);assert.equal((await lstat(recovery.job.helperRuntimePath)).isDirectory(),true);assert.equal((await lstat(recovery.job.startupRequestPath)).isFile(),true);await assert.rejects(lstat(join(recovery.updatesDirectory,'install-error.json')));await assert.rejects(lstat(recovery.job.startupAckPath));await assert.rejects(lstat(recovery.job.receiptPath));
  const archives=(await readdir(recovery.updatesDirectory)).filter(name=>name.startsWith('superseded-supersede-by-1.2.4-'));assert.equal(archives.length,1);const archive=join(recovery.updatesDirectory,archives[0]),record=JSON.parse(await readFile(join(archive,'superseded.json'),'utf8'));assert.equal(record.status,'superseded');assert.equal(record.oldTargetVersion,'1.2.3');assert.equal(record.currentVersion,'1.2.4');assert.equal(record.runtimeTranslocated,false);assert.equal(record.signedArtifactSha256,recovery.data.manifest.assets['darwin-arm64'].sha256);assert.equal((await lstat(join(archive,'install-error.original.json'))).isFile(),true);assert.equal((await lstat(join(archive,'install-job.snapshot.json'))).isFile(),true);assert.equal((await lstat(join(archive,'startup-request.snapshot.json'))).isFile(),true);assert.equal((await lstat(join(archive,'signed-manifest.json'))).isFile(),true);assert.equal((await lstat(join(archive,'Linkflow-1.2.4-darwin-arm64.zip'))).isFile(),true);assert(recovery.renamedPaths.some(value=>value.from===recovery.job.errorPath&&value.to===join(archive,'install-error.original.json')));
  assert.equal(recovery.mountChecks(),0);assert.equal(recovery.hashedPaths.filter(path=>path===recovery.applicationPath).length,2);assert(recovery.hashedPaths.some(path=>path.includes('.supersede-verify-')));
  assert.deepEqual(progress,['正在核对上次更新事务材料…','正在验证当前正式版本的签名发布信息…','正在建立受控恢复验证空间…','正在下载并校验当前正式版本安装包…','正在安全解包当前正式版本…','正在确认当前运行进程的安装来源…','正在核对官方安装包内的应用身份…','正在核对“应用程序”中的当前应用身份…','正在核对当前运行应用副本的身份…','正在确认当前运行进程的安装来源…','正在下载并校验当前正式版本安装包…','正在安全归档上次更新事务…']);
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('a native Mac AppTranslocation runtime is superseded only after its mount is confirmed',{skip:process.platform==='darwin'?false:'macOS-only AppTranslocation mount shape'},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-translocated-'));try{const recovery=await supersedeFixture(directory,'translocated'),manager=new UpdateManager(recovery.config);assert.notEqual(await realpath(recovery.applicationPath),await realpath(recovery.runtimeApplicationPath));assert.equal((await manager.initialize()).recoveryPending,true);const state=await manager.supersedeRecovery();assert.equal(state.phase,'up-to-date');assert.equal(state.recoveryPending,false);assert.equal(recovery.mountChecks(),1);assert(recovery.hashedPaths.includes(recovery.applicationPath));assert(recovery.hashedPaths.includes(recovery.runtimeApplicationPath));assert(recovery.hashedPaths.some(path=>path.includes('.supersede-verify-')));const archive=(await readdir(recovery.updatesDirectory)).find(name=>name.startsWith('superseded-supersede-by-1.2.4-'))!;assert.equal(JSON.parse(await readFile(join(recovery.updatesDirectory,archive,'superseded.json'),'utf8')).runtimeTranslocated,true)}finally{await rm(directory,{recursive:true,force:true})}
});

test('recovery exposes a controlled stage while the signed artifact download is pending',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-progress-'));let releaseDownload=()=>{};try{const recovery=await supersedeFixture(directory),base=recovery.getRequest();let markStarted=()=>{};const started=new Promise<void>(done=>{markStarted=done}),held=new Promise<void>(done=>{releaseDownload=done});recovery.setRequest((async(input:RequestInfo|URL,init?:RequestInit)=>{if(String(input)===recovery.data.assetUrl){markStarted();await held}return base(input,init)}) as typeof fetch);const manager=new UpdateManager(recovery.config);await manager.initialize();const completion=manager.supersedeRecovery();await started;assert.deepEqual(manager.status(),{phase:'checking',currentVersion:'1.2.4',targetVersion:'1.2.3',retryable:false,recoveryPending:true,error:'正在下载并校验当前正式版本安装包…'});releaseDownload();assert.equal((await completion).recoveryPending,false)}finally{releaseDownload();await rm(directory,{recursive:true,force:true})}
});

test('superseding an old Mac transaction fails closed for untrusted or incomplete evidence',async t=>{
 type Recovery=Awaited<ReturnType<typeof supersedeFixture>>;const transactionFailure='无法确认上次更新事务材料完整；恢复副本和原事务已保留',releaseFailure='无法验证当前正式版本的签名发布信息；恢复副本和原事务已保留',artifactFailure='无法下载或校验当前正式版本安装包；恢复副本和原事务已保留',extractionFailure='无法安全解包当前正式版本；恢复副本和原事务已保留',processFailure='无法确认当前运行进程对应真实安装应用；恢复副本和原事务已保留',officialFailure='官方安装包内的应用身份未通过验证；恢复副本和原事务已保留',installedFailure='“应用程序”中的当前应用身份未通过验证；恢复副本和原事务已保留',cases:Array<{name:string;expected:string;mutate:(value:Recovery)=>Promise<void>|void;assertReached:(value:Recovery)=>void}>=[
  {name:'wrong frozen request token',expected:transactionFailure,mutate:async value=>{await writeFile(value.job.startupRequestPath,JSON.stringify({schemaVersion:1,targetVersion:value.job.targetVersion,token:'00000000-0000-4000-8000-000000000099'}))},assertReached:value=>{assert(value.readPaths.includes(value.job.startupRequestPath));assert.equal(value.requestLog.length,0)}},
  {name:'recovery job path changed',expected:transactionFailure,mutate:async value=>{await writeFile(join(value.updatesDirectory,'install-error.json'),JSON.stringify({schemaVersion:1,targetVersion:value.job.targetVersion,failedAt:'2026-10-02T00:00:00.000Z',message:'preserved',cleanupPath:value.job.helperRuntimePath,recoveryJobPath:join(value.updatesDirectory,'install-missing.json')}))},assertReached:value=>{assert(value.lstatPaths.includes(join(value.updatesDirectory,'install-missing.json')));assert.equal(value.requestLog.length,0)}},
  {name:'old artifact hash changed',expected:transactionFailure,mutate:async value=>{value.job.artifactSha256='f'.repeat(64);await writeFile(value.jobPath,JSON.stringify(value.job))},assertReached:value=>{assert(value.streamedPaths.includes(value.job.artifactPath));assert.equal(value.requestLog.length,0)}},
  {name:'frozen job is incomplete',expected:transactionFailure,mutate:async value=>{const incomplete={...value.job} as Partial<UpdateHelperJob>;delete incomplete.stagedTreeSha256;await writeFile(value.jobPath,JSON.stringify(incomplete))},assertReached:value=>{assert(value.readPaths.includes(value.jobPath));assert(!value.readPaths.includes(value.job.startupRequestPath));assert.equal(value.requestLog.length,0)}},
  {name:'current version is not the signed latest release',expected:releaseFailure,mutate:value=>{const newer=macFixture('1.2.5',Buffer.from('newer signed archive'));value.config.publicKey=newer.publicKey;value.setRequest(newer.request)},assertReached:value=>{assert(value.requestLog.includes(UPDATE_MANIFEST_URL));assert(value.requestLog.includes(UPDATE_SIGNATURE_URL));assert.equal(value.requestLog.length,2)}},
  {name:'manifest signature is invalid',expected:releaseFailure,mutate:value=>{const base=value.getRequest();value.setRequest((async(input:RequestInfo|URL,init?:RequestInit)=>String(input)===UPDATE_SIGNATURE_URL?new Response(Uint8Array.from(Buffer.from('invalid\n'))):base(input,init)) as typeof fetch)},assertReached:value=>{assert(value.requestLog.includes(UPDATE_MANIFEST_URL));assert(value.requestLog.includes(UPDATE_SIGNATURE_URL));assert(!value.requestLog.includes(value.data.assetUrl))}},
  {name:'served official artifact hash differs',expected:artifactFailure,mutate:value=>{const base=value.getRequest(),asset=value.data.asset;value.setRequest((async(input:RequestInfo|URL,init?:RequestInit)=>String(input)===value.data.assetUrl?new Response(Uint8Array.from(Buffer.alloc(asset.length,7)),{headers:{'content-length':String(asset.length)}}):base(input,init)) as typeof fetch)},assertReached:value=>{assert(value.requestLog.includes(value.data.assetUrl));assert(!value.hashedPaths.length)}},
  {name:'official artifact extraction fails with private details',expected:extractionFailure,mutate:value=>{const run=value.getExecute();value.setExecute(async(file,args)=>{if(file==='/usr/bin/ditto')throw Error(`private ${value.applicationPath} token=secret`);return run(file,args)})},assertReached:value=>{assert(value.commandLog.some(command=>command.file==='/usr/bin/ditto'));assert.equal(value.hashedPaths.length,0)}},
  {name:'official bundle signature fails',expected:officialFailure,mutate:value=>{const run=value.getExecute();value.setExecute(async(file,args)=>{if(file==='/usr/bin/codesign'&&args.at(-1)?.includes('.supersede-verify-'))throw Error('private signature diagnostic');return run(file,args)})},assertReached:value=>{assert(value.commandLog.some(command=>command.file==='/usr/bin/codesign'&&command.args.at(-1)?.includes('.supersede-verify-')));assert(value.hashedPaths.some(path=>path.includes('.supersede-verify-')))}},
  {name:'official extracted tree differs',expected:installedFailure,mutate:async value=>{await writeFile(join(value.officialTemplate,'official-only.txt'),'different')},assertReached:value=>{assert(value.hashedPaths.some(path=>path.includes('.supersede-verify-')));assert(value.hashedPaths.includes(value.applicationPath))}},
  {name:'persistent application tree differs',expected:installedFailure,mutate:async value=>{await writeFile(join(value.applicationPath,'persistent-only.txt'),'different')},assertReached:value=>{assert(value.hashedPaths.some(path=>path.includes('.supersede-verify-')));assert(value.hashedPaths.includes(value.applicationPath))}},
  {name:'running process command is not exact',expected:processFailure,mutate:value=>{const run=value.getExecute();value.setExecute(async(file,args)=>file==='/bin/ps'&&args[0]==='-p'?'/Applications/other.app/Contents/MacOS/other\n':run(file,args))},assertReached:value=>{assert(value.commandLog.some(command=>command.file==='/bin/ps'&&command.args[0]==='-p'));assert.equal(value.hashedPaths.length,0)}},
  {name:'old helper still has a live process',expected:transactionFailure,mutate:value=>{const run=value.getExecute();value.setExecute(async(file,args)=>file==='/bin/ps'&&args[0]==='-axo'?`789 ${join(value.job.helperRuntimePath,'外链助手.app','Contents','MacOS','外链助手')}\n`:run(file,args))},assertReached:value=>{assert(value.commandLog.some(command=>command.file==='/bin/ps'&&command.args[0]==='-axo'));assert.equal(value.requestLog.length,0)}}
 ];
 for(const scenario of cases)await t.test(scenario.name,async()=>{const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-reject-'));try{const recovery=await supersedeFixture(directory);await scenario.mutate(recovery);const manager=new UpdateManager(recovery.config),initial=await manager.initialize();assert.equal(initial.recoveryPending,true);await assert.rejects(manager.supersedeRecovery(),{message:scenario.expected});scenario.assertReached(recovery);const state=manager.status();assert.equal(state.phase,'failed');assert.equal(state.retryable,false);assert.equal(state.recoveryPending,true);assert.equal(state.error,scenario.expected);assert(!state.error?.includes(directory));assert(!state.error?.includes('token=secret'));assert.equal((await lstat(join(recovery.updatesDirectory,'install-error.json'))).isFile(),true);assert.equal((await lstat(recovery.jobPath)).isFile(),true);assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);assert(!recovery.renamedPaths.some(value=>value.from===recovery.job.errorPath));await assert.rejects(lstat(recovery.job.startupAckPath));await assert.rejects(lstat(recovery.job.receiptPath));assert.deepEqual(await manager.check(),state)}finally{await rm(directory,{recursive:true,force:true})}})
});

test('an independent runtime without a confirmed Mac translocation mount stays locked',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-unconfirmed-runtime-'));try{const recovery=await supersedeFixture(directory,'translocated'),run=recovery.getExecute();recovery.setExecute(async(file,args)=>file==='/sbin/mount'?'synthetic on /other (nullfs, read-only, nobrowse)\n':run(file,args));assert.notEqual(await realpath(recovery.applicationPath),await realpath(recovery.runtimeApplicationPath));const manager=new UpdateManager(recovery.config);await manager.initialize();await assert.rejects(manager.supersedeRecovery(),/无法确认当前运行进程/);assert(recovery.commandLog.some(command=>command.file==='/sbin/mount'));assert.equal(recovery.hashedPaths.length,0);assert.equal(manager.status().recoveryPending,true);assert(!recovery.renamedPaths.some(value=>value.from===recovery.job.errorPath))}finally{await rm(directory,{recursive:true,force:true})}
});

test('a changed translocated runtime tree is rejected after native Mac mount confirmation',{skip:process.platform==='darwin'?false:'macOS-only AppTranslocation tree verification'},async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-runtime-tree-'));try{const recovery=await supersedeFixture(directory,'translocated');await writeFile(join(recovery.runtimeApplicationPath,'runtime-only.txt'),'different');const manager=new UpdateManager(recovery.config);await manager.initialize();await assert.rejects(manager.supersedeRecovery(),/运行应用副本的身份未通过验证/);assert.equal(recovery.mountChecks(),1);assert(recovery.hashedPaths.includes(recovery.runtimeApplicationPath));assert.equal(manager.status().recoveryPending,true);assert(!recovery.renamedPaths.some(value=>value.from===recovery.job.errorPath))}finally{await rm(directory,{recursive:true,force:true})}
});

test('a failed final archive commit keeps the old block and a later verified retry can finish',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-commit-'));try{
  const recovery=await supersedeFixture(directory),errorPath=join(recovery.updatesDirectory,'install-error.json'),guardedRename=(async(from:Parameters<typeof rename>[0],to:Parameters<typeof rename>[1])=>{if(String(from)===errorPath)throw Error('synthetic final commit interruption');return rename(from,to)}) as typeof rename,first=new UpdateManager({...recovery.config,files:{rename:guardedRename}});await first.initialize();await assert.rejects(first.supersedeRecovery(),/旧更新事务未能安全归档/);assert.match(first.status().error!,/旧更新事务未能安全归档/);assert.equal(first.status().recoveryPending,true);assert.equal((await lstat(errorPath)).isFile(),true);assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);await assert.rejects(lstat(recovery.job.startupAckPath));await assert.rejects(lstat(recovery.job.receiptPath));const incompleteArchives=(await readdir(recovery.updatesDirectory)).filter(name=>name.startsWith('superseded-supersede-by-1.2.4-'));assert.equal(incompleteArchives.length,1);assert.equal((await lstat(join(recovery.updatesDirectory,incompleteArchives[0],'superseded.json'))).isFile(),true);
  const retry=new UpdateManager(recovery.config);assert.equal((await retry.initialize()).recoveryPending,true);const state=await retry.supersedeRecovery();assert.equal(state.recoveryPending,false);await assert.rejects(lstat(errorPath));assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);await assert.rejects(lstat(recovery.job.startupAckPath));await assert.rejects(lstat(recovery.job.receiptPath));const archives=(await readdir(recovery.updatesDirectory)).filter(name=>name.startsWith('superseded-supersede-by-1.2.4-'));assert.equal(archives.length,2);const committed=await Promise.all(archives.map(async name=>{try{return (await lstat(join(recovery.updatesDirectory,name,'install-error.original.json'))).isFile()}catch{return false}}));assert.equal(committed.filter(Boolean).length,1);
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('an unresolved recovery transaction stays visible and blocks the normal update flow',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),data=fixture('1.2.0',Buffer.from('installer')),config={...options(directory,data),platform:'darwin' as const,arch:'arm64'},recoveryJobPath=join(directory,'updates','install-recovery.json');try{
  await mkdir(config.updatesDirectory,{recursive:true});await writeFile(recoveryJobPath,'{}');await writeFile(join(config.updatesDirectory,'install-error.json'),JSON.stringify({schemaVersion:1,targetVersion:'1.2.0',failedAt:new Date().toISOString(),message:'preserved',recoveryJobPath}));const manager=new UpdateManager(config),state=await manager.initialize();assert.equal(state.phase,'failed');assert.equal(state.retryable,false);assert.match(state.error!,/恢复副本/);assert.deepEqual(await manager.check(),state);await assert.rejects(manager.download(),/恢复副本/);await assert.rejects(manager.install(),/恢复副本/);assert.deepEqual(manager.status(),state);
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('Mac startup acknowledgement carries the live runtime identity',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),data=fixture('1.3.0',Buffer.from('installer')),runtimeApplicationPath=join(directory,'AppTranslocation','id','d','外链助手.app'),runtimeExecutablePath=join(runtimeApplicationPath,'Contents','MacOS','外链助手'),config={...options(directory,data),currentVersion:'1.2.0',platform:'darwin' as const,arch:'arm64',runtimeApplicationPath,runtimeExecutablePath,pid:456},token='00000000-0000-4000-8000-000000000001';try{
  await mkdir(config.updatesDirectory,{recursive:true});await writeFile(join(config.updatesDirectory,'startup-request.json'),JSON.stringify({schemaVersion:1,targetVersion:'1.2.0',token}));const manager=new UpdateManager(config);assert.equal(await manager.acknowledgeStartup(),true);assert.deepEqual(JSON.parse(await readFile(join(config.updatesDirectory,'startup-ack'),'utf8')),{schemaVersion:2,targetVersion:'1.2.0',token,pid:456,applicationPath:runtimeApplicationPath,executablePath:runtimeExecutablePath});
 }finally{await rm(directory,{recursive:true,force:true})}
});

test('a signed release without this platform is unsupported instead of becoming downloadable',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-update-')),data=fixture('1.2.0',Buffer.from('installer'));try{const manager=new UpdateManager({...options(directory,data),platform:'darwin',arch:'arm64'});assert.equal((await manager.check()).phase,'unsupported');assert.equal(manager.status().targetVersion,'1.2.0');await assert.rejects(manager.download())}finally{await rm(directory,{recursive:true,force:true})}
});

test('notification failures cannot undo a committed superseded transaction',async()=>{const directory=await mkdtemp(join(tmpdir(),'linkflow-supersede-notify-'));try{const recovery=await supersedeFixture(directory),manager=new UpdateManager({...recovery.config,emit:()=>{throw Error('unavailable UI')}});await manager.initialize();const state=await manager.supersedeRecovery();assert.equal(state.phase,'up-to-date');assert.equal(state.recoveryPending,false);assert.equal((await manager.check()).phase,'up-to-date');await assert.rejects(lstat(recovery.job.errorPath));await assert.rejects(lstat(recovery.job.startupAckPath));await assert.rejects(lstat(recovery.job.receiptPath));assert((await lstat(recovery.backupPath)).isDirectory());}finally{await rm(directory,{recursive:true,force:true})}});

test('disk artifact tamper after identity is classified as artifact rather than process',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-stage-audit-'));
 try{
  const recovery=await supersedeFixture(directory),run=recovery.getExecute();let artifactPath='',identityChecks=0;
  recovery.setExecute(async(file,args)=>{
   if(file==='/usr/bin/ditto')artifactPath=args[3];
   if(file==='/bin/ps'&&args[0]==='-p'&&++identityChecks===2)await writeFile(artifactPath,Buffer.alloc(recovery.data.asset.length,7));
   return run(file,args);
  });
  const manager=new UpdateManager(recovery.config);await manager.initialize();
  let message='';try{await manager.supersedeRecovery()}catch(error){message=(error as Error).message}
  const facts={identityChecks,actualFailure:message,retainsError:(await lstat(recovery.job.errorPath)).isFile(),retainsBackup:(await lstat(recovery.backupPath)).isDirectory(),recoveryPending:manager.status().recoveryPending};
  assert.equal(facts.identityChecks,2);assert.equal(facts.retainsError,true);assert.equal(facts.retainsBackup,true);assert.equal(facts.recoveryPending,true);
  assert.equal(message,'无法下载或校验当前正式版本安装包；恢复副本和原事务已保留');
 }finally{await rm(directory,{recursive:true,force:true})}
});


test('native recovery diagnostics expose only fixed command and bounded status categories',()=>{
 const error=recoveryCommandFailure('/usr/bin/ditto',{code:1,signal:'SIGTERM'},'ditto: /private/example/token-secret: Operation not permitted');
 assert.equal(error.message,'解包工具：退出码 1，SIGTERM，系统拒绝文件访问');
 assert.doesNotMatch(error.message,/private-owner|token-secret|Users/);
 assert.equal(recoveryCommandFailure('/private/path',{code:'SECRET',signal:'TOKEN'}).message,'系统校验工具：执行失败');
 assert.equal(recoveryCommandFailure('/usr/bin/ditto',{killed:true}).message,'解包工具：执行已超时或终止');
});

test('native extraction failure keeps old recovery data and reports a sanitized diagnostic',async()=>{
 const directory=await mkdtemp(join(tmpdir(),'linkflow-native-extraction-error-'));
 try{
  const recovery=await supersedeFixture(directory),execute=recovery.getExecute();
  recovery.setExecute(async(file,args)=>{if(file==='/usr/bin/ditto')throw recoveryCommandFailure(file,{code:1},'secret path: No space left on device');return execute(file,args)});
  const manager=new UpdateManager(recovery.config);await manager.initialize();
  await assert.rejects(manager.supersedeRecovery(),/无法安全解包.*退出码 1，磁盘空间不足/);
  assert.doesNotMatch(manager.status().error??'',/secret path/);assert.equal(manager.status().recoveryPending,true);
  assert.equal((await lstat(recovery.job.errorPath)).isFile(),true);assert.equal((await lstat(recovery.backupPath)).isDirectory(),true);
 }finally{await rm(directory,{recursive:true,force:true})}
});
