import {useCallback, useEffect, useMemo, useRef, useState} from 'react';
import type {FormEvent, ReactNode} from 'react';
import {
  ArrowClockwise, ArrowLeft, ArrowSquareOut, Bell, CalendarBlank, CaretDown,
  CheckCircle, Clock, Copy, DownloadSimple, DotsThree, Eye, FileText, Funnel,
  Gear, House, Info, Leaf, LinkSimple, MagnifyingGlass, Pause, PencilSimple,
  Play, Plus, ShieldCheck, SlidersHorizontal, Trash, UploadSimple, UserCircle,
  WarningCircle, X
} from '@phosphor-icons/react';
import type {Account, Category, Channel, Settings, Site, Snapshot, Task, TaskStatus} from '../shared/types';
import {demoSnapshot} from './demo';

type Page = 'overview'|'channels'|'accounts'|'settings'|'site';
type Modal = 'add'|'editSite'|'account'|'draft'|'url'|'backupExport'|'backupImport'|'deleteSite'|'deleteAccount'|null;
type IconType = typeof House;
const categoryText:Record<Category,string>={software:'软件',ai:'人工智能',developer:'开发工具',design:'设计',business:'商业',content:'内容',education:'教育',finance:'金融',general:'综合'};
const taskText:Record<TaskStatus,string>={queued:'等待执行',running:'执行中',needs_input:'需要处理',review:'等待审核',live:'已生效',failed:'执行失败',skipped:'已跳过',expired:'已失效'};
const taskTone:Record<TaskStatus,string>={queued:'muted',running:'blue',needs_input:'amber',review:'blue',live:'green',failed:'red',skipped:'muted',expired:'red'};
const fmt = (date?:string) => {if(!date)return '—'; const d=new Date(date);return Number.isNaN(d.getTime())?date:new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric'}).format(d)};
const fullDate = new Intl.DateTimeFormat('zh-CN',{year:'numeric',month:'long',day:'numeric',weekday:'long'}).format(new Date());
const monthOf=(value:string,timezone:string)=>{try{return new Intl.DateTimeFormat('en-CA',{timeZone:timezone,year:'numeric',month:'2-digit'}).format(new Date(value))}catch{return value.slice(0,7)}};
const errorText=(e:unknown)=>e instanceof Error?e.message:String(e);
const cleanDomain=(value:string)=>value.trim().replace(/^https?:\/\//i,'').replace(/\/.*$/,'').toLowerCase();
const isDomain=(value:string)=>/^(?=.{1,253}$)(?!-)[a-z0-9-]+(?:\.[a-z0-9-]+)+$/i.test(value);
const isEmail=(value:string)=>/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value.trim());

function Button({children,onClick,disabled=false,variant='secondary',type='button',className='',title}:{children:ReactNode;onClick?:()=>void;disabled?:boolean;variant?:'primary'|'secondary'|'text'|'danger';type?:'button'|'submit';className?:string;title?:string}){
  return <button type={type} title={title} className={`button ${variant} ${className}`} onClick={onClick} disabled={disabled}>{children}</button>;
}
function Empty({icon:Icon=LinkSimple,title,body,action}:{icon?:IconType;title:string;body:string;action?:ReactNode}){
  return <div className="empty"><div className="empty-icon"><Icon size={28}/></div><h3>{title}</h3><p>{body}</p>{action}</div>;
}
function Dialog({title,children,onClose,width='medium'}:{title:string;children:ReactNode;onClose:()=>void;width?:'medium'|'wide'}){
  const ref=useRef<HTMLDivElement>(null);
  useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const first=ref.current?.querySelector<HTMLElement>('.dialog-form input,.dialog-form select,.dialog-form textarea')??ref.current?.querySelector<HTMLElement>('button');first?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose();if(e.key==='Tab'&&ref.current){const all=[...ref.current.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')];if(!all.length)return;const first=all[0],last=all[all.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener('keydown',onKey);return()=>{document.removeEventListener('keydown',onKey);previous?.focus()}},[onClose]);
  return <div className="dialog-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><div ref={ref} className={`dialog ${width}`} role="dialog" aria-modal="true" aria-label={title}><div className="dialog-head"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="关闭"><X size={20}/></button></div>{children}</div></div>;
}
function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){return <label className="field"><span>{label}</span>{children}{hint&&<small>{hint}</small>}</label>}

export default function App(){
  const [snapshot,setSnapshot]=useState<Snapshot|null>(null);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState('');
  const [demo,setDemo]=useState(false),[page,setPage]=useState<Page>('overview'),[modal,setModal]=useState<Modal>(null);
  const [selectedSite,setSelectedSite]=useState(''),[selectedTask,setSelectedTask]=useState(''),[selectedAccount,setSelectedAccount]=useState('');
  const [pending,setPending]=useState(false),[siteSearch,setSiteSearch]=useState(''),[channelSearch,setChannelSearch]=useState('');
  const [channelFilter,setChannelFilter]=useState('all'),[taskFilter,setTaskFilter]=useState('all');
  const [domain,setDomain]=useState(''),[email,setEmail]=useState(''),[target,setTarget]=useState(2);
  const [name,setName]=useState(''),[description,setDescription]=useState(''),[category,setCategory]=useState<Category>('general'),[language,setLanguage]=useState('zh');
  const [accountChannel,setAccountChannel]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[revealed,setRevealed]=useState<Record<string,string>>({});
  const [draftTitle,setDraftTitle]=useState(''),[draftDescription,setDraftDescription]=useState(''),[draftBody,setDraftBody]=useState(''),[url,setUrl]=useState(''),[passphrase,setPassphrase]=useState('');
  const [settings,setSettings]=useState<Settings|null>(null),[apiKey,setApiKey]=useState(''),[mailPassword,setMailPassword]=useState('');
  const settingsDirty=useRef(false);
  const api=window.linkflow;
  const refresh=useCallback(async()=>{if(!window.linkflow){setSnapshot(null);setLoading(false);return}try{const next=await window.linkflow.invoke<Snapshot>('snapshot');setSnapshot(next)}catch(e){setError(errorText(e))}finally{setLoading(false)}},[]);
  useEffect(()=>{void refresh();const unsub=window.linkflow?.onChange(()=>{void refresh()});return()=>unsub?.()},[refresh]);
  useEffect(()=>{settingsDirty.current=false;setSettings(demo?demoSnapshot.settings:snapshot?.settings??null)},[demo]);
  useEffect(()=>{if(!demo&&!settingsDirty.current)setSettings(snapshot?.settings??null)},[snapshot,demo]);
  const data=demo?demoSnapshot:snapshot;
  const act=useCallback(async<T,>(command:string,payload?:unknown,success?:string):Promise<T|undefined>=>{if(demo){setError('演示模式仅供预览。请关闭演示模式后操作真实数据。');return}if(!window.linkflow){setError('桌面服务未连接。请在客户端中打开，或开启演示模式预览。');return}setPending(true);setError('');setNotice('');try{const result=await window.linkflow.invoke<T>(command,payload);if(!['snapshot','settings:test-ai','settings:test-mail','account:reveal','external:open','task:open','data:export','backup:export'].includes(command))await refresh();if(success)setNotice(success);return result}catch(e){setError(errorText(e));return}finally{setPending(false)}},[demo,refresh]);
  const close=useCallback(()=>{setModal(null);setPassphrase('');setPassword('')},[]);
  const site=data?.sites.find(s=>s.id===selectedSite);
  const chosenTask=data?.tasks.find(t=>t.id===selectedTask);
  const account=data?.accounts.find(a=>a.id===selectedAccount);
  const liveThisMonth=(siteId?:string)=>{const zone=data?.settings.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;const month=monthOf(new Date().toISOString(),zone);return new Set(data?.tasks.filter(t=>(!siteId||t.siteId===siteId)&&t.firstLiveAt&&monthOf(t.firstLiveAt,zone)===month).map(t=>`${t.siteId}:${t.sourceDomain}`)).size};
  const total=data?.sites.reduce((n,s)=>n+s.monthlyTarget,0)??0,live=liveThisMonth();
  const progress=Math.min(100,total?Math.round(live/total*100):0);
  const attention=data?.tasks.filter(t=>t.status==='needs_input'||t.status==='failed'||t.status==='expired')??[];
  const firstAttention=attention[0];
  const siteForTask=(t:Task)=>data?.sites.find(s=>s.id===t.siteId);
  const channelForTask=(t:Task)=>data?.channels.find(c=>c.id===t.channelId);
  const zone=data?.settings.timezone||Intl.DateTimeFormat().resolvedOptions().timeZone;
  const [planYear,planMonth]=monthOf(new Date().toISOString(),zone).split('-').map(Number);
  const nextPlan=new Date(Date.UTC(planYear,planMonth,1));
  const nextDate=new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',timeZone:'UTC'}).format(nextPlan);
  const nextSiteDate=(site:Site)=>{if(site.status==='paused')return '已暂停';const next=data?.tasks.filter(t=>t.siteId===site.id&&t.status==='queued').sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt))[0];return next?new Intl.DateTimeFormat('zh-CN',{month:'long',day:'numeric',timeZone:zone}).format(new Date(next.scheduledAt)):nextDate};
  const selectSite=(id:string)=>{setSelectedSite(id);setPage('site');setTaskFilter('all')};
  const openAdd=()=>{setDomain('');setEmail('');setTarget(2);setModal('add')};
  const openEdit=(s:Site)=>{setSelectedSite(s.id);setName(s.name);setDescription(s.description);setCategory(s.category);setLanguage(s.language);setTarget(s.monthlyTarget);setEmail(s.email);setModal('editSite')};
  const openAccount=(a?:Account)=>{setSelectedAccount(a?.id??'');setAccountChannel(a?.channelId??data?.channels[0]?.id??'');setEmail(a?.email??'');setUsername(a?.username??'');setPassword('');setModal('account')};
  const openDraft=(t:Task)=>{setSelectedTask(t.id);setDraftTitle(t.draft?.title??'');setDraftDescription(t.draft?.description??'');setDraftBody(t.draft?.body??'');setModal('draft')};
  const openUrl=(t:Task)=>{setSelectedTask(t.id);setUrl(t.publicUrl??'');setModal('url')};
  const saveAdd=async(e:FormEvent)=>{e.preventDefault();const d=cleanDomain(domain);if(!isDomain(d)||!isEmail(email)){setError('请输入有效的域名和联系邮箱。');return}if(!Number.isInteger(target)||target<1||target>20){setError('每月目标须为 1–20 个。');return}const result=await act('site:add',{domain:d,email:email.trim(),monthlyTarget:target},'网站已添加，正在分析。');if(result)close()};
  const saveSite=async(e:FormEvent)=>{e.preventDefault();if(!site||!isEmail(email)){setError('请输入有效的联系邮箱。');return}if(!Number.isInteger(target)||target<1||target>20){setError('每月目标须为 1–20 个。');return}const result=await act('site:update',{id:site.id,name,description,category,language,monthlyTarget:target,email:email.trim()},'网站资料已保存。');if(result)close()};
  const saveAccount=async(e:FormEvent)=>{e.preventDefault();if(!accountChannel||!isEmail(email)||!username.trim()){setError('请选择渠道，并填写有效邮箱和用户名。');return}const result=await act('account:save',{id:selectedAccount||undefined,channelId:accountChannel,email:email.trim(),username:username.trim(),password:password||undefined},'账号已保存。');if(result)close()};
  const submitSimple=async(e:FormEvent,command:string,payload:unknown,message:string)=>{e.preventDefault();const result=await act(command,payload,message);if(result)close()};
  const statLabel=(s:Site)=>{const ts=data?.tasks.filter(t=>t.siteId===s.id)??[];if(s.status==='paused')return ['已暂停','muted'];if(s.status==='analyzing')return ['分析中','blue'];if(ts.some(t=>t.status==='needs_input'))return ['需要验证','amber'];if(ts.some(t=>t.status==='failed'||t.status==='expired'))return ['需要处理','red'];if(liveThisMonth(s.id)>=s.monthlyTarget)return ['本月完成','green'];if(ts.some(t=>t.status==='review'))return ['等待审核','blue'];return ['计划中','blue']};
  const nav=(to:Page)=>{setPage(to);setError('');setNotice('')};

  return <div className="app-shell">
    <aside className="sidebar"><div className="traffic" aria-hidden="true"/><div className="brand"><span className="brand-mark"><LinkSimple size={38} weight="bold"/></span><div><strong>外链助手</strong><small>LINKFLOW</small></div></div>
      <nav aria-label="主导航" className="nav"><NavButton icon={House} active={page==='overview'||page==='site'} onClick={()=>nav('overview')}>总览</NavButton><NavButton icon={FileText} active={page==='channels'} onClick={()=>nav('channels')}>渠道</NavButton><NavButton icon={UserCircle} active={page==='accounts'} onClick={()=>nav('accounts')}>账号</NavButton></nav>
      <div className="sidebar-bottom"><NavButton icon={Gear} active={page==='settings'} onClick={()=>nav('settings')}>设置</NavButton><div className="runtime-indicator"><span className={`dot ${demo?'blue':data?.runtime.busy?'green':data?.settings.autoRun?'green':'gray'}`}/><div><strong>{demo?'演示模式':data?.runtime.busy?'正在执行':data?.settings.autoRun?'自动执行中':'自动执行已暂停'}</strong><small>{demo?'仅供预览':data?'系统按计划运行':'等待桌面服务'}</small></div></div></div>
    </aside>
    <main className="main"><div className="topline"><span>个人工作空间</span><span>{fullDate}</span></div>
      {!api&&!demo&&<div className="banner warning"><WarningCircle size={20}/> 桌面服务未连接。可在浏览器中开启演示模式预览界面。<Button variant="text" onClick={()=>setDemo(true)}>开启演示模式</Button></div>}
      {api&&!demo&&<div className="demo-switch"><label><input type="checkbox" checked={false} onChange={()=>setDemo(true)}/> 演示模式</label></div>}
      {demo&&<button className="demo-exit" onClick={()=>setDemo(false)}>演示模式 · 返回真实数据</button>}
      {error&&<div role="alert" className="banner error"><WarningCircle size={18}/><span>{error}</span><button aria-label="关闭错误" onClick={()=>setError('')}><X size={18}/></button></div>}
      {notice&&<div role="status" className="banner success"><CheckCircle size={18}/><span>{notice}</span><button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={18}/></button></div>}
      {loading&&!data?<div className="loading">正在读取本地数据…</div>:
      page==='overview'?<div className="overview page"><div className="hero"><div><h1>外链，井然有序。</h1><p>系统按计划推进，你只需关注结果。</p></div><Button variant="primary" className="add-button" onClick={openAdd} disabled={pending}><Plus size={24}/>添加网站</Button></div>
        <div className="overview-grid"><div className="overview-primary"><section className="metric"><h2>本月已生效</h2><div className="metric-number"><strong>{live}</strong><span>/ {total}</span></div><div className="bar-row"><div className="progress-track"><span style={{width:`${progress}%`}}/></div><b>{progress}%</b></div><p>已完成 {live} 个 · 本月目标 {total} 个（{data?.sites.length&&data.sites.every(s=>s.monthlyTarget===2)?'每个网站 2 个 / 月':'按各网站目标计算'}）</p><div className="metric-meta"><span><CalendarBlank size={22}/>下一轮计划：{nextDate}</span><span><Leaf size={22}/>仅使用免费渠道 · 自动排队 · 次月自动继续</span></div></section>
          <section className="site-list-section"><div className="section-title"><div><h2>网站列表</h2>{demo&&<span className="demo-tag">演示数据</span>}</div><div className="section-tools"><span>每个网站 {data?.sites.length&&data.sites.every(s=>s.monthlyTarget===2)?'2 个 / 月':'按各站目标'} </span><button className="icon-button" onClick={()=>document.getElementById('site-search')?.focus()} aria-label="筛选网站"><SlidersHorizontal size={21}/></button></div></div>
          {!!data?.sites.length&&<div className="list-search"><MagnifyingGlass size={17}/><input id="site-search" placeholder="搜索网站或邮箱" value={siteSearch} onChange={e=>setSiteSearch(e.target.value)}/></div>}
          {data?.sites.length?<div className="site-table"><div className="site-table-header"><span>网站</span><span>每月目标</span><span>本月进度</span><span>状态</span><span>下次计划</span><span/></div>{data.sites.filter(s=>`${s.domain} ${s.email} ${s.name}`.toLowerCase().includes(siteSearch.toLowerCase())).map(s=>{const count=liveThisMonth(s.id),[label,tone]=statLabel(s),pct=Math.min(100,Math.round(count/s.monthlyTarget*100));return <div className="site-row" key={s.id}><button className="site-name" onClick={()=>selectSite(s.id)}><span className="avatar">{s.domain[0].toUpperCase()}</span><span><strong>{s.domain}</strong><small>{s.email}</small></span></button><span>{s.monthlyTarget} / 月</span><div className="row-progress"><strong>{count} / {s.monthlyTarget}</strong><div><span className="mini-track"><i style={{width:`${pct}%`}}/></span><small>{pct}%</small></div></div><span><span className={`badge ${tone}`}>{label}</span></span><span className="next-date">{nextSiteDate(s)}</span><button aria-label={`查看 ${s.domain} 详情`} className="icon-button row-more" onClick={()=>selectSite(s.id)}><DotsThree size={23}/></button></div>})}{!data.sites.some(s=>`${s.domain} ${s.email} ${s.name}`.toLowerCase().includes(siteSearch.toLowerCase()))&&<Empty title="没有匹配的网站" body="试试其他关键词。"/>}</div>:<Empty title="先添加第一个网站" body="只需域名和联系邮箱。系统会分析网站并建立月度计划。" action={<Button variant="primary" onClick={openAdd} disabled={demo}><Plus size={18}/>添加网站</Button>}/>}</section></div>
          <aside className="insight"><div className="insight-card attention-card"><div className="attention-main"><h3><Info size={28} weight="fill"/>需要你处理</h3>{firstAttention?<><p className="insight-domain">{siteForTask(firstAttention)?.domain??'未知网站'}</p><h2>{firstAttention.status==='needs_input'?'邮箱验证':firstAttention.status==='expired'?'外链已失效':'任务失败'}</h2><p>{firstAttention.message||'请查看任务详情并处理。'}<br/>完成后将自动继续，无需手动安排。</p><Button variant="primary" onClick={()=>{selectSite(firstAttention.siteId);setSelectedTask(firstAttention.id)}}>去处理</Button></>:<><h2>一切进展顺利</h2><p>{data?.sites.length?'目前没有需要你处理的事项。':'添加网站后，这里会集中显示需要你处理的事项。'}</p></>}</div><div className="insight-divider"/><div className="next-plan"><span><CalendarBlank size={22}/>下一轮计划</span><strong>{nextDate}</strong><p>系统将为所有网站<br/>自动创建下月外链任务。</p></div></div></aside></div></div>
      :page==='site'?<div className="page detail-page">{!site?<Empty title="网站不存在" body="该网站可能已被删除。" action={<Button onClick={()=>nav('overview')}>返回总览</Button>}/>:<><button className="back-link" onClick={()=>nav('overview')}><ArrowLeft size={18}/>返回总览</button><div className="page-heading"><div><div className="eyebrow">网站详情</div><h1>{site.domain}</h1><p>{site.name||'网站资料'} · {categoryText[site.category]} · {site.language}</p></div><div className="heading-actions"><Button onClick={()=>openEdit(site)} disabled={demo}><PencilSimple size={18}/>编辑网站</Button><Button onClick={()=>void act('site:pause',{id:site.id,paused:site.status!=='paused'},site.status==='paused'?'已恢复网站。':'已暂停网站。')} disabled={demo||pending}>{site.status==='paused'?<Play size={18}/>:<Pause size={18}/ >}{site.status==='paused'?'恢复':'暂停'}</Button></div></div>
          {site.error&&<div className="banner warning"><WarningCircle size={18}/>{site.error}<Button variant="text" onClick={()=>void act('site:analyze',{id:site.id},'已重新开始分析。')} disabled={demo||pending}>重新分析</Button></div>}
          <div className="detail-metrics"><Stat label="本月已生效" value={`${liveThisMonth(site.id)} / ${site.monthlyTarget}`} icon={CheckCircle}/><Stat label="等待审核" value={String(data?.tasks.filter(t=>t.siteId===site.id&&t.status==='review').length??0)} icon={Clock}/><Stat label="需要处理" value={String(data?.tasks.filter(t=>t.siteId===site.id&&['needs_input','failed','expired'].includes(t.status)).length??0)} icon={WarningCircle}/></div>
          <div className="detail-columns"><section className="panel"><div className="panel-head"><h2>任务时间线</h2><select aria-label="筛选任务" value={taskFilter} onChange={e=>setTaskFilter(e.target.value)}><option value="all">全部状态</option>{Object.entries(taskText).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></div>{data?.tasks.filter(t=>t.siteId===site.id&&(taskFilter==='all'||t.status===taskFilter)).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(t=><TaskCard key={t.id} task={t} channel={channelForTask(t)} selected={selectedTask===t.id} onSelect={()=>setSelectedTask(selectedTask===t.id?'':t.id)} onAction={async(command,payload)=>{await act(command,payload)}} onDraft={()=>openDraft(t)} onUrl={()=>openUrl(t)} demo={demo||pending}/>) ?? null}{!data?.tasks.some(t=>t.siteId===site.id&&(taskFilter==='all'||t.status===taskFilter))&&<Empty icon={Clock} title="暂无任务" body={site.status==='analyzing'?'网站分析后会自动建立计划。':'当前条件下没有任务。'}/>}</section><section className="panel site-info"><div className="panel-head"><h2>网站资料</h2><button className="icon-button" aria-label="编辑网站资料" onClick={()=>openEdit(site)} disabled={demo}><PencilSimple size={18}/></button></div><dl><dt>网站名称</dt><dd>{site.name||'待分析'}</dd><dt>网站简介</dt><dd>{site.description||'待分析'}</dd><dt>联系邮箱</dt><dd>{site.email}</dd><dt>每月目标</dt><dd>{site.monthlyTarget} 个有效来源</dd><dt>网站地址</dt><dd><button className="inline-link" onClick={()=>void act('external:open',{url:site.url})}>{site.url}<ArrowSquareOut size={14}/></button></dd></dl><div className="panel-footer"><Button variant="danger" onClick={()=>setModal('deleteSite')} disabled={demo}><Trash size={17}/>删除本地记录</Button></div></section></div></>}</div>
      :page==='channels'?<div className="page collection-page"><div className="page-heading"><div><div className="eyebrow">资源库</div><h1>渠道</h1><p>查看免费条件、投稿规则与自动化支持情况。</p></div></div><div className="toolbar"><div className="search"><MagnifyingGlass size={19}/><input value={channelSearch} onChange={e=>setChannelSearch(e.target.value)} placeholder="搜索渠道名称或域名" aria-label="搜索渠道"/></div><div className="select-wrap"><Funnel size={18}/><select value={channelFilter} onChange={e=>setChannelFilter(e.target.value)} aria-label="筛选渠道"><option value="all">全部渠道</option><option value="yes">免费</option><option value="conditional">有条件免费</option><option value="manual">人工操作</option><option value="browser">浏览器执行</option></select></div></div><div className="channel-grid">{data?.channels.filter(c=>`${c.name} ${c.domain}`.toLowerCase().includes(channelSearch.toLowerCase())&&(channelFilter==='all'||c.free===channelFilter||c.automation===channelFilter)).map(c=><article className="panel channel-card" key={c.id}><div className="channel-top"><div className="channel-avatar"><LinkSimple size={22}/></div><span className={`badge ${c.enabled?'green':'muted'}`}>{c.enabled?'可用':'已关闭'}</span></div><h2>{c.name}</h2><p className="muted">{c.domain}</p><div className="channel-tags"><span>{c.free==='yes'?'免费':c.free==='conditional'?'有条件免费':'费用待确认'}</span><span>{c.automation==='browser'&&c.enabled?'浏览器流程':'人工处理'}</span><span>{c.kind==='directory'?'目录':c.kind==='profile'?'资料页':c.kind==='article'?'文章':'社区'}</span></div><p>{c.qualityReason||c.notes||'请查看渠道规则确认是否适合当前网站。'}</p><dl><dt>免费条件</dt><dd>{c.freeNote||'以渠道规则为准'}</dd><dt>执行方式</dt><dd>{c.automation==='browser'&&c.enabled?'已配置浏览器流程':'需要人工查看与提交'}</dd><dt>适合类别</dt><dd>{c.categories.map(x=>categoryText[x]).join('、')||'未标明'}</dd><dt>语言</dt><dd>{c.languages.join('、')||'未标明'}</dd><dt>账号 / 邮箱</dt><dd>{c.accountRequired?'需要账号':'无需账号'} · {c.emailRequired?'需邮箱':'无需邮箱'}</dd><dt>最近核查</dt><dd>{fmt(c.checkedAt)}</dd></dl><div className="card-actions"><Button variant="text" onClick={()=>void act('external:open',{url:c.rulesUrl||c.url})} disabled={demo}>查看规则 <ArrowSquareOut size={15}/></Button><Button variant="text" onClick={()=>void act('external:open',{url:c.submitUrl||c.url})} disabled={demo}>打开投稿页 <ArrowSquareOut size={15}/></Button></div></article>)}{!data?.channels.length&&<div className="grid-empty"><Empty icon={FileText} title="暂无渠道" body="渠道库尚未建立。建立并核查渠道后会在此显示。"/></div>}{!!data?.channels.length&&!data.channels.some(c=>`${c.name} ${c.domain}`.toLowerCase().includes(channelSearch.toLowerCase())&&(channelFilter==='all'||c.free===channelFilter||c.automation===channelFilter))&&<div className="grid-empty"><Empty title="没有匹配的渠道" body="调整搜索或筛选条件。"/></div>}</div></div>
      :page==='accounts'?<div className="page collection-page"><div className="page-heading"><div><div className="eyebrow">本地保险箱</div><h1>账号</h1><p>按渠道管理账号。密码默认隐藏，查看时需要本机解锁。</p></div><Button variant="primary" onClick={()=>openAccount()} disabled={demo||!data?.channels.length}><Plus size={18}/>添加账号</Button></div><div className="panel account-panel">{data?.accounts.length?data.accounts.map(a=><div className="account-row" key={a.id}><div className="account-icon"><UserCircle size={24}/></div><div className="account-main"><strong>{data.channels.find(c=>c.id===a.channelId)?.name??'未知渠道'}</strong><small>{a.email} {a.username&&`· ${a.username}`}</small></div><span className={`badge ${a.status==='needs_verification'?'amber':'green'}`}>{a.status==='needs_verification'?'待验证':a.status==='registered'?'已注册':'已保存'}</span><div className="account-actions"><Button variant="text" onClick={async()=>{const r=await act<{password:string}>('account:reveal',{id:a.id});if(r)setRevealed(v=>({...v,[a.id]:r.password}))}} disabled={demo||!a.hasPassword} title="查看密码"><Eye size={18}/>{revealed[a.id]?'已显示':'查看密码'}</Button>{revealed[a.id]&&<><code className="revealed">{revealed[a.id]}</code><button className="icon-button" aria-label="复制密码" onClick={()=>{void navigator.clipboard.writeText(revealed[a.id]);setNotice('密码已复制。')}}><Copy size={17}/></button></>}<button className="icon-button" aria-label="编辑账号" onClick={()=>openAccount(a)} disabled={demo}><PencilSimple size={18}/></button><button className="icon-button danger-icon" aria-label="删除账号" onClick={()=>{setSelectedAccount(a.id);setModal('deleteAccount')}} disabled={demo}><Trash size={18}/></button></div></div>):<Empty icon={ShieldCheck} title="暂无保存的账号" body="执行渠道任务时可自动创建账号，也可以手动添加已持有的账号。" action={<Button variant="primary" onClick={()=>openAccount()} disabled={demo||!data?.channels.length}><Plus size={18}/>添加账号</Button>}/>}</div></div>
      :<div className="page settings-page"><div className="page-heading"><div><div className="eyebrow">偏好设置</div><h1>设置</h1><p>管理 AI、邮箱、自动执行与本地数据。</p></div></div>{settings&&<><form className="settings-layout" onChangeCapture={()=>{settingsDirty.current=true}} onSubmit={async e=>{e.preventDefault();const result=await act<Snapshot>('settings:save',{...settings,apiKey:apiKey||undefined,mailPassword:mailPassword||undefined},'设置已保存。');if(result){settingsDirty.current=false;setSettings(result.settings);setApiKey('');setMailPassword('')}}}><div className="settings-main"><section className="panel settings-card"><div className="settings-heading"><div className="setting-icon"><LinkSimple size={22}/></div><div><h2>AI 服务</h2><p>用于分析网站与准备适合渠道的内容。</p></div></div><div className="segmented"><button type="button" className={settings.provider==='codex'?'selected':''} onClick={()=>{settingsDirty.current=true;setSettings({...settings,provider:'codex'})}}>Codex CLI</button><button type="button" className={settings.provider==='api'?'selected':''} onClick={()=>{settingsDirty.current=true;setSettings({...settings,provider:'api'})}}>自有 API</button></div>{settings.provider==='codex'?<div className="form-grid"><Field label="Codex 路径"><input value={settings.codexPath} onChange={e=>setSettings({...settings,codexPath:e.target.value})} placeholder="codex"/></Field><Field label="模型"><input value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})} placeholder="使用默认模型"/></Field></div>:<div className="form-grid"><Field label="API 地址"><input type="url" required value={settings.apiBase} onChange={e=>setSettings({...settings,apiBase:e.target.value})} placeholder="https://api.example.com"/></Field><Field label="模型"><input required value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})} placeholder="模型名称"/></Field><Field label="API 密钥" hint={settings.hasApiKey?'已保存密钥；留空保持原值':'密钥存储于本机保险箱'}><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="new-password" placeholder={settings.hasApiKey?'已保存':'输入密钥'}/></Field></div>}<div className="inline-actions"><Button onClick={async()=>{const r=await act<{ok:boolean;message:string}>('settings:test-ai');if(r)(r.ok?setNotice:setError)(r.message)}} disabled={demo||pending}>测试连接</Button><span className={`status-text ${data?.runtime.aiReady?'ok':''}`}>{data?.runtime.aiReady?'连接可用':'尚未连接'}</span></div></section>
              <section className="panel settings-card"><div className="settings-heading"><div className="setting-icon"><ShieldCheck size={22}/></div><div><h2>验证邮箱</h2><p>仅读取与当前任务匹配的验证邮件。</p></div></div><div className="form-grid"><Field label="IMAP 主机"><input value={settings.mail.host} onChange={e=>setSettings({...settings,mail:{...settings.mail,host:e.target.value}})} placeholder="imap.example.com"/></Field><Field label="端口"><input type="number" min="1" max="65535" value={settings.mail.port} onChange={e=>setSettings({...settings,mail:{...settings.mail,port:Number(e.target.value)}})}/></Field><Field label="邮箱账号"><input type="email" value={settings.mail.user} onChange={e=>setSettings({...settings,mail:{...settings.mail,user:e.target.value}})} placeholder="hello@example.com"/></Field><Field label="邮箱密码或应用密码" hint={settings.mail.hasPassword?'已保存密码；留空保持原值':'仅保存在本机保险箱'}><input type="password" autoComplete="new-password" value={mailPassword} onChange={e=>setMailPassword(e.target.value)} placeholder={settings.mail.hasPassword?'已保存':'输入密码'}/></Field></div><label className="toggle-row"><input type="checkbox" checked={settings.mail.secure} onChange={e=>setSettings({...settings,mail:{...settings.mail,secure:e.target.checked}})}/>启用 TLS 加密连接</label><div className="inline-actions"><Button onClick={async()=>{const r=await act<{ok:boolean;message:string}>('settings:test-mail');if(r)(r.ok?setNotice:setError)(r.message)}} disabled={demo||pending}>测试邮箱</Button><span className={`status-text ${data?.runtime.mailReady?'ok':''}`}>{data?.runtime.mailReady?'连接可用':'尚未连接'}</span></div></section>
              <section className="panel settings-card"><div className="settings-heading"><div className="setting-icon"><CalendarBlank size={22}/></div><div><h2>运行与限制</h2><p>控制自动执行的时间、通知和重试范围。</p></div></div><div className="toggle-list"><label className="toggle-row"><input type="checkbox" checked={settings.autoRun} onChange={e=>setSettings({...settings,autoRun:e.target.checked})}/>自动执行计划</label><label className="toggle-row"><input type="checkbox" checked={settings.launchAtLogin} onChange={e=>setSettings({...settings,launchAtLogin:e.target.checked})}/>登录电脑时启动</label><label className="toggle-row"><input type="checkbox" checked={settings.notify} onChange={e=>setSettings({...settings,notify:e.target.checked})}/>需要处理时发送通知</label></div><div className="form-grid"><Field label="时区"><input value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})} placeholder="Asia/Singapore"/></Field><Field label="最多重试次数"><input type="number" min="1" max="5" value={settings.maxAttempts} onChange={e=>setSettings({...settings,maxAttempts:Number(e.target.value)})}/></Field><Field label="单任务最多步骤"><input type="number" min="3" max="40" value={settings.maxSteps} onChange={e=>setSettings({...settings,maxSteps:Number(e.target.value)})}/></Field><Field label="每天 AI 调用上限"><input type="number" min="1" max="200" value={settings.dailyAiLimit} onChange={e=>setSettings({...settings,dailyAiLimit:Number(e.target.value)})}/></Field></div></section><div className="settings-save"><Button variant="primary" type="submit" disabled={demo||pending}>保存设置</Button></div></div><aside className="settings-side"><section className="panel settings-card"><h2>计划控制</h2><p>执行会在后台继续。暂停后不会领取新任务。</p><div className="stack-actions"><Button onClick={()=>void act('plan:run',{},'计划已启动。')} disabled={demo||pending}><Play size={17}/>立即运行</Button><Button onClick={()=>void act('plan:pause',{},'计划已暂停。')} disabled={demo||pending}><Pause size={17}/>暂停运行</Button></div></section><section className="panel settings-card"><h2>本地数据</h2><p>备份使用口令加密。恢复前请确认已保留现有数据的备份。</p><div className="stack-actions"><Button onClick={()=>setModal('backupExport')} disabled={demo}><DownloadSimple size={17}/>导出加密备份</Button><Button onClick={()=>setModal('backupImport')} disabled={demo}><UploadSimple size={17}/>导入加密备份</Button><Button onClick={()=>void act('data:export',{},'CSV 已导出。')} disabled={demo||pending}><DownloadSimple size={17}/>导出 CSV</Button></div></section><section className="panel settings-card app-info"><h2>关于</h2><p>外链助手 {data?.runtime.version||''}</p><p>AI 调用：今日 {data?.runtime.aiCallsToday??0} 次</p></section></aside></form></>}</div>}
    </main>

    {modal==='add'&&<Dialog title="添加网站" onClose={close}><form onSubmit={saveAdd} className="dialog-form"><p className="dialog-intro">输入网站域名和联系邮箱，系统将分析公开页面并建立计划。</p><Field label="网站域名"><input required autoFocus value={domain} onChange={e=>setDomain(e.target.value)} placeholder="example.com" autoCapitalize="off"/></Field><Field label="联系邮箱"><input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="hello@example.com"/></Field><Field label="每月目标" hint="默认每月 2 个合格来源，可随时调整。"><input required type="number" min="1" max="20" value={target} onChange={e=>setTarget(Number(e.target.value))}/></Field><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="primary" type="submit" disabled={pending||demo}>分析并开始</Button></div></form></Dialog>}
    {modal==='editSite'&&site&&<Dialog title="编辑网站" onClose={close}><form onSubmit={saveSite} className="dialog-form"><Field label="网站名称"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="网站简介"><textarea rows={4} value={description} onChange={e=>setDescription(e.target.value)}/></Field><div className="form-grid"><Field label="类别"><select value={category} onChange={e=>setCategory(e.target.value as Category)}>{Object.entries(categoryText).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><Field label="语言"><input value={language} onChange={e=>setLanguage(e.target.value)}/></Field></div><div className="form-grid"><Field label="联系邮箱"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="每月目标"><input type="number" min="1" max="20" required value={target} onChange={e=>setTarget(Number(e.target.value))}/></Field></div><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="primary" type="submit" disabled={pending}>保存</Button></div></form></Dialog>}
    {modal==='account'&&<Dialog title={account?'编辑账号':'添加账号'} onClose={close}><form onSubmit={saveAccount} className="dialog-form"><Field label="渠道"><select value={accountChannel} onChange={e=>setAccountChannel(e.target.value)} required>{!accountChannel&&<option value="">请选择渠道</option>}{data?.channels.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></Field><Field label="邮箱"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)}/></Field><Field label="用户名"><input required value={username} onChange={e=>setUsername(e.target.value)}/></Field><Field label="密码" hint={account?.hasPassword?'留空保持原密码':'密码保存在本机保险箱'}><input type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/></Field><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="primary" type="submit" disabled={pending}>保存账号</Button></div></form></Dialog>}
    {modal==='draft'&&chosenTask&&<Dialog title="编辑投稿草稿" onClose={close} width="wide"><form onSubmit={e=>void submitSimple(e,'task:update-draft',{id:chosenTask.id,title:draftTitle,description:draftDescription,body:draftBody},'草稿已保存。')} className="dialog-form"><Field label="标题"><input value={draftTitle} onChange={e=>setDraftTitle(e.target.value)}/></Field><Field label="摘要"><textarea rows={3} value={draftDescription} onChange={e=>setDraftDescription(e.target.value)}/></Field><Field label="正文"><textarea rows={10} value={draftBody} onChange={e=>setDraftBody(e.target.value)}/></Field><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="primary" type="submit" disabled={pending}>保存草稿</Button></div></form></Dialog>}
    {modal==='url'&&chosenTask&&<Dialog title="填写公开页面地址" onClose={close}><form onSubmit={e=>void submitSimple(e,'task:set-url',{id:chosenTask.id,url:url.trim()},'地址已保存。')} className="dialog-form"><p className="dialog-intro">填写渠道公开页面的完整地址。保存后可点击“核验”检查外链。</p><Field label="公开页面 URL"><input type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://example.com/page"/></Field><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="primary" type="submit" disabled={pending}>保存地址</Button></div></form></Dialog>}
    {(modal==='backupExport'||modal==='backupImport')&&<Dialog title={modal==='backupExport'?'导出加密备份':'导入加密备份'} onClose={close}><form onSubmit={async e=>{e.preventDefault();if(passphrase.length<12||passphrase.length>256){setError('备份口令需要 12–256 个字符。');return}const command=modal==='backupExport'?'backup:export':'backup:import';const r=await act<{ok:boolean;message:string}>(command,{passphrase});if(r?.ok){setNotice(r.message);close()}else if(r)setError(r.message)}} className="dialog-form"><p className="dialog-intro">{modal==='backupImport'?'请选择已有备份文件并输入其口令。导入前建议先导出当前数据。':'备份包含网站、任务和账号关联。请妥善保存口令。'}</p><Field label="备份口令"><input type="password" required minLength={12} maxLength={256} autoComplete="new-password" value={passphrase} onChange={e=>setPassphrase(e.target.value)}/></Field><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="primary" type="submit" disabled={pending}>{modal==='backupImport'?'选择文件并导入':'选择位置并导出'}</Button></div></form></Dialog>}
    {modal==='deleteSite'&&site&&<Dialog title="删除网站本地记录" onClose={close}><div className="dialog-form"><p className="dialog-intro">将删除 {site.domain} 的本地计划、任务和记录。已发布在第三方网站的外链不会被删除。</p><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="danger" onClick={async()=>{const r=await act('site:delete',{id:site.id},'网站已删除。');if(r){close();nav('overview')}}} disabled={pending}>确认删除</Button></div></div></Dialog>}
    {modal==='deleteAccount'&&account&&<Dialog title="删除保存的账号" onClose={close}><div className="dialog-form"><p className="dialog-intro">将从本机删除 {account.email} 的账号记录和保存的密码。</p><div className="dialog-actions"><Button onClick={close}>取消</Button><Button variant="danger" onClick={async()=>{const r=await act('account:delete',{id:account.id},'账号已删除。');if(r){setRevealed(v=>{const next={...v};delete next[account.id];return next});close()}}} disabled={pending}>确认删除</Button></div></div></Dialog>}
  </div>;
}

function NavButton({icon:Icon,active,onClick,children}:{icon:IconType;active:boolean;onClick:()=>void;children:ReactNode}){return <button className={`nav-item ${active?'active':''}`} onClick={onClick} aria-current={active?'page':undefined}><Icon size={23} weight={active?'fill':'regular'}/><span>{children}</span></button>}
function Stat({label,value,icon:Icon}:{label:string;value:string;icon:IconType}){return <div className="stat panel"><div><Icon size={20}/><span>{label}</span></div><strong>{value}</strong></div>}
function TaskCard({task,channel,selected,onSelect,onAction,onDraft,onUrl,demo}:{task:Task;channel?:Channel;selected:boolean;onSelect:()=>void;onAction:(command:string,payload:unknown)=>Promise<void>;onDraft:()=>void;onUrl:()=>void;demo:boolean}){
  return <article className={`task-card ${selected?'selected':''}`}><button className="task-summary" onClick={onSelect} aria-expanded={selected}><span className={`timeline-dot ${taskTone[task.status]}`}/><span className="task-main"><strong>{channel?.name??task.sourceDomain}</strong><small>{task.sourceDomain} · 更新于 {fmt(task.updatedAt)}</small></span><span className={`badge ${taskTone[task.status]}`}>{taskText[task.status]}</span><CaretDown size={16} className={selected?'rotated':''}/></button>{selected&&<div className="task-detail"><p>{task.message||'暂无说明。'}</p>{task.reason&&<p className="muted">原因：{task.reason}</p>}<dl><dt>创建时间</dt><dd>{fmt(task.createdAt)}</dd><dt>计划时间</dt><dd>{fmt(task.scheduledAt)}</dd><dt>尝试次数</dt><dd>{task.attempts}</dd>{task.publicUrl&&<><dt>公开地址</dt><dd>{task.publicUrl}</dd></>}{task.linkRel&&<><dt>链接属性</dt><dd>{task.linkRel}</dd></>}{task.verifiedAt&&<><dt>核验时间</dt><dd>{fmt(task.verifiedAt)}</dd></>}</dl><div className="task-actions"><Button onClick={()=>void onAction('task:open',{id:task.id})} disabled={demo}><ArrowSquareOut size={16}/>打开渠道</Button><Button onClick={onDraft} disabled={demo}><PencilSimple size={16}/>编辑草稿</Button><Button onClick={onUrl} disabled={demo}><LinkSimple size={16}/>填写地址</Button><Button onClick={()=>void onAction('task:verify',{id:task.id})} disabled={demo}><CheckCircle size={16}/>核验</Button>{['failed','needs_input','expired','skipped'].includes(task.status)&&<Button onClick={()=>void onAction('task:retry',{id:task.id})} disabled={demo}><ArrowClockwise size={16}/>重试</Button>}{!task.draft&&<Button onClick={()=>void onAction('task:generate',{id:task.id})} disabled={demo}>生成草稿</Button>}{task.status!=='live'&&task.status!=='skipped'&&<Button onClick={()=>void onAction('task:skip',{id:task.id})} disabled={demo}>跳过</Button>}</div></div>}</article>;
}
