import {useState} from 'react';
import {ArrowSquareOut,CalendarBlank,CheckCircle,Database,DownloadSimple,EnvelopeSimple,Gear,Info,LinkSimple,LockKey,Pause,Play,ShieldCheck,UploadSimple} from '@phosphor-icons/react';
import type {Settings,Snapshot} from '../../shared/types';
import {DEFAULT_MAIL_PRESET_ID,MAIL_PRESETS,getMailPreset,inferMailPreset,type MailPresetId} from '../../shared/mail-presets';
import {Button,Field} from '../components';

type Section='ai'|'mail'|'run'|'data';
type Props={settings:Settings|null;setSettings:(next:Settings)=>void;snapshot:Snapshot|null;apiKey:string;setApiKey:(value:string)=>void;mailPassword:string;setMailPassword:(value:string)=>void;disabled:boolean;onSave:()=>Promise<boolean>;onAction:<T>(command:string,payload?:unknown,success?:string)=>Promise<T|undefined>;onResult:(ok:boolean,message:string)=>void;onBackup:(kind:'export'|'import')=>void};
export function SettingsPage({settings,setSettings,snapshot,apiKey,setApiKey,mailPassword,setMailPassword,disabled,onSave,onAction,onResult,onBackup}:Props){
  const [section,setSection]=useState<Section>('ai'),[customMail,setCustomMail]=useState(false),[testing,setTesting]=useState(false);
  if(!settings)return <div className="page"><p className="muted">正在读取设置…</p></div>;
  const dirty=!!apiKey||!!mailPassword||JSON.stringify(settings)!==JSON.stringify(snapshot?.settings);
  const preset=customMail?undefined:inferMailPreset({host:settings.mail.host});
  const selectedProvider=customMail?'custom':preset?.id??(!settings.mail.host?DEFAULT_MAIL_PRESET_ID:'custom');
  const activePreset=selectedProvider==='custom'?undefined:getMailPreset(selectedProvider as MailPresetId);
  const detected=inferMailPreset({email:settings.mail.user});
  const mailDirty=!!mailPassword||JSON.stringify(settings.mail)!==JSON.stringify(snapshot?.settings.mail);
  const aiDirty=!!apiKey||['provider','codexPath','model','apiBase'].some(key=>settings[key as keyof Settings]!==snapshot?.settings[key as keyof Settings]);
  const updateMail=(patch:Partial<Settings['mail']>)=>setSettings({...settings,mail:{...settings.mail,...patch}});
  const chooseProvider=(id:string)=>{
    setCustomMail(id==='custom');setMailPassword('');
    if(id!=='custom'){const next=getMailPreset(id as MailPresetId);updateMail({host:next.host,port:next.port,secure:true,hasPassword:false})}
  };
  const test=async(kind:'ai'|'mail')=>{
    if(kind==='mail'&&(!settings.mail.user||!settings.mail.host||!(mailPassword||settings.mail.hasPassword))){onResult(false,'请填写邮箱账号及授权码 / 应用专用密码。');return}
    setTesting(true);try{if(!await onSave())return;const r=await onAction<{ok:boolean;message:string}>(kind==='ai'?'settings:test-ai':'settings:test-mail');if(r)onResult(r.ok,r.message)}finally{setTesting(false)}
  };
  const blocked=disabled||testing;
  const guides:Record<Section,{title:string;text:string;steps:string[]}>={
    ai:{title:'连接一次，后续自动执行',text:'助手会识别网站主题、准备资料，并操作已接入的渠道。',steps:['先在本机安装并登录 Codex CLI','也可以连接自己的 API 服务','调用额度与费用由所用服务决定']},
    mail:{title:'让验证邮件自动接续',text:'只处理与当前网站和渠道匹配的验证邮件。',steps:['选择邮箱服务，服务器自动填好','输入收信邮箱和应用专用密码','保存并测试，成功后自动接续任务']},
    run:{title:'少量、稳定地推进',text:'每个网站默认每月 2 个合格来源，目标可在网站详情调整。',steps:['任务按月排队，不重复计算同一来源','仅在客户端运行且电脑联网时执行','验证码或平台限制会在总览提醒']},
    data:{title:'资料留在这台电脑',text:'密码、密钥和邮箱授权码保存在本机加密保险箱。',steps:['备份包含账号与连接凭证','请妥善保管备份口令','CSV 仅导出外链结果，不含密码']},
  };
  return <div className="page settings-page"><div className="page-heading"><div><div className="eyebrow">PREFERENCES / 工作偏好</div><h1>设置好，放心交给助手。</h1><p>常用配置一步完成，更多选项按需展开。</p></div><span className="heading-seal"><LockKey size={17}/>仅保存在本机</span></div>
    <div className="settings-tabs" role="tablist" aria-label="设置分类">{[{id:'ai',label:'AI 服务',icon:LinkSimple},{id:'mail',label:'验证邮箱',icon:EnvelopeSimple},{id:'run',label:'运行偏好',icon:CalendarBlank},{id:'data',label:'数据与备份',icon:Database}].map(({id,label,icon:Icon})=><button key={id} id={`setting-tab-${id}`} role="tab" aria-selected={section===id} tabIndex={section===id?0:-1} onKeyDown={e=>{const ids:Section[]=['ai','mail','run','data'];let index=ids.indexOf(section);if(e.key==='ArrowRight')index=(index+1)%ids.length;else if(e.key==='ArrowLeft')index=(index+ids.length-1)%ids.length;else if(e.key==='Home')index=0;else if(e.key==='End')index=ids.length-1;else return;e.preventDefault();setSection(ids[index]);document.getElementById(`setting-tab-${ids[index]}`)?.focus()}} aria-controls={`setting-panel-${id}`} className={section===id?'active':''} onClick={()=>setSection(id as Section)}><Icon size={18}/>{label}</button>)}</div>
    <form className="settings-layout" onSubmit={async e=>{e.preventDefault();if(await onSave())onResult(true,'设置已保存。')}}><div className="settings-main" role="tabpanel" id={`setting-panel-${section}`} aria-labelledby={`setting-tab-${section}`}>
      {section==='ai'&&<section className="panel settings-card"><div className="settings-heading"><div className="setting-icon"><LinkSimple size={23}/></div><div><h2>选择你的 AI 服务</h2><p>已有 Codex 登录可直接使用，无需再次填写密钥。</p></div><span className={`badge ${snapshot?.runtime.aiReady&&!aiDirty?'green':'muted'}`}>{aiDirty?'等待保存':snapshot?.runtime.aiReady?'已连接':'未连接'}</span></div><div className="provider-options"><button type="button" className={settings.provider==='codex'?'selected':''} onClick={()=>setSettings({...settings,provider:'codex'})}><span className="provider-radio"/><span><strong>Codex CLI</strong><small>使用本机已登录的账号</small></span>{settings.provider==='codex'&&<CheckCircle size={19} weight="fill"/>}</button><button type="button" className={settings.provider==='api'?'selected':''} onClick={()=>setSettings({...settings,provider:'api'})}><span className="provider-radio"/><span><strong>自有 API</strong><small>连接兼容的模型服务</small></span>{settings.provider==='api'&&<CheckCircle size={19} weight="fill"/>}</button></div>
        {settings.provider==='codex'?<><div className="connection-guide"><Info size={18}/><p>助手通过本机 Codex 完成网站分析和浏览器任务。先登录 Codex，再点击下方测试连接。</p></div><details className="advanced-settings"><summary>高级连接选项</summary><div className="form-grid"><Field label="Codex 路径"><input value={settings.codexPath} onChange={e=>setSettings({...settings,codexPath:e.target.value})} placeholder="codex"/></Field><Field label="模型" hint="留空使用默认模型"><input value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})} placeholder="使用默认模型"/></Field></div></details></>:<div className="form-grid"><Field label="API 地址"><input type="url" required value={settings.apiBase} onChange={e=>setSettings({...settings,apiBase:e.target.value})} placeholder="https://api.example.com/v1"/></Field><Field label="模型"><input required value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})} placeholder="模型名称"/></Field><Field label="API 密钥" hint={settings.hasApiKey?'已保存密钥；留空保持原值':'只保存在本机保险箱'}><input type="password" value={apiKey} onChange={e=>setApiKey(e.target.value)} autoComplete="new-password" placeholder={settings.hasApiKey?'已加密保存':'输入 API Key'}/></Field></div>}
        <div className="connection-footer"><Button variant="primary" onClick={()=>void test('ai')} disabled={blocked}>{testing?'正在测试…':'保存并测试连接'}</Button><span>测试使用当前填写的配置</span></div>
      </section>}
      {section==='mail'&&<section className="panel settings-card mailbox-card"><div className="settings-heading"><div className="setting-icon"><EnvelopeSimple size={23}/></div><div><h2>验证邮箱</h2><p>选好邮箱服务，其余连接参数由助手填写。</p></div><span className={`badge ${snapshot?.runtime.mailReady&&!mailDirty?'green':'muted'}`}>{mailDirty?'等待保存':snapshot?.runtime.mailReady?'已连接':'未连接'}</span></div>
        <Field label="邮箱服务"><select aria-label="邮箱服务" value={selectedProvider} onChange={e=>chooseProvider(e.target.value)}>{MAIL_PRESETS.map(p=><option key={p.id} value={p.id}>{p.name}{p.id==='gmail'?' · 默认推荐':p.support==='oauth-required'?' · 暂未支持 OAuth':''}</option>)}<option value="custom">其他邮箱 / 自定义服务器</option></select></Field>
        {activePreset&&<div className={`mail-preset-note ${activePreset.support==='oauth-required'?'unsupported':''}`}><ShieldCheck size={19}/><p>{activePreset.hint}</p><Button variant="text" disabled={disabled} onClick={()=>void onAction('external:open',{url:activePreset.helpUrl})}>设置指引<ArrowSquareOut size={14}/></Button></div>}
        <div className="form-grid mail-credentials"><Field label="收信邮箱" hint="需要能收到发送给网站联系邮箱的验证邮件"><input type="email" autoComplete="email" value={settings.mail.user} onChange={e=>{setMailPassword('');updateMail({user:e.target.value,hasPassword:e.target.value.trim().toLowerCase()===snapshot?.settings.mail.user.trim().toLowerCase()&&settings.mail.host===snapshot.settings.mail.host?!!snapshot.settings.mail.hasPassword:false})}} placeholder={selectedProvider==='gmail'?'yourname@gmail.com':'你的邮箱地址'}/></Field><Field label={selectedProvider==='custom'?'邮箱授权码 / 应用专用密码':'授权码 / 应用专用密码'} hint={settings.mail.hasPassword?'已加密保存；留空保持原值':'请使用邮箱提供的客户端专用密码'}><input type="password" autoComplete="new-password" value={mailPassword} onChange={e=>setMailPassword(e.target.value)} placeholder={settings.mail.hasPassword?'已加密保存':'输入授权码或应用专用密码'} disabled={activePreset?.support==='oauth-required'}/></Field></div>
        {detected&&detected.id!==selectedProvider&&selectedProvider!=='custom'&&<div className="detected-provider">邮箱地址属于 {detected.name}<Button variant="text" onClick={()=>chooseProvider(detected.id)}>使用对应配置</Button></div>}
        <details className="advanced-settings" open={selectedProvider==='custom'} key={selectedProvider}><summary>服务器设置 <span>{settings.mail.host||'待填写'} · {settings.mail.port} · TLS</span></summary><div className="form-grid"><Field label="IMAP 主机"><input value={settings.mail.host} onChange={e=>{setCustomMail(true);setMailPassword('');updateMail({host:e.target.value,hasPassword:false})}} placeholder="imap.example.com" autoCapitalize="off" spellCheck={false}/></Field><Field label="端口"><input type="number" min="1" max="65535" value={settings.mail.port} onChange={e=>{setCustomMail(true);setMailPassword('');updateMail({port:Number(e.target.value),hasPassword:false})}}/></Field></div><div className="tls-note"><LockKey size={14}/> 始终使用 TLS 加密连接</div></details>
        <div className="connection-footer"><Button variant="primary" disabled={blocked||activePreset?.support==='oauth-required'} onClick={()=>void test('mail')}>{testing?'正在连接…':'保存并测试邮箱'}</Button><span>{snapshot?.runtime.mailReady&&!mailDirty?'验证邮件可自动接续':'连接成功后，验证任务会自动继续'}</span></div>
      </section>}
      {section==='run'&&<section className="panel settings-card"><div className="settings-heading"><div className="setting-icon"><CalendarBlank size={23}/></div><div><h2>运行偏好</h2><p>系统按计划推进，需要你时再提醒。</p></div></div><div className="preference-rows">{[{key:'autoRun',label:'自动执行计划',hint:'按月度目标排队，并接续未完成任务'},{key:'launchAtLogin',label:'登录电脑时启动',hint:'客户端运行且联网时，才能继续任务'},{key:'notify',label:'需要处理时通知我',hint:'验证码、账号异常等事项集中提醒'}].map(({key,label,hint})=><label className="preference-row" key={key}><span><strong>{label}</strong><small>{hint}</small></span><input type="checkbox" role="switch" checked={settings[key as 'autoRun'|'launchAtLogin'|'notify']} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/></label>)}</div><details className="advanced-settings"><summary>执行限额与时区</summary><div className="form-grid"><Field label="时区"><input value={settings.timezone} onChange={e=>setSettings({...settings,timezone:e.target.value})}/></Field><Field label="每天 AI 调用上限"><input type="number" min="1" max="200" value={settings.dailyAiLimit} onChange={e=>setSettings({...settings,dailyAiLimit:Number(e.target.value)})}/></Field><Field label="任务重试上限"><input type="number" min="1" max="5" value={settings.maxAttempts} onChange={e=>setSettings({...settings,maxAttempts:Number(e.target.value)})}/></Field><Field label="单任务步骤上限"><input type="number" min="3" max="40" value={settings.maxSteps} onChange={e=>setSettings({...settings,maxSteps:Number(e.target.value)})}/></Field></div></details></section>}
      {section==='data'&&<section className="panel settings-card"><div className="settings-heading"><div className="setting-icon"><Database size={23}/></div><div><h2>本地数据与备份</h2><p>账户与连接凭证随加密备份保存，换电脑也能继续。</p></div></div><div className="data-actions"><div><span><strong>导出加密备份</strong><small>网站、任务、账号及连接配置</small></span><Button onClick={()=>onBackup('export')} disabled={blocked}><DownloadSimple size={17}/>导出备份</Button></div><div><span><strong>从备份恢复</strong><small>需要原备份口令，恢复前暂停执行</small></span><Button onClick={()=>onBackup('import')} disabled={blocked}><UploadSimple size={17}/>恢复备份</Button></div><div><span><strong>导出外链记录</strong><small>CSV 表格，不包含账号密码</small></span><Button onClick={()=>void onAction('data:export',{},'CSV 已导出。')} disabled={blocked}><DownloadSimple size={17}/>导出 CSV</Button></div></div></section>}
      {section!=='data'&&<div className="settings-save"><span>{dirty?'有未保存的更改':'配置已与本机同步'}</span><Button variant="primary" type="submit" disabled={blocked||!dirty}>保存设置</Button></div>}
    </div><aside className="settings-side"><section className="setup-guide"><span className="mini-eyebrow">一点帮助，少走弯路</span><h3>{guides[section].title}</h3><p>{guides[section].text}</p><ol>{guides[section].steps.map(step=><li key={step}>{step}</li>)}</ol></section><section className="panel settings-card compact-control"><div className="panel-head"><h2>计划状态</h2><span className={`dot ${snapshot?.settings.autoRun?'green':'gray'}`}/></div><p>{snapshot?.runtime.busy?'正在执行渠道任务':snapshot?.settings.autoRun?'已开启自动计划，等待下一项任务。':'计划已暂停，不会领取新任务。'}</p><Button onClick={async()=>{const r=await onAction<Snapshot>(snapshot?.settings.autoRun?'plan:pause':'plan:run',{},snapshot?.settings.autoRun?'计划已暂停。':'计划已启动。');if(r)setSettings({...settings,autoRun:r.settings.autoRun})}} disabled={blocked}>{snapshot?.settings.autoRun?<Pause size={16}/>:<Play size={16}/ >}{snapshot?.settings.autoRun?'暂停计划':'恢复计划'}</Button></section><div className="settings-version"><Gear size={14}/>LINKFLOW {snapshot?.runtime.version}<span>今日 AI 调用 {snapshot?.runtime.aiCallsToday??0} 次</span></div></aside></form>
  </div>;
}
