import {useState} from 'react';
import type {Channel,Qualification,Site,Snapshot,Task} from '../../shared/types';
import {eligibilityFor,qualificationLabels} from '../../integrations/eligibility';
import {matchChannels} from '../../integrations/catalog';
import {Button,Field} from '../components';

export function SiteTools({site,data,disabled,onAction}:{site:Site;data:Snapshot;disabled:boolean;onAction:(cmd:string,payload?:unknown,success?:string)=>Promise<unknown>}){
 const [key,setKey]=useState(''),[editing,setEditing]=useState(false),[proof,setProof]=useState(site.qualifications??{});
 const matches=matchChannels(site,data.channels),tasks=data.tasks.filter(t=>t.siteId===site.id);
 const gscUrl='https://search.google.com/search-console/links?resource_id='+encodeURIComponent('sc-domain:'+site.domain);
 return <div className="site-tools"><section className="panel"><div className="panel-head"><div><h2>这个网站适合哪些渠道</h2><p className="muted">按主题、语言与真实资格筛选，不为凑数重复发布。</p></div><span className="badge blue">{matches.length} 个符合基础条件</span></div>
  {matches.length?<div className="fit-list">{matches.map(({channel:c,reason})=><div className="fit-row" key={c.id}><div><strong>{c.name}</strong><small>{c.kind==='article'?'原创文章':'资料 / 项目'} · {c.automation==='api'?'官方 API':c.automation==='browser'?'浏览器操作':'人工提交'}</small><p>{reason}</p></div><Button disabled={disabled||tasks.some(t=>t.channelId===c.id)} onClick={()=>void onAction('site:queue-channel',{id:site.id,channelId:c.id},'渠道已加入任务。')}>{tasks.some(t=>t.channelId===c.id)?'已有任务':'加入计划'}</Button></div>)}</div>:<p className="muted">暂时没有符合条件的渠道。可核对网站资料及下面的资格信息。</p>}
  <details className="advanced-settings"><summary>其他渠道为什么未匹配</summary><div className="fit-list">{data.channels.filter(c=>!matches.some(m=>m.channel.id===c.id)).map(c=><div className="fit-row" key={c.id}><div><strong>{c.name}</strong><p>{eligibilityFor(site,c).eligible?'语言或主题不匹配；可在资源库查看要求。':eligibilityFor(site,c).reason}</p></div></div>)}</div></details>
  <details className="advanced-settings" onToggle={e=>{if(e.currentTarget.open&&!editing){setProof(site.qualifications??{});setEditing(true)}}}><summary>补充实际资格（有对应项目时填写）</summary><p className="muted">仅填写你本人有权维护的真实资料网址。填写即确认该资格；文章渠道通常无需这些资料。</p><div className="form-grid">{Object.entries(qualificationLabels).map(([k,label])=><Field label={label+'网址'} key={k}><input type="url" value={proof[k as Qualification]??''} placeholder="https://…" onChange={e=>setProof({...proof,[k]:e.target.value})}/></Field>)}</div><Button disabled={disabled} onClick={()=>void onAction('site:update',{id:site.id,qualifications:Object.fromEntries(Object.entries(proof).filter(([,v])=>v?.trim()).map(([k,v])=>[k,v!.trim()]))},'资格资料已保存，已重新匹配。')}>保存并重新匹配</Button></details>
 </section><section className="panel"><div className="panel-head"><div><h2>搜索引擎外链报告</h2><p className="muted">网页存在链接与搜索引擎已报告分别记录。报告可能滞后或不完整。</p></div></div><div className="search-report-grid">
  <div><h3>Google Search Console</h3><p>{site.searchReports?.gsc?.message??'尚未导入 GSC 来源网页报告。'}</p><small>{site.searchReports?.gsc?'导入于 '+new Date(site.searchReports.gsc.checkedAt).toLocaleString():'GSC 官方 API 不提供外链报告，使用控制台导出的来源网页 CSV。'}</small><div className="card-actions"><Button disabled={disabled} onClick={()=>void onAction('external:open',{url:gscUrl})}>打开 GSC</Button><Button disabled={disabled} onClick={()=>void onAction('search:import-gsc',{id:site.id})}>导入 CSV</Button></div></div>
  <div><h3>Bing Webmaster Tools</h3><p>{site.searchReports?.bing?.message??'连接后自动每天检查一次首页来源链接。'}</p><small>{site.searchReports?.bing?'检查于 '+new Date(site.searchReports.bing.checkedAt).toLocaleString():'使用你已有的网站管理权限。'}</small><div className="card-actions"><Button disabled={disabled||!data.settings.hasBingKey} onClick={()=>void onAction('search:bing',{id:site.id})}>立即检查</Button><Button disabled={disabled} onClick={()=>void onAction('external:open',{url:'https://www.bing.com/webmasters/?siteUrl='+encodeURIComponent(site.url+'/')})}>打开 Bing</Button></div><details className="advanced-settings"><summary>{data.settings.hasBingKey?'更新 Bing 连接':'连接 Bing API Key'}</summary><Field label="Bing Webmaster API Key" hint="只在本机加密保存，不会发给 AI"><input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)}/></Field><Button disabled={disabled||!key.trim()} onClick={async()=>{const r=await onAction('search:save-key',{key,enabled:true},'Bing 连接已保存。');if(r){setKey('');await onAction('search:bing',{id:site.id})}}}>保存并检查</Button></details><label className="checkbox"><input type="checkbox" checked={!!data.settings.monitorSearch} disabled={disabled||!data.settings.hasBingKey} onChange={e=>void onAction('settings:save',{monitorSearch:e.target.checked})}/>自动检查 Bing（客户端运行时）</label></div>
 </div><div className="table-scroll"><table className="channel-table"><thead><tr><th>公开来源</th><th>页面链接</th><th>GSC 导入样本</th><th>Bing API 样本</th></tr></thead><tbody>{tasks.filter(t=>t.publicUrl).map(t=><tr key={t.id}><td><button className="inline-link" disabled={disabled} onClick={()=>void onAction('external:open',{url:t.publicUrl})}>{t.sourceDomain}</button></td><td>{t.linkCheck==='invalid'?'地址不符合渠道要求':t.linkCheck==='unreachable'?'暂时无法检查':t.linkCheck==='absent'?'本次未发现':t.verifiedAt?'曾核验存在':'待核验'}</td><td>{reportLabel(site,'gsc',t)}</td><td>{reportLabel(site,'bing',t)}</td></tr>)}</tbody></table>{!tasks.some(t=>t.publicUrl)&&<p className="muted">发布并取得公开地址后，这里会逐条对照报告。</p>}</div></section></div>;
}
function reportLabel(site:Site,engine:'gsc'|'bing',task:Task){const report=site.searchReports?.[engine];if(!report||report.error||!task.publicUrl)return '尚未确认';let url=task.publicUrl;try{const u=new URL(url);u.hash='';url=u.href}catch{}return report.sources.includes(url)?'报告中已出现':'当前样本未出现'}
