import {useState} from 'react';
import type {Channel,Site,Snapshot,Task} from '../../shared/types';
import {discoverChannels} from '../../integrations/channel-discovery';
import {Button,Field} from '../components';
import {channelReadinessForDisplay,channelReadinessLabel} from '../presentation';

export function SiteTools({site,data,disabled,onAction}:{site:Site;data:Snapshot;disabled:boolean;onAction:(cmd:string,payload?:unknown,success?:string)=>Promise<unknown>}){
 const [key,setKey]=useState(''),[gistUrl,setGistUrl]=useState('');
 const discoveries=discoverChannels(site,data.channels),tasks=data.tasks.filter(t=>t.siteId===site.id),readinessRank={ready:0,autocreate:1,handoff_required:2,manual:3} as const;
 const candidates=discoveries.filter(item=>item.status!=='blocked').map((item,index)=>({...item,index,readiness:channelReadinessForDisplay(data,site,item.channel)})).sort((a,b)=>readinessRank[a.readiness]-readinessRank[b.readiness]||a.index-b.index),blocked=discoveries.filter(item=>item.status==='blocked');
 const automaticCandidates=candidates.filter(item=>item.channel.automation!=='manual'&&item.canQueue),automaticContinuable=automaticCandidates.filter(item=>item.readiness==='ready'||item.readiness==='autocreate').length,accountHandoffs=automaticCandidates.filter(item=>item.readiness==='handoff_required').length,manualPreparable=candidates.filter(item=>item.channel.automation==='manual'&&item.canQueue).length,capacity=data.capacity?.find(item=>item.siteId===site.id);
 const gscUrl='https://search.google.com/search-console/links?resource_id='+encodeURIComponent('sc-domain:'+site.domain);
 return <div className="site-tools"><section className="panel"><div className="panel-head"><div><h2>这个网站适合哪些渠道</h2><p className="muted">候选按可执行性优先排列；主题、语言和公开资格只用于判断适合度，不代表平台已经接受。</p></div><span className="badge blue">{candidates.length} 个候选 · {automaticContinuable} 个可自动衔接 · {accountHandoffs} 个需账号 · {manualPreparable} 个可人工准备</span></div>
  {capacity&&<p className="muted">目录余量只统计尚未建立任务的适合来源：{capacity.eligibleUnused} 个，其中自动渠道 {capacity.automaticUnused} 个、人工渠道 {capacity.manualUnused} 个。账号与系统当前是否可执行，以每项状态为准。</p>}
  {automaticCandidates.length===0&&<p className="muted">当前没有可自动推进的新来源。系统会等待目录出现可用渠道；无需为了补足数量填写并不存在的资格。</p>}
  {candidates.length?<div className="fit-list">{candidates.map(item=>{const c=item.channel,existing=tasks.some(t=>t.sourceDomain===c.domain),policyStatus=data.channelPolicyStatus?.[site.id]?.[c.id];return <div className="fit-row" key={c.id}><div><strong>{c.name}</strong><small><span className={`badge ${item.status==='recommended'?'green':item.status==='worth_trying'?'blue':'amber'}`}>{item.status==='recommended'?'推荐':item.status==='worth_trying'?'可尝试':'待准备'}</span> · {c.kind==='article'?'原创文章':'资料 / 项目'} · {c.automation==='api'?'官方 API':c.automation==='browser'?'浏览器操作':'人工提交'} · {channelReadinessLabel[item.readiness]}</small><p>{item.reason} {item.nextStep}</p>{c.id==='telegraph'&&c.provenance==='built-in'&&<div className="card-actions"><small>{policyStatus==='valid'?'已有渠道使用确认；每篇稿件仍须独立 AI 审核。':policyStatus==='expired_or_changed'?'此前的可选确认已失效；自动流程会等待适用政策证据。':'尚未找到适用的内容政策；自动流程会等待新证据，不要求你决定例外。'}</small><Button disabled={disabled} onClick={()=>void onAction('site:confirm-channel-policy',{id:site.id,channelId:c.id})}>可选：渠道使用设置</Button></div>}</div><Button disabled={disabled||existing||!item.canQueue} onClick={()=>void onAction('site:queue-channel',{id:site.id,channelId:c.id},c.automation==='manual'?'人工待办已建立，可继续准备真实材料。':item.readiness==='handoff_required'?'账号接续待办已建立，其他可执行渠道会继续。':'渠道已加入任务。')}>{existing?'已有任务':!item.canQueue?'暂不可加入':item.readiness==='handoff_required'?'建立账号接续待办':c.automation==='manual'?'建立人工待办':'加入计划'}</Button></div>})}</div>:<p className="muted">暂时没有适合的新候选，系统会等待目录或网站条件变化。</p>}
  <details className="advanced-settings"><summary>暂不适合的渠道与原因</summary><div className="fit-list">{blocked.map(item=><div className="fit-row" key={item.channel.id}><div><strong>{item.channel.name}</strong><p>{item.reason} {item.nextStep}</p></div></div>)}</div></details>
  <details className="advanced-settings"><summary>接回已发布的 Gist</summary><p className="muted">填写公开 HTTPS Gist 地址。系统会核验公开页中的目标链接，核验后才计入有效来源；这是外部已发布内容的接回，不会由客户端新建内容。</p><div className="connection-footer"><Field label="公开 Gist URL"><input type="url" value={gistUrl} onChange={e=>setGistUrl(e.target.value)} placeholder="https://gist.github.com/…" autoCapitalize="off"/></Field><Button disabled={disabled||!gistUrl.trim()} onClick={async()=>{const result=await onAction('site:adopt-gist',{id:site.id,url:gistUrl.trim()},'Gist 已接回并完成核验。');if(result)setGistUrl('')}}>核验并接回</Button></div></details>
 </section><section className="panel"><div className="panel-head"><div><h2>搜索引擎外链报告</h2><p className="muted">网页存在链接与搜索引擎已报告分别记录。报告可能滞后或不完整。</p></div></div><div className="search-report-grid">
  <div><h3>Google Search Console</h3><p>{site.searchReports?.gsc?.message??'尚未导入 GSC 来源网页报告。'}</p><small>{site.searchReports?.gsc?'导入于 '+new Date(site.searchReports.gsc.checkedAt).toLocaleString():'GSC 官方 API 不提供外链报告，使用控制台导出的来源网页 CSV。'}</small><div className="card-actions"><Button disabled={disabled} onClick={()=>void onAction('external:open',{url:gscUrl})}>打开 GSC</Button><Button disabled={disabled} onClick={()=>void onAction('search:import-gsc',{id:site.id})}>导入 CSV</Button></div></div>
  <div><h3>Bing Webmaster Tools</h3><p>{site.searchReports?.bing?.message??'连接后自动每天检查一次首页来源链接。'}</p><small>{site.searchReports?.bing?'检查于 '+new Date(site.searchReports.bing.checkedAt).toLocaleString():'使用你已有的网站管理权限。'}</small><div className="card-actions"><Button disabled={disabled||!data.settings.hasBingKey} onClick={()=>void onAction('search:bing',{id:site.id})}>立即检查</Button><Button disabled={disabled} onClick={()=>void onAction('external:open',{url:'https://www.bing.com/webmasters/?siteUrl='+encodeURIComponent(site.url+'/')})}>打开 Bing</Button></div><details className="advanced-settings"><summary>{data.settings.hasBingKey?'更新 Bing 连接':'连接 Bing API Key'}</summary><Field label="Bing Webmaster API Key" hint="只在本机加密保存，不会发给 AI"><input type="password" autoComplete="new-password" value={key} onChange={e=>setKey(e.target.value)}/></Field><Button disabled={disabled||!key.trim()} onClick={async()=>{const r=await onAction('search:save-key',{key,enabled:true},'Bing 连接已保存。');if(r){setKey('');await onAction('search:bing',{id:site.id})}}}>保存并检查</Button></details><label className="checkbox"><input type="checkbox" checked={!!data.settings.monitorSearch} disabled={disabled||!data.settings.hasBingKey} onChange={e=>void onAction('settings:save',{monitorSearch:e.target.checked})}/>自动检查 Bing（客户端运行时）</label></div>
 </div><div className="table-scroll"><table className="channel-table"><thead><tr><th>公开来源</th><th>页面链接</th><th>GSC 导入样本</th><th>Bing API 样本</th></tr></thead><tbody>{tasks.filter(t=>t.publicUrl).map(t=><tr key={t.id}><td><button className="inline-link" disabled={disabled} onClick={()=>void onAction('external:open',{url:t.publicUrl})}>{t.sourceDomain}</button></td><td>{t.linkCheck==='invalid'?'地址不符合渠道要求':t.linkCheck==='unreachable'?'暂时无法检查':t.linkCheck==='absent'?'本次未发现':t.verifiedAt?'曾核验存在':'待核验'}</td><td>{reportLabel(site,'gsc',t)}</td><td>{reportLabel(site,'bing',t)}</td></tr>)}</tbody></table>{!tasks.some(t=>t.publicUrl)&&<p className="muted">发布并取得公开地址后，这里会逐条对照报告。</p>}</div></section></div>;
}
function reportLabel(site:Site,engine:'gsc'|'bing',task:Task){const report=site.searchReports?.[engine];if(!report||report.error||!task.publicUrl)return '尚未确认';let url=task.publicUrl;try{const u=new URL(url);u.hash='';url=u.href}catch{}return report.sources.includes(url)?'报告中已出现':'当前样本未出现'}
