import type { Category, Channel, Site } from '../shared/types.js';
import {eligibilityFor} from './eligibility';

const checkedAt = '2026-09-27';
type Entry = Pick<Channel, 'id'|'name'|'domain'|'submitUrl'|'categories'|'kind'|'free'|'freeNote'|'quality'|'qualityReason'|'rulesUrl'|'notes'> &
  Partial<Pick<Channel, 'languages'|'emailRequired'|'accountRequired'|'articleRequired'|'automation'|'allowedHosts'|'enabled'|'checkedAt'|'requirements'>>;

function channel(entry: Entry): Channel {
  return {
    url: `https://${entry.domain}/`,
    languages: ['en'],
    emailRequired: true,
    accountRequired: true,
    articleRequired: false,
    automation: 'manual',
    allowedHosts: [entry.domain],
    enabled: true,
    provenance: 'built-in',
    evidenceStatus: 'rules_checked',
    checkedAt,
    ...entry,
  };
}

// 渠道必须面向相关受众，并承载真实的资料页、产品、作品或文章。
// A/B/C 仅表示编辑适配度，不代表域名权重、流量或预期 SEO 效果。
export const CHANNELS: Channel[] = [
  channel({id:'github-gist',name:'GitHub Gist',domain:'gist.github.com',submitUrl:'https://gist.github.com/',categories:['developer','software','ai','education','finance'],languages:['*'],kind:'article',free:'yes',freeNote:'公开 Gist 免费；首次连接已有 GitHub 账号的 Gists 读写令牌。',quality:'B',qualityReason:'适合有实际用途的代码、模板和技术说明，不代表权重或收录保证。',rulesUrl:'https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies',notes:'只发布本人项目相关、可复用的技术材料；不得以广告为主要内容。需要提供本人维护的项目资料，稿件确认后通过官方 API 发布。账号复用，受限时不自动换号。',accountRequired:true,emailRequired:false,articleRequired:true,automation:'api'}),
  channel({id:'telegraph',name:'Telegraph',domain:'telegra.ph',submitUrl:'https://telegra.ph/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'官方发布接口无需付费，使用自动创建的作者令牌。',quality:'C',qualityReason:'可独立阅读的公开文章；不代表编辑背书或搜索引擎收录。',rulesUrl:'https://telegra.ph/api',notes:'通过官方 API 创建作者和文章，令牌仅加密保存在本机。现有官方来源为接口文档，不代表已确认所有内容或返佣推广规则；AI 无法核实时会交给用户。文章须有独立价值，明确作者与网站关系，不批量复制或堆放链接。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api'}),
  channel({ id:'product-hunt', name:'Product Hunt', domain:'producthunt.com', submitUrl:'https://www.producthunt.com/posts/new', categories:['software','ai','developer','design','business'], kind:'directory', free:'yes', freeNote:'普通产品发布免费；个人账号还需满足平台的发布权限要求。', quality:'A', qualityReason:'适合已经可用的数字产品，并由平台审核发布内容。', rulesUrl:'https://help.producthunt.com/en/articles/479557-how-to-post-a-product', notes:'每个真实产品只做一次有意义的发布；需完成个人账号引导并满足账号时长等要求，禁止拉票。', allowedHosts:['producthunt.com','www.producthunt.com'] }),
  channel({ id:'alternativeto', name:'AlternativeTo', domain:'alternativeto.net', submitUrl:'https://alternativeto.net/', categories:['software','ai','developer','design'], kind:'directory', free:'yes', freeNote:'可以自行提交新应用，但须通过邮箱验证和编辑审核。', quality:'A', qualityReason:'软件对比目录，提交项需有真实产品网址并进入审核队列。', rulesUrl:'https://alternativeto.net/faq/', notes:'邮箱验证后使用“Suggest new application”；待审条目不会公开。' }),
  channel({ id:'g2', name:'G2', domain:'g2.com', submitUrl:'https://sell.g2.com/create-a-profile', categories:['software','ai','developer','business'], kind:'directory', free:'yes', freeNote:'认领基础产品资料页免费，另有付费升级方案。', quality:'A', qualityReason:'面向软件采购者的产品资料和评价平台。', rulesUrl:'https://sell.g2.com/plans', notes:'只适用于真实软件产品；资格、资料审核和评价规则均由平台决定。', allowedHosts:['g2.com','sell.g2.com','my.g2.com'] }),
  channel({ id:'saashub', name:'SaaSHub', domain:'saashub.com', submitUrl:'https://www.saashub.com/services/submit', categories:['software','ai','developer','business'], kind:'directory', free:'unknown', freeNote:'存在可用的产品提交表单，但该页面没有明确写出当前刊登费用。', quality:'B', qualityReason:'与软件发现相关，并设有产品审核。', rulesUrl:'https://www.saashub.com/services/submit', notes:'仅接受已发布、有独立域名的英文软件；不接受等待名单、代理服务或免费托管子域名。提交前先确认费用。', allowedHosts:['saashub.com','www.saashub.com'] }),
  channel({ id:'capterra', name:'Capterra', domain:'capterra.com', submitUrl:'https://www.capterra.com/vendors/', categories:['software','ai','developer','business'], kind:'directory', free:'yes', freeNote:'软件和服务提供商可免费建立资料页；赞助展示和获客服务另行付费。', quality:'A', qualityReason:'面向软件买家的分类资料页和评价平台。', rulesUrl:'https://www.capterra.com/legal/listing-guidelines/', notes:'只提交真实软件或服务；资料不得放促销号召、邮箱、电话或正文网址，平台会审核和规范分类。', allowedHosts:['capterra.com','www.capterra.com'] }),

  channel({ id:'github', name:'GitHub', domain:'github.com', submitUrl:'https://github.com/settings/profile', categories:['developer','software','ai','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'免费账号可使用公开个人资料和仓库链接。', quality:'A', qualityReason:'真实维护者资料或活跃仓库能为开发者提供项目背景。', rulesUrl:'https://docs.github.com/en/account-and-profile/tutorials/personalize-your-profile', notes:'浏览器流程只维护所有者自己的资料；不得创建空仓库或泛泛内容。', automation:'browser' }),
  channel({ id:'gitlab', name:'GitLab', domain:'gitlab.com', submitUrl:'https://gitlab.com/-/profile', categories:['developer','software','ai','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'GitLab Free 包含个人资料和公开项目。', quality:'A', qualityReason:'真实开发者资料或活跃公开项目可提供有用的项目背景。', rulesUrl:'https://docs.gitlab.com/user/profile/', notes:'浏览器流程只维护所有者自己的资料；公开可见性受账号和项目设置影响。', automation:'browser' }),
  channel({ id:'codeberg', name:'Codeberg', domain:'codeberg.org', submitUrl:'https://codeberg.org/repo/create', categories:['developer','software','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'账号和公开仓库免费，但公共内容应采用自由或开源许可并符合非营利平台使命。', quality:'A', qualityReason:'适合真实自由软件项目的代码、文档和项目网站。', rulesUrl:'https://docs.codeberg.org/getting-started/faq/', notes:'仅用于真实自由软件或自由内容项目；不要把商业镜像、媒体备份或纯推广页面放到 Codeberg。' }),
  channel({ id:'npm', name:'npm', domain:'npmjs.com', submitUrl:'https://www.npmjs.com/signup', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'账号可免费发布公开 npm 包。', quality:'A', qualityReason:'真实 JavaScript 包的项目网址和文档对使用者有直接价值。', rulesUrl:'https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages/', notes:'仅用于可安装且有文档的真实软件包；需满足账号、双重验证或令牌要求。', allowedHosts:['npmjs.com','www.npmjs.com'] }),
  channel({ id:'pypi', name:'PyPI', domain:'pypi.org', submitUrl:'https://pypi.org/account/register/', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'账号可免费上传公开 Python 包。', quality:'A', qualityReason:'真实 Python 包的项目主页链接能帮助使用者了解来源和文档。', rulesUrl:'https://packaging.python.org/en/latest/tutorials/packaging-projects/', notes:'仅用于真实 Python 发行包；项目网址应写入包元数据。' }),
  channel({ id:'nuget', name:'NuGet.org', domain:'nuget.org', submitUrl:'https://www.nuget.org/packages/manage/upload', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'免费 NuGet.org 账号可以公开发布软件包。', quality:'A', qualityReason:'真实 .NET 软件包的元数据、说明和项目网址对开发者有直接价值。', rulesUrl:'https://learn.microsoft.com/en-us/nuget/nuget-org/publish-a-package', notes:'只发布真实、可安装的 .NET 包；包 ID 需唯一，提交前检查说明、许可和项目网址。', allowedHosts:['nuget.org','www.nuget.org','learn.microsoft.com'] }),
  channel({ id:'crates-io', name:'crates.io', domain:'crates.io', submitUrl:'https://crates.io/settings/tokens', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'使用账号和 API 令牌即可向 crates.io 发布公开 Rust 包。', quality:'A', qualityReason:'真实 Rust crate 的主页、仓库和说明对开发者有直接价值。', rulesUrl:'https://doc.rust-lang.org/cargo/reference/publishing.html', notes:'发布通常不可撤销，版本不能覆盖或删除；只提交真实 crate，并先补齐许可、说明、主页、仓库和 README。', allowedHosts:['crates.io','doc.rust-lang.org'] }),
  channel({ id:'sourceforge', name:'SourceForge', domain:'sourceforge.net', submitUrl:'https://sourceforge.net/p/add_project', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'公开开源项目的创建流程免费。', quality:'B', qualityReason:'开源项目目录可承载项目说明、下载和主页信息。', rulesUrl:'https://sourceforge.net/p/forge/documentation/Create%20a%20New%20Project/', notes:'仅用于采用有效开源许可的真实软件项目。' }),
  channel({ id:'docker-hub', name:'Docker Hub', domain:'hub.docker.com', submitUrl:'https://hub.docker.com/repository/create', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'Docker Personal 包含不限数量的公开仓库，但拉取频率和公平使用政策仍有限制。', quality:'A', qualityReason:'真实容器镜像的仓库页可向使用者提供版本、说明和来源。', rulesUrl:'https://docs.docker.com/docker-hub/usage/', notes:'仅发布可运行、持续维护且说明完整的真实镜像；免费个人账号受拉取频率和公平使用限制。', allowedHosts:['hub.docker.com','docs.docker.com'] }),
  channel({ id:'huggingface', name:'Hugging Face', domain:'huggingface.co', submitUrl:'https://huggingface.co/new', categories:['ai','developer','education'], kind:'profile', free:'conditional', freeNote:'公开仓库和静态 Spaces 有免费方案；需要计算资源的 Spaces 可能收费。', quality:'A', qualityReason:'真实模型、数据集或演示页对人工智能受众有直接价值。', rulesUrl:'https://huggingface.co/docs/hub/spaces-overview', notes:'仅用于真实模型、数据集或可运行演示；不要创建空仓库。' }),

  channel({ id:'firefox-addons', name:'Firefox Add-ons', domain:'addons.mozilla.org', submitUrl:'https://addons.mozilla.org/developers/addon/submit/distribution', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'使用 Mozilla 账号即可提交扩展；公开上架需通过校验并可能接受后续审核。', quality:'A', qualityReason:'真实 Firefox 扩展的官方发现和安装页面。', rulesUrl:'https://extensionworkshop.com/documentation/publish/submitting-an-add-on/', notes:'只提交可用扩展；上传前阅读附加组件政策和开发者协议，压缩或混淆代码可能还需提供源代码包。', allowedHosts:['addons.mozilla.org','extensionworkshop.com'] }),
  channel({ id:'vscode-marketplace', name:'VS Code Marketplace', domain:'marketplace.visualstudio.com', submitUrl:'https://marketplace.visualstudio.com/manage/publishers/', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'扩展默认可按免费产品发布；需要 Microsoft/Azure DevOps 身份和发布者资料。', quality:'A', qualityReason:'真实 VS Code 扩展的官方发现、说明和安装页面。', rulesUrl:'https://code.visualstudio.com/api/working-with-extensions/publishing-extension', notes:'只发布经过测试的真实扩展；需创建发布者并满足包、图片、安全和元数据限制。', allowedHosts:['marketplace.visualstudio.com','code.visualstudio.com'] }),
  channel({ id:'jetbrains-marketplace', name:'JetBrains Marketplace', domain:'plugins.jetbrains.com', submitUrl:'https://plugins.jetbrains.com/plugin/add', categories:['developer','software','ai'], kind:'directory', free:'conditional', freeNote:'平台允许免费插件，也支持付费或增值插件；免费候选必须明确选择免费分发。', quality:'A', qualityReason:'真实 JetBrains 插件的官方发现、说明和安装页面。', rulesUrl:'https://plugins.jetbrains.com/docs/marketplace/uploading-a-new-plugin.html', notes:'需 JetBrains 账号、Vendor 资料和开发者协议；插件页会经人工审核，开源许可还应提供源码链接。', allowedHosts:['plugins.jetbrains.com'] }),
  channel({ id:'flathub', name:'Flathub', domain:'flathub.org', submitUrl:'https://github.com/flathub/flathub/compare/new-pr...new-pr', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'新应用通过公开 GitHub 合并请求提交，不收刊登费。', quality:'A', qualityReason:'Linux 桌面应用的真实分发页，包含安装、说明和项目资料。', rulesUrl:'https://docs.flathub.org/docs/for-app-authors/requirements#generative-ai-policy', notes:'默认关闭：Flathub 禁止 manifest 含 AI 生成或 AI 辅助内容；AI 工具或代理不得创建或自动化提交 PR，也不得生成 commit 消息、PR 描述、审核评论或回复，且不得请求 AI 代理审查。提交者必须本人纯人工完成提交和审核沟通；应用及其打包中其他 AI 生成材料还须按规则披露并接受审核。', allowedHosts:['flathub.org','docs.flathub.org','github.com'], enabled:false }),
  channel({ id:'fdroid', name:'F-Droid', domain:'f-droid.org', submitUrl:'https://gitlab.com/fdroid/fdroiddata/-/merge_requests/new', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'F-Droid 主仓库不收上架费，但只接收满足严格自由软件和可构建要求的 Android 应用。', quality:'A', qualityReason:'自由开源 Android 应用的真实源码构建和分发页面。', rulesUrl:'https://f-droid.org/docs/Inclusion_Policy/', notes:'必须是持续维护、源码公开、许可合规且依赖可自由构建的 Android 应用；Firebase、Google Play Services 等专有依赖通常不符合要求。', allowedHosts:['f-droid.org','gitlab.com'] }),
  channel({ id:'snap-store', name:'Snap Store', domain:'snapcraft.io', submitUrl:'https://snapcraft.io/account/register-snap', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'免费 Snapcraft 开发者账号可注册并发布公开 snap；特殊权限可能需要人工批准。', quality:'B', qualityReason:'真实 Linux 应用的安装和版本分发页面。', rulesUrl:'https://snapcraft.io/docs/releasing-your-app/', notes:'只提交已构建并测试的真实 snap；名称须唯一，上传会经过自动审核，classic confinement 可能需先获批准。' }),
  channel({ id:'itch-io', name:'itch.io', domain:'itch.io', submitUrl:'https://itch.io/game/new', categories:['design','content','software'], kind:'directory', free:'yes', freeNote:'创建账号、项目页和上传内容免费；出售内容时会涉及自选平台分成及支付费用。', quality:'A', qualityReason:'独立游戏、漫画、音乐和数字素材的真实作品页。', rulesUrl:'https://itch.io/docs/creators/getting-started', notes:'仅用于本人创作且实际可展示或下载的项目；新页面默认私有，需完成内容后改为公开。' }),

  channel({ id:'dev', name:'DEV Community', domain:'dev.to', submitUrl:'https://dev.to/new', categories:['developer','software','ai','education'], kind:'article', free:'yes', freeNote:'账号可免费发布社区文章。', quality:'B', qualityReason:'原创技术文章可在正文语境中为读者提供有用链接。', rulesUrl:'https://dev.to/terms', notes:'默认关闭：DEV 禁止主要为了推广或获取反向链接而写的内容。仅适合由人工主导的实质性技术文章。', articleRequired:true, enabled:false }),
  channel({ id:'hashnode', name:'Hashnode', domain:'hashnode.com', submitUrl:'https://hashnode.com/onboard', categories:['developer','software','ai','education'], kind:'article', free:'yes', freeNote:'Hashnode 子域名上的技术出版物可免费建立；部分自定义域名功能需要 Pro。', quality:'B', qualityReason:'实质性教程或产品说明可服务技术读者。', rulesUrl:'https://hashnode.com/code-of-conduct', notes:'只做人工主导的技术知识分享；平台禁止 automated or bulk posting 和 SEO abuse。AI 辅助稿须人工审核，不能作为无人值守发布渠道。公开文章可能位于 hashnode.dev 子域名。', articleRequired:true, allowedHosts:['hashnode.com','hashnode.dev'] }),
  channel({ id:'medium', name:'Medium', domain:'medium.com', submitUrl:'https://medium.com/new-story', categories:['content','education','business','design','software','ai'], kind:'article', free:'conditional', freeNote:'免费账号可以发布文章；读者能否免费阅读取决于文章的付费墙设置。', quality:'B', qualityReason:'有实质内容的原创文章可以服务目标读者。', rulesUrl:'https://help.medium.com/hc/en-us/articles/213477928-Medium-Rules', notes:'默认关闭：Medium 禁止自动、系统化或程序化注册与发文，禁止主要为外部引流或搜索排名写稿。附带联盟链接须披露；加密内容另受专项规则约束。AI 审核通过不等于可以自动发布。', articleRequired:true, enabled:false }),
  channel({ id:'substack', name:'Substack', domain:'substack.com', submitUrl:'https://substack.com/start', categories:['content','education','business','design'], kind:'profile', free:'conditional', freeNote:'免费出版物可添加主页链接，但仍需完成出版物和受众设置。', quality:'B', qualityReason:'真实运营的出版物可为读者提供相关自有资源。', rulesUrl:'https://support.substack.com/hc/en-us/articles/360059181172-How-do-I-add-links-to-my-Substack-homepage', notes:'仅维护本人真实运营的出版物；不适合为外部引流或 SEO 新建出版物。按平台规则人工处理，不进行无人值守浏览器操作。', automation:'manual', allowedHosts:['substack.com'] }),
  channel({ id:'indie-hackers', name:'Indie Hackers', domain:'indiehackers.com', submitUrl:'https://www.indiehackers.com/products', categories:['business','software','ai','developer'], kind:'community', free:'unknown', freeNote:'产品目录提供“Add Your Product”，但该页面未明确当前账号或费用条件。', quality:'B', qualityReason:'创业者和产品社区，适合真实创作者及产品资料。', rulesUrl:'https://www.indiehackers.com/products', notes:'只做人工提交和真实参与；不得批量发帖。', allowedHosts:['indiehackers.com','www.indiehackers.com'] }),
  channel({ id:'show-hn', name:'Show HN', domain:'news.ycombinator.com', submitUrl:'https://news.ycombinator.com/submit', categories:['developer','software','ai','design'], kind:'community', free:'yes', freeNote:'社区提交免费，但发布权限可能取决于账号状态。', quality:'A', qualityReason:'本人制作且可直接体验的项目能获得技术社区的真实反馈。', rulesUrl:'https://news.ycombinator.com/showhn.html', notes:'只允许人工做一次性判断。项目必须可体验；不接受纯落地页、新闻通讯、拉票或例行版本更新。', emailRequired:false }),

  channel({ id:'behance', name:'Behance', domain:'behance.net', submitUrl:'https://www.behance.net/', categories:['design','content'], languages:['*'], kind:'profile', free:'yes', freeNote:'标准创意资料页提供网站网址字段。', quality:'A', qualityReason:'真实作品集上的网站链接对查看作品的访客有直接价值。', rulesUrl:'https://help.behance.net/hc/en-us/articles/360034538213-Guide-Fill-Out-Your-Profile', notes:'浏览器流程只维护所有者自己的作品集；资料还要求填写所在地。', automation:'browser', allowedHosts:['behance.net','www.behance.net'] }),
  channel({ id:'artstation', name:'ArtStation', domain:'artstation.com', submitUrl:'https://www.artstation.com/', categories:['design','content'], languages:['*'], kind:'profile', free:'yes', freeNote:'艺术家可获得免费作品集网站，部分自定义功能收费。', quality:'A', qualityReason:'包含真实作品及个人网站链接的作品集与访客需求直接相关。', rulesUrl:'https://help.artstation.com/en/articles/16155273-what-s-the-difference-between-my-community-profile-and-my-website-why-are-there-2-profiles', notes:'浏览器流程只维护所有者自己的艺术家资料；作品必须由该艺术家或工作室创作。', automation:'browser', allowedHosts:['artstation.com','www.artstation.com'] }),
  channel({ id:'gravatar', name:'Gravatar', domain:'gravatar.com', submitUrl:'https://gravatar.com/profile', categories:['general'], languages:['*'], kind:'profile', free:'yes', freeNote:'个人公开资料页和普通链接完全免费；首年免费自定义域名续费另计。', quality:'C', qualityReason:'统一身份和个人链接页对已在寻找该所有者的访客有用，但不构成编辑背书。', rulesUrl:'https://support.gravatar.com/your-profile/links/', notes:'仅维护本人或本人组织的真实资料；普通链接不经过平台验证，公开资料默认可被搜索引擎索引。' }),
  channel({ id:'linktree', name:'Linktree', domain:'linktr.ee', submitUrl:'https://linktr.ee/register', categories:['general'], languages:['*'], kind:'profile', free:'yes', freeNote:'免费方案包含基础链接，免费页面可能显示广告。', quality:'C', qualityReason:'个人链接页对已经寻找该所有者的访客有用，但不构成编辑背书。', rulesUrl:'https://linktr.ee/s/pricing', notes:'只适合已有真实受众的所有者品牌或创作者资料；不得只为制造链接而新建账号。' }),

  channel({ id:'clutch', name:'Clutch', domain:'clutch.co', submitUrl:'https://clutch.co/get-listed', categories:['business','design','developer','software'], kind:'directory', free:'yes', freeNote:'服务商基础公司资料页免费，另有付费升级。', quality:'A', qualityReason:'经审核的代理或服务公司资料包含网站和服务详情。', rulesUrl:'https://help.clutch.co/en/knowledge/get-listed-on-clutch', notes:'仅用于有真实客户服务的公司；公开前需经过审核。', allowedHosts:['clutch.co','www.clutch.co'] }),
  channel({ id:'wellfound', name:'Wellfound', domain:'wellfound.com', submitUrl:'https://wellfound.com/onboarding/recruit', categories:['business','software','ai','developer'], kind:'profile', free:'yes', freeNote:'招聘公司的基础公司资料页免费。', quality:'B', qualityReason:'真实初创公司的资料对求职者和潜在合作方有用。', rulesUrl:'https://help.wellfound.com/article/1075-how-do-i-recruit-with-wellfound-for-free', notes:'仅适用于真实初创公司或雇主；需要个人登录并完成公司引导。' }),

  channel({ id:'google-business', name:'Google 商家资料', domain:'business.google.com', submitUrl:'https://business.google.com/add', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'符合资格的商家可以免费添加或认领资料。', quality:'A', qualityReason:'经验证的实体或上门服务商家资料能向本地顾客展示官网、营业时间和联系方式。', rulesUrl:'https://support.google.com/business/answer/13763036?hl=zh-Hans', notes:'仅限营业时间内与顾客面对面接触的实体店或上门服务商家；纯线上业务、引流公司和无权代表的地点不符合资格。', allowedHosts:['business.google.com','support.google.com'] }),
  channel({ id:'bing-places', name:'Bing Places for Business', domain:'bing.com', submitUrl:'https://www.bing.com/forbusiness/', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'商家可免费添加、认领并完善 Bing 资料。', quality:'B', qualityReason:'经验证的本地商家资料可展示官网、营业时间、服务和联系信息。', rulesUrl:'https://www.bing.com/forbusiness/', notes:'仅用于真实商家；需提供有效地址并通过地址、电话或邮箱验证，部分商家可在搜索结果中隐藏地址。', allowedHosts:['bing.com','www.bing.com','bingplaces.com','www.bingplaces.com'] }),
  channel({ id:'apple-business', name:'Apple Business', domain:'business.apple.com', submitUrl:'https://business.apple.com/', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'Apple Business 的基础服务免费，额外存储和 AppleCare 等可选服务收费。', quality:'A', qualityReason:'经验证的公司和地点资料可在 Apple 地图等应用中展示品牌、网址和关键资料。', rulesUrl:'https://www.apple.com/newsroom/2026/03/introducing-apple-business-a-new-all-in-one-platform-for-businesses-of-all-sizes/', notes:'需使用 Apple 账号注册并验证真实公司或组织；服务和功能可用性因国家或地区而异。' }),
  channel({ id:'yelp-business', name:'Yelp for Business', domain:'yelp.com', submitUrl:'https://biz.yelp.com/claim', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'认领和维护基础商家页面完全免费，广告及部分增强功能另行付费。', quality:'B', qualityReason:'真实本地商家页面可向顾客展示官网、营业信息和顾客评价。', rulesUrl:'https://www.yelp-support.com/article/What-is-a-claimed-business?l=en_US', notes:'仅添加或认领本人有权管理的真实商家；需完成验证，并保持网址、地址、电话和营业时间准确。', allowedHosts:['yelp.com','www.yelp.com','biz.yelp.com','www.yelp-support.com'] }),
  channel({id:'uneed',name:'Uneed',domain:'uneed.best',submitUrl:'https://www.uneed.best/submit-a-tool',categories:['software','ai','developer','design','business'],kind:'directory',free:'conditional',freeNote:'有免费排队；需在控制台另行选择排期，队列满时可能暂停。免费刊登的保留与链接属性受平台条件影响。',quality:'B',qualityReason:'真实科技产品可以获得发现机会；排期、审核和留存条件单独核对。',rulesUrl:'https://www.uneed.best/how-it-works',notes:'提交产品资料不等于已排期。只提交真实可用产品，不生成虚假投票；不承诺当月发布或永久保留。',allowedHosts:['uneed.best','www.uneed.best'],checkedAt:'2026-09-28'}),
  channel({id:'betalist',name:'BetaList',domain:'betalist.com',submitUrl:'https://betalist.com/submit',categories:['software','ai','developer','business'],kind:'directory',free:'paid',freeNote:'官方 FAQ 明确所有提交目前收费，不再提供免费提交。',quality:'B',qualityReason:'适合未发布或近期发布的真实科技初创产品，仍需编辑审核。',rulesUrl:'https://betalist.com/support',notes:'需要独立域名与明确产品价值。不会进入免费自动计划；费用和资格必须在平台确认，本工具不代付。',checkedAt:'2026-09-28'}),
  channel({id:'wordpress-plugins',name:'WordPress.org Plugins',domain:'wordpress.org',submitUrl:'https://wordpress.org/plugins/developers/add/',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方提供插件提交入口；本轮资料未单独确认刊登费用字段，请在提交前核对。',quality:'A',qualityReason:'真实 WordPress 插件的分发页能为使用者提供功能、维护与项目资料。',rulesUrl:'https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/',notes:'必须有完整可用且许可合规的插件；不能只是推广壳。登录后上传，接受人工审核；不得把普通网站网址当成插件资格。',checkedAt:'2026-09-28'}),
  channel({id:'drupal',name:'Drupal.org Projects',domain:'drupal.org',submitUrl:'https://www.drupal.org/project/add',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方提供项目创建步骤；费用未单独核实。',quality:'A',qualityReason:'适合真实 Drupal 模块、主题和相关代码项目。',rulesUrl:'https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/creating-a-new-project/how-to-create-a-new-project',notes:'需要实际代码与后续维护；遵守项目广告规则，不创建空项目或纯推广页面。',allowedHosts:['drupal.org','www.drupal.org'],checkedAt:'2026-09-28'}),
  channel({id:'packagist',name:'Packagist',domain:'packagist.org',submitUrl:'https://packagist.org/packages/submit',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'公开包有官方提交入口；此处不把私有托管订阅费用与公开仓库条件混记，提交前确认。',quality:'A',qualityReason:'真实 Composer 包的主页、说明和仓库信息服务 PHP 开发者。',rulesUrl:'https://packagist.org/about',notes:'需要可安装的真实项目和仓库根目录 composer.json。验证包名、许可及分发权；不提交没有软件功能的外链占位包。',checkedAt:'2026-09-28'}),
  channel({id:'pub-dev',name:'pub.dev',domain:'pub.dev',submitUrl:'https://pub.dev/',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方文档提供 Dart 包发布流程；费用未单独核实。',quality:'A',qualityReason:'真实 Dart/Flutter 包的版本、文档和项目网址对使用者有直接价值。',rulesUrl:'https://dart.dev/tools/pub/publishing',notes:'需要 Google 身份、可用包、LICENSE 与分发权；使用 dart pub publish。已发布版本通常不能撤下，需本人确认制品后发布。',checkedAt:'2026-09-28'}),
  channel({id:'rubygems',name:'RubyGems',domain:'rubygems.org',submitUrl:'https://rubygems.org/sign_up',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方说明了 gem 发布与账号流程；费用与当前账号安全要求需在发布前确认。',quality:'A',qualityReason:'真实 Ruby gem 的项目主页与说明可帮助开发者使用和维护软件。',rulesUrl:'https://guides.rubygems.org/publishing/',notes:'必须有可安装的真实 gem、唯一包名及维护权限。使用正式包发布流程，不创建推广占位包。',checkedAt:'2026-09-28'}),
  channel({id:'blogger',name:'Blogger',domain:'blogspot.com',submitUrl:'https://www.blogger.com/',categories:['content','education','business','design','finance','ai','developer','general'],languages:['*'],kind:'article',free:'unknown',freeNote:'官方提供个人博客创建与管理流程；费用未在本轮资料单独确认，按当前账号界面核对。',quality:'C',qualityReason:'适合持续经营的原创出版物；自建文章页面不等于第三方编辑推荐。',rulesUrl:'https://www.blogger.com/content-policy',notes:'仅用于本人真实运营且具有独立价值的出版物；不得建立重复促销或垃圾博客。金融稿件、商业关系与引用须人工核对，不进行无人值守发布。',articleRequired:true,allowedHosts:['blogspot.com','blogger.com','www.blogger.com'],checkedAt:'2026-09-28'}),
  channel({id:'hackernoon',name:'HackerNoon',domain:'hackernoon.com',submitUrl:'https://app.hackernoon.com/',categories:['developer','software','ai','business','finance','education'],kind:'article',free:'conditional',freeNote:'个人与品牌发布方式不同，品牌免费额度和后续收费需在账号内确认；不能当成无限免费投稿。',quality:'B',qualityReason:'技术文章可服务 AI、区块链与软件读者，受编辑审核与链接规则约束。',rulesUrl:'https://help.hackernoon.com/backlinks-guideline',notes:'只提交有深度的真实技术内容，品牌故事使用品牌身份。商业关系明确披露；遵守来源多样性和链接密度要求，不在通过审核后偷换推广链接。先由本人核对稿件。',articleRequired:true,allowedHosts:['hackernoon.com','app.hackernoon.com'],checkedAt:'2026-09-28'}),
  channel({id:'paragraph',name:'Paragraph',domain:'paragraph.com',submitUrl:'https://app.paragraph.com/',categories:['content','education','business','developer','ai','finance'],languages:['*'],kind:'article',free:'unknown',freeNote:'产品提供出版物功能；方案与费用需在账号中核对，不将试用等同于永久免费。',quality:'C',qualityReason:'适合本人持续运营的原创出版物，不代表第三方编辑背书。',rulesUrl:'https://paragraph.com/content-guidelines',notes:'禁止以第三方促销、获取佣金或外部销售引流为主要目的的出版物。只允许实质原创内容中相关且明确披露的附带商业链接；仅向主动订阅者发信，人工核对后发布。',articleRequired:true,allowedHosts:['paragraph.com','app.paragraph.com'],checkedAt:'2026-09-28'}),

  // 原创金融内容和真实品牌资料；这些入口尚未接入自动发布。
  channel({id:'wordpress-com',name:'WordPress.com',domain:'wordpress.com',submitUrl:'https://wordpress.com/start/',categories:['content','education','finance','business'],languages:['*'],kind:'article',free:'conditional',freeNote:'提供免费子域名与文章托管；自定义域名、去广告等功能另收费。',quality:'B',qualityReason:'适合持续更新的独立科普博客；自有出版物不等于第三方推荐。',rulesUrl:'https://wordpress.com/support/monetize-your-site/',notes:'原创内容必须是主要目的。允许相关附带联盟链接，但禁止以联盟引流为主的站点、快速致富与不可靠商家推广。返佣关系应明确披露；不复制整批站群文章或建立跳转页。人工维护本人博客，发布后另核验公开链接。',articleRequired:true,requirements:['publication'],checkedAt:'2026-09-30'}),
  channel({id:'ghost-pro',name:'Ghost(Pro)',domain:'ghost.io',submitUrl:'https://account.ghost.org/',categories:['content','education','finance','business'],languages:['*'],kind:'article',free:'paid',freeNote:'托管出版物为付费订阅；免费试用不等于永久免费，请先核对当前方案。',quality:'B',qualityReason:'适合长期运营的金融知识出版物；不会直接获得 ghost.org 主域的权威或受众。',rulesUrl:'https://ghost.org/terms/',notes:'使用本人持续运营的原创出版物；仅给主动订阅者发信，禁止未经允许的促销和欺诈。不自动购买方案。本条目接回 ghost.io 子域名的公开文章；自定义域名需单独建立人工渠道。不要把自有网站文章记作新的外部来源。本客户端尚未接入 Ghost 发布 API，不能因平台提供 API 就称为已自动化。',articleRequired:true,requirements:['publication'],allowedHosts:['ghost.org','account.ghost.org','ghost.io'],checkedAt:'2026-09-30'}),
  channel({id:'tumblr',name:'Tumblr',domain:'tumblr.com',submitUrl:'https://www.tumblr.com/new/text',categories:['content','education','finance','design'],languages:['*'],kind:'article',free:'unknown',freeNote:'文章入口已核对；付费功能和账号条件以当前平台页面为准。',quality:'C',qualityReason:'可用于原创图解和知识分享；受众适配及具体页面公开性需另核验。',rulesUrl:'https://www.tumblr.com/policy/user-guidelines',notes:'仅供人工操作：禁止自动、系统化或程序化注册及发帖，禁止以联盟营销为主要目的的博客。适用于有独立阅读价值的教育内容，不能批量复制站群稿或堆返佣链接。返佣主导的落地页不适合此渠道。',articleRequired:true,requirements:['publication'],allowedHosts:['tumblr.com','www.tumblr.com'],checkedAt:'2026-09-30'}),
  channel({id:'linkedin-articles',name:'LinkedIn 文章',domain:'linkedin.com',submitUrl:'https://www.linkedin.com/article/new/',categories:['business','education','finance','content'],languages:['*'],kind:'article',free:'conditional',freeNote:'成员及有权限的主页管理员可发布文章；需要真实身份和正常账号。',quality:'B',qualityReason:'适合面向专业读者的研究或经验；文章公开不代表搜索收录。',rulesUrl:'https://www.linkedin.com/help/linkedin/answer/a519782',notes:'人工发布本人专业知识与原创研究，可以提供相关参考链接。文章政策不接受产品、服务或活动广告；纯交易所推广、邀请码合集不适合。不得虚构从业资历、自动批量加好友或发私信。',articleRequired:true,requirements:['publication'],allowedHosts:['linkedin.com','www.linkedin.com'],checkedAt:'2026-09-30'}),
  channel({id:'youtube-channel',name:'YouTube 频道资料',domain:'youtube.com',submitUrl:'https://studio.youtube.com/',categories:['content','education','finance'],languages:['*'],kind:'profile',free:'conditional',freeNote:'本人频道可在资料中管理网站链接；需要已有正常运营的频道。',quality:'B',qualityReason:'为原创视频观众提供作者网站；资料链接与正文外链、搜索收录分别核验。',rulesUrl:'https://support.google.com/youtube/answer/9054257',notes:'维护真实运营频道的资料链接，入口在 YouTube Studio → 自定义 → 个人资料。联盟内容本身不被一概禁止，但专门账号过量发布联盟内容可能构成垃圾内容。不得夸大收益、引向诈骗页面或只建空频道挂链接；客户端不自动上传视频。',requirements:['publication'],allowedHosts:['youtube.com','www.youtube.com','studio.youtube.com'],checkedAt:'2026-09-30'}),
  channel({id:'x-profile',name:'X 品牌资料',domain:'x.com',submitUrl:'https://x.com/settings/profile',categories:['content','education','finance','business'],languages:['*'],kind:'profile',free:'unknown',freeNote:'资料页提供网站字段；功能、账号验证和地区可用性需在账号内核对。',quality:'C',qualityReason:'方便真实读者找到运营者网站；不承诺链接传递权重或自然流量。',rulesUrl:'https://help.x.com/en/rules-and-policies/authenticity',notes:'人工维护本人或真实品牌资料的网站字段。明确独立运营与商业关系，不冒充交易所。禁止重复灌链接、批量无关回复、协同刷互动或为绕过封禁换号；个人资料链接可能经过平台跳转，须另外验证公开结果。',requirements:['publication'],allowedHosts:['x.com','www.x.com','twitter.com'],checkedAt:'2026-09-30'}),
  channel({id:'publish0x',name:'Publish0x（仅人工原创）',domain:'publish0x.com',submitUrl:'https://www.publish0x.com/become',categories:['finance','content','education'],languages:['*'],kind:'article',free:'conditional',freeNote:'本人项目的内容可免费发布，但作者资格需申请；代客户营销另有条件。',quality:'B',qualityReason:'有加密货币读者，适合有独立价值的原创分享；作者资格并非自动批准。',rulesUrl:'https://www.publish0x.com/page/rules',notes:'本工具中停用：平台禁止 AI 写稿及任何自动发布，只允许本人纯人工原创。允许适度附带推荐链接，但禁止 SEO 外链文、引流落地页、内容搬运和多账号。不能用 AI 审核代替平台对人工创作的要求；保留规则记录供人工评估。',articleRequired:true,requirements:['publication'],enabled:false,allowedHosts:['publish0x.com','www.publish0x.com'],checkedAt:'2026-09-30'}),
  channel({id:'pinterest',name:'Pinterest（金融推广需预审）',domain:'pinterest.com',submitUrl:'https://www.pinterest.com/pin-creation-tool/',categories:['finance','content','education','design'],languages:['*'],kind:'profile',free:'unknown',freeNote:'普通内容与商业推广有不同条件；金融推广许可及费用需另行核对。',quality:'C',qualityReason:'适合原创图解，但联盟金融内容还有额外资格，不能视为通用返佣发布入口。',rulesUrl:'https://policy.pinterest.com/en/commercial-and-branded-content-guidelines',notes:'本工具中停用：联盟内容必须遵循商业合作及广告规则；加密产品服务受限，允许的交易所及钱包广告仍需资质、地区合规与平台预批准。不能把普通 Pin 当作规避金融推广限制的方法。禁止批量重复联盟 Pin、假账号和互刷。',requirements:['publication'],enabled:false,allowedHosts:['pinterest.com','www.pinterest.com'],checkedAt:'2026-09-30'}),

];

const related: Partial<Record<Category, Category[]>> = {
  ai:['software','developer'], software:['ai','developer','business'], developer:['software','ai','education'],
  design:['content','software'], business:['software','content'], content:['design','education','business'],
  education:['content','developer'], finance:['business'],
};

const categoryLabel: Record<Category, string> = {
  software:'软件', ai:'人工智能', developer:'开发者', design:'设计', business:'商业',
  content:'内容', education:'教育', finance:'金融', general:'综合',
};

export function matchChannels(site: Site, channels: Channel[]): Array<{channel: Channel; score: number; reason: string}> {
  return channels.flatMap(channel => {
    if (!eligibilityFor(site,channel).eligible) return [];
    const direct = channel.categories.includes(site.category);
    const adjacent = !direct && (related[site.category] ?? []).some(category => channel.categories.includes(category));
    const general = channel.categories.includes('general');
    const relevance = direct ? 70 : adjacent ? 42 : general ? (channel.id==='telegraph'?55:site.category === 'general' ? 55 : 20) : 0;
    if (relevance < 35) return [];
    const language = site.language.toLowerCase().split('-')[0];
    const languageFit = channel.languages.includes(language) || channel.languages.includes('*');
    // 英文编辑渠道不能仅凭类别相关，就推荐给其他语言的网站。
    if (!languageFit && language !== 'und') return [];
    const score = Math.min(100, relevance + (languageFit ? 15 : 0) +
      (channel.quality === 'A' ? 8 : channel.quality === 'B' ? 4 : 0) +
      (channel.free === 'yes' ? 5 : channel.free === 'conditional' ? 1 : 0));
    const label = categoryLabel[site.category];
    const reason = direct ? `适合${label}类受众` : adjacent ? `与${label}类受众相关` : '覆盖面较广，需人工确认适配度';
    return [{ channel, score, reason: `${reason}；${eligibilityFor(site,channel).reason}；${channel.qualityReason}` }];
  }).sort((a, b) => b.score - a.score || a.channel.name.localeCompare(b.channel.name));
}
