import type { Category, Channel, Site } from '../shared/types.js';
import {channelDiscoveryFor} from './channel-discovery';

const checkedAt = '2026-09-27';
type Entry = Pick<Channel, 'id'|'name'|'domain'|'submitUrl'|'categories'|'kind'|'free'|'freeNote'|'quality'|'qualityReason'|'rulesUrl'|'notes'> &
  Partial<Pick<Channel, 'contentFormat'|'languages'|'emailRequired'|'accountRequired'|'articleRequired'|'automation'|'allowedHosts'|'enabled'|'checkedAt'|'requirements'|'evidenceSources'|'evidenceStatus'>>;

function channel(entry: Entry): Channel {
  return {
    url: `https://${entry.domain}/`,
    languages: ['en'],
    emailRequired: true,
    accountRequired: true,
    articleRequired: false,
    automation: 'manual',
    allowedHosts: [entry.domain],
    enabled: true,
    provenance: 'built-in',
    evidenceStatus: 'rules_checked',
    checkedAt,
    ...entry,
  };
}

// 渠道必须面向相关受众，并承载真实的资料页、产品、作品或文章。
// A/B/C 仅表示编辑适配度，不代表域名权重、流量或预期 SEO 效果。
export const CHANNELS: Channel[] = [
  channel({id:'betterthanhtml',name:'Better Than HTML · Workshop',domain:'betterthanhtml.com',submitUrl:'https://betterthanhtml.com/connect',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'官方提供免费免注册全文接口；Workshop 无设定到期日，不能保证服务永久运行。',quality:'C',qualityReason:'实验型公开 HTML 内容平台，权威与流量未知；公开可读不代表已被搜索引擎收录。',rulesUrl:'https://betterthanhtml.com/ai',evidenceSources:[{url:'https://betterthanhtml.com/ai',kind:'product_guidance',appliesTo:'betterthanhtml',applicability:'verified'}],evidenceStatus:'source_checked',notes:'免费免账号发布完整静态文章；源文件公开可查看、复用，不上传私人资料。官网明确允许 Workshop 文章，尚未核实独立完整内容政策；按已知官方说明逐篇独立审核真实原创内容及相关引用，不发布垃圾推广、复制稿或收益保证。软件只生成无脚本、无远程图片与追踪的静态页面。未确认编辑删除或所有权保护接口，不承诺发布后可撤回。提交前保留原稿和意图；网络结果不明不重复投稿；通过有界只读查找确认唯一原稿，再核验完整正文、链接与索引指令。',emailRequired:false,accountRequired:false,articleRequired:true,automation:'api',enabled:true,allowedHosts:['betterthanhtml.com'],checkedAt:'2026-10-08'}),
  channel({id:'sigle',name:'Sigle · 钱包发文候选',domain:'sigle.io',submitUrl:'https://app.sigle.io/',categories:['finance','content','education','developer'],languages:['*'],kind:'article',free:'conditional',freeNote:'官网提供免费 Starter 发文档；高级功能及可选链上操作另有条件，逐篇费用仍需确认。',quality:'C',qualityReason:'面向 Web3 内容作者的钱包平台候选；本轮未验收公开全文与外链，不推定权重或收录。',rulesUrl:'https://docs.sigle.io/start-writing/rich-text/',evidenceSources:[{url:'https://docs.sigle.io/start-writing/rich-text/',kind:'product_guidance',appliesTo:'sigle',applicability:'verified'},{url:'https://www.sigle.io/',kind:'product_guidance',appliesTo:'sigle',applicability:'verified'}],evidenceStatus:'source_checked',notes:'平台支持 Leather / Stacks 钱包，富文本可含链接。当前官方源码涉及逐篇签名及账号白名单；连接钱包不等于授权软件持续自动发文。旧文档与当前源码有差异，实际开户、签名、费用和完整内容政策仍需核对。本工具仅收录为人工候选，尚未接入无人值守发布，不要求导入助记词或资产密钥；网站主体资格、真实原创内容与商业关系仍须如实呈现。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'manual',allowedHosts:['sigle.io','www.sigle.io','app.sigle.io'],checkedAt:'2026-10-08'}),
  channel({id:'nuance',name:'Nuance · 钱包发文候选',domain:'nuance.xyz',submitUrl:'https://nuance.xyz/',categories:['finance','content','education','developer'],languages:['*'],kind:'article',free:'unknown',freeNote:'费用与当前开户条件待核实；不将区块链的资源模式直接解释为用户永久免费。',quality:'C',qualityReason:'Internet Computer 全文平台候选；公开页需进一步浏览器核验，不保证权重、流量或搜索收录。',rulesUrl:'https://github.com/Aikindapps/Nuance',evidenceSources:[{url:'https://github.com/Aikindapps/Nuance',kind:'product_guidance',appliesTo:'nuance',applicability:'verified'}],evidenceStatus:'source_checked',notes:'官方源码支持 NFID Wallet、Plug 与 Internet Identity 的有期限身份委托；仍需注册用户名，并有注册和发文日限。不是免注册平台，也不能把普通钱包连接当作无限期自动发布许可。当前本工具未接入委托签名与发布；完整内容政策、公开正文和链接仍待验收，仅作人工候选。不要为投稿转账、授权花费或导入助记词；私人数据不进入公开文章。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'manual',allowedHosts:['nuance.xyz'],checkedAt:'2026-10-08'}),
  channel({id:'rentry',name:'Rentry',domain:'rentry.co',submitUrl:'https://rentry.co/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'免账号全文接口；编辑凭据由软件生成并加密保存在本机。',quality:'C',qualityReason:'公开 Markdown 文档来源，非第三方编辑推荐；逐页核验索引指令，不保证权重或收录。',rulesUrl:'https://rentry.co/rentry_acceptable_use_policy',evidenceSources:[{url:'https://rentry.co/rentry_acceptable_use_policy',kind:'content_policy',appliesTo:'rentry',applicability:'verified'},{url:'https://rentry.co/rentry_terms_of_service',kind:'content_policy',appliesTo:'rentry',applicability:'verified'},{url:'https://github.com/radude/rentry',kind:'api',appliesTo:'rentry',applicability:'verified'}],notes:'通过平台官方客户端公开的接口发布独立有用的原创全文。禁止垃圾内容、冒名和虚假商业关系；AI 辅助与相关推广如实披露，不批量复制稿件或堆链接。固定页面地址和编辑凭据在提交前保存；结果不明只读取原页面，不换地址或换镜像重发。遇验证则停止该渠道，其他任务继续。rentry.org 为同一平台镜像，仅计一个来源。实发页返回 noindex，暂不作为可索引来源启用；原因尚未确认。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['rentry.co'],enabled:false,checkedAt:'2026-10-08'}),
  channel({id:'lucid-page',name:'Lucid.page',domain:'lucid.page',submitUrl:'https://lucid.page/docs/agents',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'免账号公开全文 API；匿名发布后修改或删除需本人登录认领。',quality:'C',qualityReason:'独立的全文文档来源；公开模式允许索引不代表实际收录或链接权重。',rulesUrl:'https://lucid.page/terms',evidenceSources:[{url:'https://lucid.page/terms',kind:'content_policy',appliesTo:'lucid-page',applicability:'verified'},{url:'https://lucid.page/docs/agents',kind:'api',appliesTo:'lucid-page',applicability:'verified'}],notes:'仅将已独立核对、有原创信息价值的文章发布为 public；禁止垃圾内容和链接农场，不将默认 unlisted 文档当作可索引成果。相关推广及 AI 辅助须如实披露。匿名发布不能直接修改或删除，认领凭据仅加密保存在本机；如创建请求返回不明且没有原网址，不重新提交，保留记录并继续其他渠道。已取得原网址的结果只读核验原全文与链接。已完成免账号单篇实发及公开完整标题、正文、链接核验。实测推广链接带 ugc/nofollow；不保证收录、权重或持续可用。',emailRequired:false,accountRequired:false,articleRequired:true,automation:'api',allowedHosts:['lucid.page'],enabled:true,checkedAt:'2026-10-08'}),
  channel({id:'verbose',name:'Verbose.blog（实验）',domain:'verbose.blog',submitUrl:'https://verbose.blog/docs',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'官方 API 自动创建作者身份，不需邮箱或首次授权；一次性令牌仅加密保存在本机。',quality:'C',qualityReason:'小型实验出版平台，公开全文链接带 nofollow/ugc；权重和流量未知，不保证搜索收录。',rulesUrl:'https://verbose.blog/why',evidenceSources:[{url:'https://verbose.blog/why',kind:'product_guidance',appliesTo:'verbose',applicability:'verified'},{url:'https://verbose.blog/docs',kind:'api',appliesTo:'verbose',applicability:'verified'}],notes:'官方明确为 AI 代理提供低摩擦建号与原创全文发布，API v0 尚不保证兼容稳定。仅发布对读者独立有用的原创教育、研究方法与资料说明，相关推广及 AI 辅助如实披露；不发模板灌水、虚假体验、收益承诺或纯返佣导流页。官方用途与 API 文档不等于已核实完整内容政策或金融推广许可，逐篇独立审核已知限制与目标内容。单个工作空间共用一个作者身份；注册令牌回包不明时保留原身份，不重新建号。公开全文与链接一致才计页面成果，同一平台不重复算来源。已完成自动建号与原创全文实发核验；平台仍处实验期，可用性与搜索收录不作保证。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['verbose.blog'],enabled:true,checkedAt:'2026-10-08'}),
  channel({id:'mataroa',name:'Mataroa',domain:'mataroa.blog',submitUrl:'https://mataroa.blog/accounts/create/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'免费博客与官方全文 API；正常注册无需邮箱，首次任务自动建立作者身份。平台若要求验证则保留原身份等待处理。',quality:'C',qualityReason:'原创博客全文及可点击正文链接；不代表第三方编辑推荐，不保证搜索收录或流量。',rulesUrl:'https://mataroa.blog/about/methodology/',evidenceSources:[{url:'https://mataroa.blog/about/methodology/',kind:'content_policy',appliesTo:'mataroa',applicability:'verified'},{url:'https://mataroa.blog/api/docs/',kind:'api',appliesTo:'mataroa',applicability:'verified'}],notes:'面向真实读者的原创博客，可在独立有用的文章中附相关来源。官方禁止面向机器而非人类阅读的低质量内容；不得生成链接占位页、批量改名复制稿或纯促销列表。作者、AI 辅助和商业关系如实披露；未明确限制所有推广主题不等于平台授权全部返佣内容。首次仅建立一个本机作者身份，后续网站复用；不重复建号规避限制。新建账号关闭 Newsletter；已有账号须确认该功能已关闭，仅发布网页。完整标题、正文与匿名页面中的真实链接核验通过才计成果。2026-10-07 已完成单篇自动建号、独立审核、发布与匿名全文核验；后续稿件仍逐篇核对。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['mataroa.blog'],checkedAt:'2026-10-07'}),
  channel({id:'paper-wf',name:'Paper.wf · WriteFreely',domain:'paper.wf',submitUrl:'https://paper.wf/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'conditional',freeNote:'注册页开放且邮箱可选，未见收费门槛；自动注册实测遇到人机验证，可先完成首次验证并连接已有博客。',quality:'C',qualityReason:'独立的公开全文博客来源；不以实例存量文章推断质量、权重或平台许可。',rulesUrl:'https://paper.wf/about',evidenceSources:[{url:'https://developers.write.as/docs/api/',kind:'api',appliesTo:'paper-wf',applicability:'verified'},{url:'https://paper.wf/about',kind:'product_guidance',appliesTo:'paper-wf',applicability:'verified'}],notes:'仅使用固定 Paper.wf 主机的 WriteFreely 官方接口，发布具有独立阅读价值的原创文章并核验公开全文与真实链接。首次任务尝试建立一个作者身份供本机网站复用；遇到人机验证时保留同一身份并暂停，需用户首次完成验证。已有身份受限时不会更换账号规避。尚未找到主机完整内容政策，按已核官方资料和已知限制审核，不宣称获得主题或推广许可。禁止重复灌链接、冒名、侵权及收益保证；作者与网站、AI 辅助及商业关系如实披露。已接入全文接口；首次注册实测被人机验证阻断，真实发文尚未验收。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['paper.wf'],checkedAt:'2026-10-07'}),
  channel({id:'hive',name:'Hive 原创文章',domain:'hive.blog',submitUrl:'https://signup.hive.io/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'conditional',freeNote:'首次需要已有账号及 posting key；免费注册有验证或审批条件。发布无交易手续费，但需要足够 RC 资源。',quality:'C',qualityReason:'独立区块链全文来源，社区可降低内容可见性；链上存在不等于公开文章核验成功或搜索收录。',rulesUrl:'https://hive.blog/faq.html',evidenceSources:[{url:'https://hive.blog/faq.html',kind:'content_policy',appliesTo:'hive',applicability:'verified'},{url:'https://hive.blog/tos.html',kind:'content_policy',appliesTo:'hive',applicability:'verified'},{url:'https://developers.hive.io/tutorials-javascript/submit_post.html',kind:'api',appliesTo:'hive',applicability:'verified'}],notes:'Hive.blog、PeakD、Ecency 是同一 Hive 链的不同入口，同一文章只算一个来源。一次连接本人账号的 posting key 后自动发布原创全文；只发作者根文章，不代投有单独规则的社区，不转账、不投票、不操纵收益。拒绝 active、owner、memo 权限密钥。平台允许在文章中介绍商品服务，但禁止垃圾内容、抄袭和诈骗；相关商业及 AI 辅助关系须清晰披露。链上历史不能彻底删除，连接时明确确认。RC 或网络异常保留原稿延后；两个节点完整内容核对与匿名可见正文链接均通过才计成果。生产实发仍在本轮验收。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['hive.blog','signup.hive.io'],checkedAt:'2026-10-07'}),
  channel({id:'nostr',name:'Nostr 长文',domain:'njump.me',submitUrl:'https://yakihonne.com/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'固定免费中继；首次任务自动在本机创建作者身份，无需邮箱或手动注册。私钥仅加密保存在本机。',quality:'C',qualityReason:'开放协议原创长文及可点击正文链接；多个中继和阅读入口只算一个来源，不保证收录、权重或永久留存。',rulesUrl:'https://yakihonne.com/terms',evidenceSources:[{url:'https://yakihonne.com/terms',kind:'content_policy',appliesTo:'nostr',applicability:'verified'}],notes:'仅通过固定 YakiHonne 中继发布已独立审核的原创长文，并以 njump 匿名文章页核验签名事件、全文和目标链接。按 YakiHonne 内容约束禁止垃圾广告、侵扰、侵权、冒名与违法内容；不批量复制站群稿件，不发送私信、不操纵互动。作者须明确与网站及商业关系；本机身份不会额外公开邮箱或用户资料。多个中继/阅读器不是多个独立来源。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['njump.me','yakihonne.com'],checkedAt:'2026-10-07'}),
  channel({id:'github-gist',name:'GitHub Gist',domain:'gist.github.com',submitUrl:'https://gist.github.com/',categories:['developer','software','ai','education','finance'],languages:['*'],kind:'article',free:'yes',freeNote:'公开 Gist 免费；首次连接已有 GitHub 账号的 Gists 读写令牌。',quality:'B',qualityReason:'适合有实际用途的代码、模板和技术说明，不代表权重或收录保证。',rulesUrl:'https://docs.github.com/en/site-policy/acceptable-use-policies/github-acceptable-use-policies',notes:'只发布本人项目相关、可复用的技术材料；不得以广告为主要内容。需要有本站公开的可复用代码、计算工具或技术模板材料，稿件独立核对后通过官方 API 发布。GitHub 条款要求账号由真人创建；本客户端只导入并复用已有账号，受限时不自动换号。',accountRequired:true,emailRequired:false,articleRequired:true,automation:'api'}),
  channel({id:'telegraph',name:'Telegraph',domain:'telegra.ph',submitUrl:'https://telegra.ph/',categories:['general','content','education','finance','ai','developer'],languages:['*'],kind:'article',free:'yes',freeNote:'官方发布接口无需付费，使用自动创建的作者令牌。',quality:'C',qualityReason:'可独立阅读的公开文章；不代表编辑背书或搜索引擎收录。',rulesUrl:'https://telegra.ph/api',evidenceSources:[{url:'https://telegra.ph/api',kind:'api',appliesTo:'telegraph',applicability:'verified'},{url:'https://telegram.org/blog/telegraph',kind:'product_guidance',appliesTo:'telegraph',applicability:'verified'}],notes:'通过官方 API 创建作者和文章，令牌仅加密保存在本机。现有官方来源为接口文档，不代表已确认所有内容或返佣推广规则；AI 无法核实时会交给用户。文章须有独立价值，明确作者与网站关系，不批量复制或堆放链接。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api'}),
  channel({id:'bluesky',name:'Bluesky',domain:'bsky.app',submitUrl:'https://bsky.app/',categories:['general','education','content','finance','ai','developer'],languages:['*'],kind:'community',free:'yes',freeNote:'公开短帖接口免费；首次需连接本人 Bluesky 账号的应用专用密码。',quality:'C',qualityReason:'原创短内容分发与可点击正文链接；不等于独立编辑推荐，不承诺权重、收录或流量。',rulesUrl:'https://bsky.social/about/support/community-guidelines',evidenceSources:[{url:'https://bsky.social/about/support/community-guidelines',kind:'content_policy',appliesTo:'bluesky',applicability:'verified'}],notes:'先连接本人控制的 Bluesky 托管账号并明确绑定网站，再自动生成短帖、独立审核与发布。只发表独立有用的教育要点及一个相关正文链接，公开披露网站与推荐佣金关系；禁止垃圾信息、重复营销、欺诈或互动操纵。每账号至少间隔一天，每网站同平台沿用文章间隔。短内容单独显示，不计为完整长文或独立背书。现阶段不自动注册账号或接入其他 PDS。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',contentFormat:'social',allowedHosts:['bsky.app'],checkedAt:'2026-10-06'}),
  channel({ id:'product-hunt', name:'Product Hunt', domain:'producthunt.com', submitUrl:'https://www.producthunt.com/posts/new', categories:['software','ai','developer','design','business'], kind:'directory', free:'yes', freeNote:'普通产品发布免费；个人账号还需满足平台的发布权限要求。', quality:'A', qualityReason:'适合已经可用的数字产品，并由平台审核发布内容。', rulesUrl:'https://help.producthunt.com/en/articles/479557-how-to-post-a-product', notes:'每个真实产品只做一次有意义的发布；需完成个人账号引导并满足账号时长等要求，禁止拉票。', allowedHosts:['producthunt.com','www.producthunt.com'] }),
  channel({ id:'alternativeto', name:'AlternativeTo', domain:'alternativeto.net', submitUrl:'https://alternativeto.net/', categories:['software','ai','developer','design'], kind:'directory', free:'yes', freeNote:'可以自行提交新应用，但须通过邮箱验证和编辑审核。', quality:'A', qualityReason:'软件对比目录，提交项需有真实产品网址并进入审核队列。', rulesUrl:'https://alternativeto.net/faq/', notes:'邮箱验证后使用“Suggest new application”；待审条目不会公开。' }),
  channel({ id:'g2', name:'G2', domain:'g2.com', submitUrl:'https://sell.g2.com/create-a-profile', categories:['software','ai','developer','business'], kind:'directory', free:'yes', freeNote:'认领基础产品资料页免费，另有付费升级方案。', quality:'A', qualityReason:'面向软件采购者的产品资料和评价平台。', rulesUrl:'https://sell.g2.com/plans', notes:'只适用于真实软件产品；资格、资料审核和评价规则均由平台决定。', allowedHosts:['g2.com','sell.g2.com','my.g2.com'] }),
  channel({ id:'saashub', name:'SaaSHub', domain:'saashub.com', submitUrl:'https://www.saashub.com/services/submit', categories:['software','ai','developer','business'], kind:'directory', free:'unknown', freeNote:'存在可用的产品提交表单，但该页面没有明确写出当前刊登费用。', quality:'B', qualityReason:'与软件发现相关，并设有产品审核。', rulesUrl:'https://www.saashub.com/services/submit', notes:'仅接受已发布、有独立域名的英文软件；不接受等待名单、代理服务或免费托管子域名。提交前先确认费用。', allowedHosts:['saashub.com','www.saashub.com'] }),
  channel({ id:'capterra', name:'Capterra', domain:'capterra.com', submitUrl:'https://www.capterra.com/vendors/', categories:['software','ai','developer','business'], kind:'directory', free:'yes', freeNote:'软件和服务提供商可免费建立资料页；赞助展示和获客服务另行付费。', quality:'A', qualityReason:'面向软件买家的分类资料页和评价平台。', rulesUrl:'https://www.capterra.com/legal/listing-guidelines/', notes:'只提交真实软件或服务；资料不得放促销号召、邮箱、电话或正文网址，平台会审核和规范分类。', allowedHosts:['capterra.com','www.capterra.com'] }),

  channel({ id:'github', name:'GitHub', domain:'github.com', submitUrl:'https://github.com/settings/profile', categories:['developer','software','ai','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'免费账号可使用公开个人资料和仓库链接。', quality:'A', qualityReason:'真实维护者资料或活跃仓库能为开发者提供项目背景。', rulesUrl:'https://docs.github.com/en/account-and-profile/tutorials/personalize-your-profile', notes:'GitHub 条款要求账号由真人创建；客户端只导入已有账号并维护所有者自己的资料，不自动注册。不得创建空仓库或泛泛内容。', automation:'browser' }),
  channel({ id:'gitlab', name:'GitLab', domain:'gitlab.com', submitUrl:'https://gitlab.com/-/profile', categories:['developer','software','ai','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'GitLab Free 包含个人资料和公开项目。', quality:'A', qualityReason:'真实开发者资料或活跃公开项目可提供有用的项目背景。', rulesUrl:'https://docs.gitlab.com/user/profile/', notes:'首次账号由本人注册后导入，自动注册尚未完成验收；浏览器流程只维护所有者自己的资料；公开可见性受账号和项目设置影响。', automation:'browser' }),
  channel({ id:'codeberg', name:'Codeberg', domain:'codeberg.org', submitUrl:'https://codeberg.org/repo/create', categories:['developer','software','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'账号和公开仓库免费，但公共内容应采用自由或开源许可并符合非营利平台使命。', quality:'A', qualityReason:'适合真实自由软件项目的代码、文档和项目网站。', rulesUrl:'https://docs.codeberg.org/getting-started/faq/', notes:'仅用于真实自由软件或自由内容项目；不要把商业镜像、媒体备份或纯推广页面放到 Codeberg。' }),
  channel({ id:'npm', name:'npm', domain:'npmjs.com', submitUrl:'https://www.npmjs.com/signup', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'账号可免费发布公开 npm 包。', quality:'A', qualityReason:'真实 JavaScript 包的项目网址和文档对使用者有直接价值。', rulesUrl:'https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages/', notes:'仅用于可安装且有文档的真实软件包；需满足账号、双重验证或令牌要求。', allowedHosts:['npmjs.com','www.npmjs.com'] }),
  channel({ id:'pypi', name:'PyPI', domain:'pypi.org', submitUrl:'https://pypi.org/account/register/', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'账号可免费上传公开 Python 包。', quality:'A', qualityReason:'真实 Python 包的项目主页链接能帮助使用者了解来源和文档。', rulesUrl:'https://packaging.python.org/en/latest/tutorials/packaging-projects/', notes:'仅用于真实 Python 发行包；项目网址应写入包元数据。' }),
  channel({ id:'nuget', name:'NuGet.org', domain:'nuget.org', submitUrl:'https://www.nuget.org/packages/manage/upload', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'免费 NuGet.org 账号可以公开发布软件包。', quality:'A', qualityReason:'真实 .NET 软件包的元数据、说明和项目网址对开发者有直接价值。', rulesUrl:'https://learn.microsoft.com/en-us/nuget/nuget-org/publish-a-package', notes:'只发布真实、可安装的 .NET 包；包 ID 需唯一，提交前检查说明、许可和项目网址。', allowedHosts:['nuget.org','www.nuget.org','learn.microsoft.com'] }),
  channel({ id:'crates-io', name:'crates.io', domain:'crates.io', submitUrl:'https://crates.io/settings/tokens', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'使用账号和 API 令牌即可向 crates.io 发布公开 Rust 包。', quality:'A', qualityReason:'真实 Rust crate 的主页、仓库和说明对开发者有直接价值。', rulesUrl:'https://doc.rust-lang.org/cargo/reference/publishing.html', notes:'发布通常不可撤销，版本不能覆盖或删除；只提交真实 crate，并先补齐许可、说明、主页、仓库和 README。', allowedHosts:['crates.io','doc.rust-lang.org'] }),
  channel({ id:'sourceforge', name:'SourceForge', domain:'sourceforge.net', submitUrl:'https://sourceforge.net/p/add_project', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'公开开源项目的创建流程免费。', quality:'B', qualityReason:'开源项目目录可承载项目说明、下载和主页信息。', rulesUrl:'https://sourceforge.net/p/forge/documentation/Create%20a%20New%20Project/', notes:'仅用于采用有效开源许可的真实软件项目。' }),
  channel({ id:'docker-hub', name:'Docker Hub', domain:'hub.docker.com', submitUrl:'https://hub.docker.com/repository/create', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'Docker Personal 包含不限数量的公开仓库，但拉取频率和公平使用政策仍有限制。', quality:'A', qualityReason:'真实容器镜像的仓库页可向使用者提供版本、说明和来源。', rulesUrl:'https://docs.docker.com/docker-hub/usage/', notes:'仅发布可运行、持续维护且说明完整的真实镜像；免费个人账号受拉取频率和公平使用限制。', allowedHosts:['hub.docker.com','docs.docker.com'] }),
  channel({ id:'huggingface', name:'Hugging Face', domain:'huggingface.co', submitUrl:'https://huggingface.co/new', categories:['ai','developer','education'], kind:'profile', free:'conditional', freeNote:'公开仓库和静态 Spaces 有免费方案；需要计算资源的 Spaces 可能收费。', quality:'A', qualityReason:'真实模型、数据集或演示页对人工智能受众有直接价值。', rulesUrl:'https://huggingface.co/docs/hub/spaces-overview', notes:'仅用于真实模型、数据集或可运行演示；不要创建空仓库。' }),

  channel({ id:'firefox-addons', name:'Firefox Add-ons', domain:'addons.mozilla.org', submitUrl:'https://addons.mozilla.org/developers/addon/submit/distribution', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'使用 Mozilla 账号即可提交扩展；公开上架需通过校验并可能接受后续审核。', quality:'A', qualityReason:'真实 Firefox 扩展的官方发现和安装页面。', rulesUrl:'https://extensionworkshop.com/documentation/publish/submitting-an-add-on/', notes:'只提交可用扩展；上传前阅读附加组件政策和开发者协议，压缩或混淆代码可能还需提供源代码包。', allowedHosts:['addons.mozilla.org','extensionworkshop.com'] }),
  channel({ id:'vscode-marketplace', name:'VS Code Marketplace', domain:'marketplace.visualstudio.com', submitUrl:'https://marketplace.visualstudio.com/manage/publishers/', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'扩展默认可按免费产品发布；需要 Microsoft/Azure DevOps 身份和发布者资料。', quality:'A', qualityReason:'真实 VS Code 扩展的官方发现、说明和安装页面。', rulesUrl:'https://code.visualstudio.com/api/working-with-extensions/publishing-extension', notes:'只发布经过测试的真实扩展；需创建发布者并满足包、图片、安全和元数据限制。', allowedHosts:['marketplace.visualstudio.com','code.visualstudio.com'] }),
  channel({ id:'jetbrains-marketplace', name:'JetBrains Marketplace', domain:'plugins.jetbrains.com', submitUrl:'https://plugins.jetbrains.com/plugin/add', categories:['developer','software','ai'], kind:'directory', free:'conditional', freeNote:'平台允许免费插件，也支持付费或增值插件；免费候选必须明确选择免费分发。', quality:'A', qualityReason:'真实 JetBrains 插件的官方发现、说明和安装页面。', rulesUrl:'https://plugins.jetbrains.com/docs/marketplace/uploading-a-new-plugin.html', notes:'需 JetBrains 账号、Vendor 资料和开发者协议；插件页会经人工审核，开源许可还应提供源码链接。', allowedHosts:['plugins.jetbrains.com'] }),
  channel({ id:'flathub', name:'Flathub', domain:'flathub.org', submitUrl:'https://github.com/flathub/flathub/compare/new-pr...new-pr', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'新应用通过公开 GitHub 合并请求提交，不收刊登费。', quality:'A', qualityReason:'Linux 桌面应用的真实分发页，包含安装、说明和项目资料。', rulesUrl:'https://docs.flathub.org/docs/for-app-authors/requirements#generative-ai-policy', notes:'默认关闭：Flathub 禁止 manifest 含 AI 生成或 AI 辅助内容；AI 工具或代理不得创建或自动化提交 PR，也不得生成 commit 消息、PR 描述、审核评论或回复，且不得请求 AI 代理审查。提交者必须本人纯人工完成提交和审核沟通；应用及其打包中其他 AI 生成材料还须按规则披露并接受审核。', allowedHosts:['flathub.org','docs.flathub.org','github.com'], enabled:false }),
  channel({ id:'fdroid', name:'F-Droid', domain:'f-droid.org', submitUrl:'https://gitlab.com/fdroid/fdroiddata/-/merge_requests/new', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'F-Droid 主仓库不收上架费，但只接收满足严格自由软件和可构建要求的 Android 应用。', quality:'A', qualityReason:'自由开源 Android 应用的真实源码构建和分发页面。', rulesUrl:'https://f-droid.org/docs/Inclusion_Policy/', notes:'必须是持续维护、源码公开、许可合规且依赖可自由构建的 Android 应用；Firebase、Google Play Services 等专有依赖通常不符合要求。', allowedHosts:['f-droid.org','gitlab.com'] }),
  channel({ id:'snap-store', name:'Snap Store', domain:'snapcraft.io', submitUrl:'https://snapcraft.io/account/register-snap', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'免费 Snapcraft 开发者账号可注册并发布公开 snap；特殊权限可能需要人工批准。', quality:'B', qualityReason:'真实 Linux 应用的安装和版本分发页面。', rulesUrl:'https://snapcraft.io/docs/releasing-your-app/', notes:'只提交已构建并测试的真实 snap；名称须唯一，上传会经过自动审核，classic confinement 可能需先获批准。' }),
  channel({ id:'itch-io', name:'itch.io', domain:'itch.io', submitUrl:'https://itch.io/game/new', categories:['design','content','software'], kind:'directory', free:'yes', freeNote:'创建账号、项目页和上传内容免费；出售内容时会涉及自选平台分成及支付费用。', quality:'A', qualityReason:'独立游戏、漫画、音乐和数字素材的真实作品页。', rulesUrl:'https://itch.io/docs/creators/getting-started', notes:'仅用于本人创作且实际可展示或下载的项目；新页面默认私有，需完成内容后改为公开。' }),

  channel({ id:'dev', name:'DEV Community', domain:'dev.to', submitUrl:'https://dev.to/new', categories:['developer','software','ai','education'], kind:'article', free:'yes', freeNote:'账号可免费发布社区文章。', quality:'B', qualityReason:'原创技术文章可在正文语境中为读者提供有用链接。', rulesUrl:'https://dev.to/terms', notes:'默认关闭：DEV 禁止主要为了推广或获取反向链接而写的内容。仅适合由人工主导的实质性技术文章。', articleRequired:true, enabled:false }),
  channel({ id:'hashnode', name:'Hashnode', domain:'hashnode.com', submitUrl:'https://hashnode.com/onboard', categories:['developer','software','ai','education'], kind:'article', free:'yes', freeNote:'Hashnode 子域名上的技术出版物可免费建立；部分自定义域名功能需要 Pro。', quality:'B', qualityReason:'实质性教程或产品说明可服务技术读者。', rulesUrl:'https://hashnode.com/code-of-conduct', notes:'普通网页发布与 API 接入不同；2026-05 起文章写入 API 要求目标出版物订阅 Hashnode Pro，本工具当前不接入付费写入。只做人工主导的技术知识分享；平台禁止 automated or bulk posting 和 SEO abuse。AI 辅助稿须人工审核，不能作为无人值守发布渠道。公开文章可能位于 hashnode.dev 子域名。', articleRequired:true, allowedHosts:['hashnode.com','hashnode.dev'] }),
  channel({ id:'medium', name:'Medium', domain:'medium.com', submitUrl:'https://medium.com/new-story', categories:['content','education','business','design','software','ai','finance'], kind:'article', free:'conditional', freeNote:'免费账号可以发布文章；读者能否免费阅读取决于文章的付费墙设置。', quality:'B', qualityReason:'有实质内容的原创文章可以服务目标读者。', rulesUrl:'https://help.medium.com/hc/en-us/articles/213477928-Medium-Rules', notes:'默认关闭：Medium 禁止自动、系统化或程序化注册与发文，禁止主要为外部引流或搜索排名写稿。官方已停止发放新 API 令牌及接入新集成；附带联盟链接须披露，加密内容另受专项规则约束。AI 审核通过不等于可以自动发布。', articleRequired:true, enabled:false, checkedAt:'2026-10-07' }),
  channel({ id:'substack', name:'Substack', domain:'substack.com', submitUrl:'https://substack.com/start', categories:['content','education','business','design'], kind:'profile', free:'conditional', freeNote:'免费出版物可添加主页链接，但仍需完成出版物和受众设置。', quality:'B', qualityReason:'真实运营的出版物可为读者提供相关自有资源。', rulesUrl:'https://support.substack.com/hc/en-us/articles/360059181172-How-do-I-add-links-to-my-Substack-homepage', notes:'仅维护本人真实运营的出版物；不适合为外部引流或 SEO 新建出版物。按平台规则人工处理，不进行无人值守浏览器操作。', automation:'manual', allowedHosts:['substack.com'] }),
  channel({ id:'indie-hackers', name:'Indie Hackers', domain:'indiehackers.com', submitUrl:'https://www.indiehackers.com/products', categories:['business','software','ai','developer'], kind:'community', free:'unknown', freeNote:'产品目录提供“Add Your Product”，但该页面未明确当前账号或费用条件。', quality:'B', qualityReason:'创业者和产品社区，适合真实创作者及产品资料。', rulesUrl:'https://www.indiehackers.com/products', notes:'只做人工提交和真实参与；不得批量发帖。', allowedHosts:['indiehackers.com','www.indiehackers.com'] }),
  channel({ id:'show-hn', name:'Show HN', domain:'news.ycombinator.com', submitUrl:'https://news.ycombinator.com/submit', categories:['developer','software','ai','design'], kind:'community', free:'yes', freeNote:'社区提交免费，但发布权限可能取决于账号状态。', quality:'A', qualityReason:'本人制作且可直接体验的项目能获得技术社区的真实反馈。', rulesUrl:'https://news.ycombinator.com/showhn.html', notes:'只允许人工做一次性判断。项目必须可体验；不接受纯落地页、新闻通讯、拉票或例行版本更新。', emailRequired:false }),

  channel({ id:'behance', name:'Behance', domain:'behance.net', submitUrl:'https://www.behance.net/', categories:['design','content'], languages:['*'], kind:'profile', free:'yes', freeNote:'标准创意资料页提供网站网址字段。', quality:'A', qualityReason:'真实作品集上的网站链接对查看作品的访客有直接价值。', rulesUrl:'https://help.behance.net/hc/en-us/articles/360034538213-Guide-Fill-Out-Your-Profile', notes:'首次账号由本人注册后导入，自动注册尚未完成验收；浏览器流程只维护所有者自己的作品集；资料还要求填写所在地。', automation:'browser', allowedHosts:['behance.net','www.behance.net'] }),
  channel({ id:'artstation', name:'ArtStation', domain:'artstation.com', submitUrl:'https://www.artstation.com/', categories:['design','content'], languages:['*'], kind:'profile', free:'yes', freeNote:'艺术家可获得免费作品集网站，部分自定义功能收费。', quality:'A', qualityReason:'包含真实作品及个人网站链接的作品集与访客需求直接相关。', rulesUrl:'https://help.artstation.com/en/articles/16155273-what-s-the-difference-between-my-community-profile-and-my-website-why-are-there-2-profiles', notes:'首次账号由本人注册后导入，自动注册尚未完成验收；浏览器流程只维护所有者自己的艺术家资料；作品必须由该艺术家或工作室创作。', automation:'browser', allowedHosts:['artstation.com','www.artstation.com'] }),
  channel({ id:'gravatar', name:'Gravatar', domain:'gravatar.com', submitUrl:'https://gravatar.com/profile', categories:['general'], languages:['*'], kind:'profile', free:'yes', freeNote:'个人公开资料页和普通链接完全免费；首年免费自定义域名续费另计。', quality:'C', qualityReason:'统一身份和个人链接页对已在寻找该所有者的访客有用，但不构成编辑背书。', rulesUrl:'https://support.gravatar.com/your-profile/links/', notes:'资料页可添加本人有权维护的任意网站链接，无需先有外部出版物。仅维护本人或本人组织的真实资料；不得把账号主要用于 SEO、批量推广或误导性导流。普通链接不经过平台验证，公开资料默认可被搜索引擎索引。' }),
  channel({ id:'linktree', name:'Linktree', domain:'linktr.ee', submitUrl:'https://linktr.ee/register', categories:['general'], languages:['*'], kind:'profile', free:'yes', freeNote:'免费方案包含基础链接，免费页面可能显示广告。', quality:'C', qualityReason:'个人链接页对已经寻找该所有者的访客有用，但不构成编辑背书。', rulesUrl:'https://linktr.ee/s/terms', notes:'可新建真实品牌或创作者链接页，并可按条款展示已披露的联盟链接；无需先有外部出版物。不得由机器人批量建号、运营多个规避限制的账号，或只为制造链接而新建页面。' }),

  channel({ id:'clutch', name:'Clutch', domain:'clutch.co', submitUrl:'https://clutch.co/get-listed', categories:['business','design','developer','software'], kind:'directory', free:'yes', freeNote:'服务商基础公司资料页免费，另有付费升级。', quality:'A', qualityReason:'经审核的代理或服务公司资料包含网站和服务详情。', rulesUrl:'https://help.clutch.co/en/knowledge/get-listed-on-clutch', notes:'仅用于有真实客户服务的公司；公开前需经过审核。', allowedHosts:['clutch.co','www.clutch.co'] }),
  channel({ id:'wellfound', name:'Wellfound', domain:'wellfound.com', submitUrl:'https://wellfound.com/onboarding/recruit', categories:['business','software','ai','developer'], kind:'profile', free:'yes', freeNote:'招聘公司的基础公司资料页免费。', quality:'B', qualityReason:'真实初创公司的资料对求职者和潜在合作方有用。', rulesUrl:'https://help.wellfound.com/article/1075-how-do-i-recruit-with-wellfound-for-free', notes:'仅适用于真实初创公司或雇主；需要个人登录并完成公司引导。' }),

  channel({ id:'google-business', name:'Google 商家资料', domain:'business.google.com', submitUrl:'https://business.google.com/add', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'符合资格的商家可以免费添加或认领资料。', quality:'A', qualityReason:'经验证的实体或上门服务商家资料能向本地顾客展示官网、营业时间和联系方式。', rulesUrl:'https://support.google.com/business/answer/13763036?hl=zh-Hans', notes:'仅限营业时间内与顾客面对面接触的实体店或上门服务商家；纯线上业务、引流公司和无权代表的地点不符合资格。', allowedHosts:['business.google.com','support.google.com'] }),
  channel({ id:'bing-places', name:'Bing Places for Business', domain:'bing.com', submitUrl:'https://www.bing.com/forbusiness/', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'商家可免费添加、认领并完善 Bing 资料。', quality:'B', qualityReason:'经验证的本地商家资料可展示官网、营业时间、服务和联系信息。', rulesUrl:'https://www.bing.com/forbusiness/', notes:'仅用于真实商家；需提供有效地址并通过地址、电话或邮箱验证，部分商家可在搜索结果中隐藏地址。', allowedHosts:['bing.com','www.bing.com','bingplaces.com','www.bingplaces.com'] }),
  channel({ id:'apple-business', name:'Apple Business', domain:'business.apple.com', submitUrl:'https://business.apple.com/', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'Apple Business 的基础服务免费，额外存储和 AppleCare 等可选服务收费。', quality:'A', qualityReason:'经验证的公司和地点资料可在 Apple 地图等应用中展示品牌、网址和关键资料。', rulesUrl:'https://www.apple.com/newsroom/2026/03/introducing-apple-business-a-new-all-in-one-platform-for-businesses-of-all-sizes/', notes:'需使用 Apple 账号注册并验证真实公司或组织；服务和功能可用性因国家或地区而异。' }),
  channel({ id:'yelp-business', name:'Yelp for Business', domain:'yelp.com', submitUrl:'https://biz.yelp.com/claim', categories:['business','general'], languages:['*'], kind:'profile', free:'yes', freeNote:'认领和维护基础商家页面完全免费，广告及部分增强功能另行付费。', quality:'B', qualityReason:'真实本地商家页面可向顾客展示官网、营业信息和顾客评价。', rulesUrl:'https://www.yelp-support.com/article/What-is-a-claimed-business?l=en_US', notes:'仅添加或认领本人有权管理的真实商家；需完成验证，并保持网址、地址、电话和营业时间准确。', allowedHosts:['yelp.com','www.yelp.com','biz.yelp.com','www.yelp-support.com'] }),
  channel({id:'uneed',name:'Uneed',domain:'uneed.best',submitUrl:'https://www.uneed.best/submit-a-tool',categories:['software','ai','developer','design','business'],kind:'directory',free:'conditional',freeNote:'有免费排队；需在控制台另行选择排期，队列满时可能暂停。免费刊登的保留与链接属性受平台条件影响。',quality:'B',qualityReason:'真实科技产品可以获得发现机会；排期、审核和留存条件单独核对。',rulesUrl:'https://www.uneed.best/how-it-works',notes:'提交产品资料不等于已排期。只提交真实可用产品，不生成虚假投票；不承诺当月发布或永久保留。',allowedHosts:['uneed.best','www.uneed.best'],checkedAt:'2026-09-28'}),
  channel({id:'betalist',name:'BetaList',domain:'betalist.com',submitUrl:'https://betalist.com/submit',categories:['software','ai','developer','business'],kind:'directory',free:'paid',freeNote:'官方 FAQ 明确所有提交目前收费，不再提供免费提交。',quality:'B',qualityReason:'适合未发布或近期发布的真实科技初创产品，仍需编辑审核。',rulesUrl:'https://betalist.com/support',notes:'需要独立域名与明确产品价值。不会进入免费自动计划；费用和资格必须在平台确认，本工具不代付。',checkedAt:'2026-09-28'}),
  channel({id:'wordpress-plugins',name:'WordPress.org Plugins',domain:'wordpress.org',submitUrl:'https://wordpress.org/plugins/developers/add/',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方提供插件提交入口；本轮资料未单独确认刊登费用字段，请在提交前核对。',quality:'A',qualityReason:'真实 WordPress 插件的分发页能为使用者提供功能、维护与项目资料。',rulesUrl:'https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/',notes:'必须有完整可用且许可合规的插件；不能只是推广壳。登录后上传，接受人工审核；不得把普通网站网址当成插件资格。',checkedAt:'2026-09-28'}),
  channel({id:'drupal',name:'Drupal.org Projects',domain:'drupal.org',submitUrl:'https://www.drupal.org/project/add',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方提供项目创建步骤；费用未单独核实。',quality:'A',qualityReason:'适合真实 Drupal 模块、主题和相关代码项目。',rulesUrl:'https://www.drupal.org/docs/develop/managing-a-drupalorg-theme-module-or-distribution-project/creating-a-new-project/how-to-create-a-new-project',notes:'需要实际代码与后续维护；遵守项目广告规则，不创建空项目或纯推广页面。',allowedHosts:['drupal.org','www.drupal.org'],checkedAt:'2026-09-28'}),
  channel({id:'packagist',name:'Packagist',domain:'packagist.org',submitUrl:'https://packagist.org/packages/submit',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'公开包有官方提交入口；此处不把私有托管订阅费用与公开仓库条件混记，提交前确认。',quality:'A',qualityReason:'真实 Composer 包的主页、说明和仓库信息服务 PHP 开发者。',rulesUrl:'https://packagist.org/about',notes:'需要可安装的真实项目和仓库根目录 composer.json。验证包名、许可及分发权；不提交没有软件功能的外链占位包。',checkedAt:'2026-09-28'}),
  channel({id:'pub-dev',name:'pub.dev',domain:'pub.dev',submitUrl:'https://pub.dev/',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方文档提供 Dart 包发布流程；费用未单独核实。',quality:'A',qualityReason:'真实 Dart/Flutter 包的版本、文档和项目网址对使用者有直接价值。',rulesUrl:'https://dart.dev/tools/pub/publishing',notes:'需要 Google 身份、可用包、LICENSE 与分发权；使用 dart pub publish。已发布版本通常不能撤下，需本人确认制品后发布。',checkedAt:'2026-09-28'}),
  channel({id:'rubygems',name:'RubyGems',domain:'rubygems.org',submitUrl:'https://rubygems.org/sign_up',categories:['developer','software'],languages:['*'],kind:'directory',free:'unknown',freeNote:'官方说明了 gem 发布与账号流程；费用与当前账号安全要求需在发布前确认。',quality:'A',qualityReason:'真实 Ruby gem 的项目主页与说明可帮助开发者使用和维护软件。',rulesUrl:'https://guides.rubygems.org/publishing/',notes:'必须有可安装的真实 gem、唯一包名及维护权限。使用正式包发布流程，不创建推广占位包。',checkedAt:'2026-09-28'}),
  channel({id:'blogger',name:'Blogger',domain:'blogspot.com',submitUrl:'https://www.blogger.com/',categories:['content','education','business','design','finance','ai','developer','general'],languages:['*'],kind:'article',free:'conditional',freeNote:'使用已连接账号下的既有博客发布文字；不购买自定义域名、模板或付费服务。需一次Google授权并绑定博客。',quality:'C',qualityReason:'适合持续经营的原创出版物；自建文章页面不等于第三方编辑推荐。',rulesUrl:'https://www.blogger.com/content-policy',evidenceSources:[{url:'https://www.blogger.com/content-policy',kind:'content_policy',appliesTo:'blogger',applicability:'verified'}],notes:'需在账号页连接Google桌面OAuth并为网站绑定本人博客，之后通过Blogger官方API保存草稿、发布并公开核验。仅用于本人真实运营且具有独立价值的出版物；不得建立重复促销或垃圾博客。金融稿件保留事实与风险核对，清楚披露作者和商业关系，回链带nofollow。授权失效时先推进其他可执行渠道，不复制浏览器登录态或自动注册Google身份。',automation:'api',emailRequired:false,articleRequired:true,allowedHosts:['blogspot.com','blogger.com','www.blogger.com'],checkedAt:'2026-10-04'}),
  channel({id:'hackernoon',name:'HackerNoon',domain:'hackernoon.com',submitUrl:'https://app.hackernoon.com/',categories:['developer','software','ai','business','finance','education'],kind:'article',free:'conditional',freeNote:'个人与品牌发布方式不同，品牌免费额度和后续收费需在账号内确认；不能当成无限免费投稿。',quality:'B',qualityReason:'技术文章可服务 AI、区块链与软件读者，受编辑审核与链接规则约束。',rulesUrl:'https://help.hackernoon.com/backlinks-guideline',notes:'只提交有深度的真实技术内容，品牌故事使用品牌身份。商业关系明确披露；遵守来源多样性和链接密度要求，不在通过审核后偷换推广链接。先由本人核对稿件。',articleRequired:true,allowedHosts:['hackernoon.com','app.hackernoon.com'],checkedAt:'2026-09-28'}),
  channel({id:'paragraph',name:'Paragraph',domain:'paragraph.com',submitUrl:'https://paragraph.com/',categories:['content','education','business','developer','ai','finance'],languages:['*'],kind:'article',free:'yes',freeNote:'免费方案提供文章 API；首次连接本人出版物的 API key，20 次请求/分钟。本工具仅网页发布，始终关闭邮件群发。',quality:'C',qualityReason:'本人原创出版物的公开全文与相关引用；不代表第三方编辑背书。',rulesUrl:'https://paragraph.com/content-guidelines',evidenceSources:[{url:'https://paragraph.com/content-guidelines',kind:'content_policy',appliesTo:'paragraph',applicability:'verified'}],notes:'原 Mirror 已迁移至 Paragraph，旧文章链接跳转到本平台，按同一来源管理。平台可通过钱包、邮箱或 Farcaster 登录，本工具仍使用出版物 API key，钱包连接不是自动发布授权。连接本人真实原创出版物并选择关联网站，后续自动生成、独立核对、保存草稿并发布网页；不向订阅者发送邮件。禁止以第三方促销、联盟佣金、获客或销售导流为主要目的的出版物；只允许实质原创内容中相关且明确披露的附带商业链接。AI 同时核对出版物用途与当前稿件，不因持有 API key 自动推定内容符合规则。',articleRequired:true,emailRequired:false,accountRequired:true,automation:'api',allowedHosts:['paragraph.com'],checkedAt:'2026-10-07'}),

  // 原创全文出版物和真实品牌资料。
  channel({id:'leaflet',name:'Leaflet',domain:'leaflet.pub',submitUrl:'https://leaflet.pub/',categories:['general','content','education','finance','business','developer','ai','software'],languages:['*'],kind:'article',free:'yes',freeNote:'使用本人已有的 Bluesky 账号和应用专用密码，通过 bsky.social PDS 发布公开全文；Leaflet 账号与本机已有 Bluesky 渠道连接分别保存、分别绑定。',quality:'C',qualityReason:'ATProto 上的原创公开全文可供读者独立阅读；自有作者页面不代表第三方推荐，也不保证搜索收录、权重或流量。',rulesUrl:'https://leaflet.pub/legal',evidenceSources:[{url:'https://github.com/hyperlink-academy/leaflet/blob/a583a135338740205e38e003d9213533f742edb6/app/legal/terms.mdx',kind:'content_policy',appliesTo:'leaflet',applicability:'verified'},{url:'https://github.com/hyperlink-academy/leaflet/blob/a583a135338740205e38e003d9213533f742edb6/lexicons/site/standard/document.json',kind:'api',appliesTo:'leaflet',applicability:'verified'},{url:'https://about.leaflet.pub/',kind:'product_guidance',appliesTo:'leaflet',applicability:'verified'}],notes:'只连接本人控制且托管在 bsky.social 的 Bluesky/ATProto 账号，为 Leaflet 单独保存应用专用密码和网站绑定；不复用其他 Bluesky 渠道的账号记录或凭据。仅发布与本站选题及受众匹配、有独立阅读价值的原创全文，并如实披露 AI 辅助、推广发布角色与商业关系。现有通用条款没有一概禁止加密、联盟推广、AI 辅助或 API 发布，但也不构成平台对这些主题的背书或专门许可；按完整条款、已授权作者身份、可取得的公开页和单篇稿件独立审核，拒绝垃圾推广、虚假身份、侵权、收益承诺和纯导流内容。DID、rkey、全文哈希、时间与公开地址在写入前保存；收到 creating 回执后只读取原记录核对，不换身份、不换 rkey、不重发。外部 PDS 写入的公共页可能因最多约一小时的索引刷新暂时 404，只做有限次数延后核验。适配器已接入待本人授权、真实发布及合规博客验收；当前保持停用，不把模拟测试当作真实可用。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['leaflet.pub'],enabled:false,checkedAt:'2026-10-08'}),
  channel({id:'wordpress-com',name:'WordPress.com',domain:'wordpress.com',submitUrl:'https://wordpress.com/start/',categories:['content','education','finance','business'],languages:['*'],kind:'article',free:'conditional',freeNote:'免费托管计划提供 wordpress.com 子域名和文章；自定义域名、去广告等功能另收费。首次需本人创建并公开博客、完成 OAuth 授权。',quality:'B',qualityReason:'适合持续更新的独立原创科普博客；自有出版物不等于第三方推荐，不保证收录、权重或流量。',rulesUrl:'https://wordpress.com/support/monetize-your-site/',evidenceSources:[{url:'https://developer.wordpress.com/docs/api/getting-started/',kind:'api',appliesTo:'wordpress-com',applicability:'verified'},{url:'https://wordpress.com/support/monetize-your-site/',kind:'content_policy',appliesTo:'wordpress-com',applicability:'verified'},{url:'https://wordpress.com/support/user-guidelines/',kind:'content_policy',appliesTo:'wordpress-com',applicability:'verified'}],notes:'只连接本人 OAuth 授权列表中可管理、可公开发布的 WordPress.com 托管博客；不接自建 WordPress、Jetpack 站点或自定义域本轮扩展。原创有用内容必须是出版物与单篇文章的主要目的；可以附带相关联盟链接，但禁止以外链、SEO 或联盟引流为主的站点，也不发快速致富、赌博、多层分销、诈骗或不可靠商家推广。返佣、AI 辅助及当前推广发布角色必须准确披露；不复制站群旧稿或制作跳转页。稳定 slug 和原稿回执会在 POST 前保存；结果不明只读取原博客核对，不重发。适配器已接入待实发验收；当前保持停用，不把模拟测试当作真实可用或已完成用户授权。',emailRequired:false,accountRequired:true,articleRequired:true,automation:'api',allowedHosts:['wordpress.com'],enabled:false,requirements:['publication'],checkedAt:'2026-10-08'}),
  channel({id:'ghost-pro',name:'Ghost(Pro)',domain:'ghost.io',submitUrl:'https://account.ghost.org/',categories:['content','education','finance','business'],languages:['*'],kind:'article',free:'paid',freeNote:'托管出版物为付费订阅；免费试用不等于永久免费，请先核对当前方案。',quality:'B',qualityReason:'适合长期运营的金融知识出版物；不会直接获得 ghost.org 主域的权威或受众。',rulesUrl:'https://ghost.org/terms/',notes:'使用本人持续运营的原创出版物；仅给主动订阅者发信，禁止未经允许的促销和欺诈。不自动购买方案。本条目接回 ghost.io 子域名的公开文章；自定义域名需单独建立人工渠道。不要把自有网站文章记作新的外部来源。本客户端尚未接入 Ghost 发布 API，不能因平台提供 API 就称为已自动化。',articleRequired:true,requirements:['publication'],allowedHosts:['ghost.org','account.ghost.org','ghost.io'],checkedAt:'2026-09-30'}),
  channel({id:'tumblr',name:'Tumblr',domain:'tumblr.com',submitUrl:'https://www.tumblr.com/new/text',categories:['content','education','finance','design'],languages:['*'],kind:'article',free:'unknown',freeNote:'文章入口已核对；付费功能和账号条件以当前平台页面为准。',quality:'C',qualityReason:'可用于原创图解和知识分享；受众适配及具体页面公开性需另核验。',rulesUrl:'https://www.tumblr.com/policy/user-guidelines',notes:'仅供人工操作：禁止自动、系统化或程序化注册及发帖，禁止以联盟营销为主要目的的博客。适用于有独立阅读价值的教育内容，不能批量复制站群稿或堆返佣链接。返佣主导的落地页不适合此渠道。',articleRequired:true,requirements:['publication'],allowedHosts:['tumblr.com','www.tumblr.com'],checkedAt:'2026-09-30'}),
  channel({id:'linkedin-articles',name:'LinkedIn 文章',domain:'linkedin.com',submitUrl:'https://www.linkedin.com/article/new/',categories:['business','education','finance','content'],languages:['*'],kind:'article',free:'conditional',freeNote:'成员及有权限的主页管理员可发布文章；需要真实身份和正常账号。',quality:'B',qualityReason:'适合面向专业读者的研究或经验；文章公开不代表搜索收录。',rulesUrl:'https://www.linkedin.com/help/linkedin/answer/a519782',notes:'人工发布本人专业知识与原创研究，可以提供相关参考链接。文章政策不接受产品、服务或活动广告；纯交易所推广、邀请码合集不适合。不得虚构从业资历、自动批量加好友或发私信。',articleRequired:true,requirements:['publication'],allowedHosts:['linkedin.com','www.linkedin.com'],checkedAt:'2026-09-30'}),
  channel({id:'youtube-channel',name:'YouTube 频道资料',domain:'youtube.com',submitUrl:'https://studio.youtube.com/',categories:['content','education','finance'],languages:['*'],kind:'profile',free:'conditional',freeNote:'本人频道可在资料中管理网站链接；需要已有正常运营的频道。',quality:'B',qualityReason:'为原创视频观众提供作者网站；资料链接与正文外链、搜索收录分别核验。',rulesUrl:'https://support.google.com/youtube/answer/9054257',notes:'维护真实运营频道的资料链接，入口在 YouTube Studio → 自定义 → 个人资料。联盟内容本身不被一概禁止，但专门账号过量发布联盟内容可能构成垃圾内容。不得夸大收益、引向诈骗页面或只建空频道挂链接；客户端不自动上传视频。',requirements:['publication'],allowedHosts:['youtube.com','www.youtube.com','studio.youtube.com'],checkedAt:'2026-09-30'}),
  channel({id:'x-profile',name:'X 品牌资料',domain:'x.com',submitUrl:'https://x.com/settings/profile',categories:['content','education','finance','business'],languages:['*'],kind:'profile',free:'unknown',freeNote:'资料页提供网站字段；功能、账号验证和地区可用性需在账号内核对。',quality:'C',qualityReason:'方便真实读者找到运营者网站；不承诺链接传递权重或自然流量。',rulesUrl:'https://help.x.com/en/rules-and-policies/authenticity',notes:'人工维护本人或真实品牌资料的网站字段。明确独立运营与商业关系，不冒充交易所。禁止重复灌链接、批量无关回复、协同刷互动或为绕过封禁换号；个人资料链接可能经过平台跳转，须另外验证公开结果。',requirements:['publication'],allowedHosts:['x.com','www.x.com','twitter.com'],checkedAt:'2026-09-30'}),
  channel({id:'linkedin-company',name:'LinkedIn 公司主页',domain:'linkedin.com',submitUrl:'https://www.linkedin.com/company/setup/new/',categories:['business','finance','content','education'],languages:['*'],kind:'profile',free:'yes',freeNote:'真实组织可免费创建公司主页；高级主页、广告和招聘功能另行收费。',quality:'A',qualityReason:'正式品牌资料可展示网站、业务说明与组织动态；是否验证和搜索展示由平台决定。',rulesUrl:'https://www.linkedin.com/help/linkedin/answer/a545752',notes:'仅由有权代表真实组织的人创建或认领主页，先检查是否已有页面。管理员个人账号必须使用真实姓名，并满足账号时长、连接或工作邮箱验证等反垃圾条件。网站和组织信息保持一致；不创建多个近似页面，不批量邀请、不冒充交易所或虚构雇佣关系。',requirements:['business'],allowedHosts:['linkedin.com','www.linkedin.com'],checkedAt:'2026-09-30'}),
  channel({id:'crunchbase-company',name:'Crunchbase 公司资料',domain:'crunchbase.com',submitUrl:'https://www.crunchbase.com/add-new',categories:['business','finance','software','ai'],languages:['en'],kind:'directory',free:'yes',freeNote:'免费注册并完成 Google 或 LinkedIn 社交认证后，可新增或编辑公司资料。',quality:'A',qualityReason:'适合真实科技公司、初创企业和投资生态参与者；资料页可列官网与社交链接。',rulesUrl:'https://support.crunchbase.com/hc/en-us/articles/115011823988-How-do-I-create-a-Crunchbase-profile',notes:'只添加科技或初创生态中的真实组织，创建前先搜索去重。填写可核实的成立时间、所在地、创始人和业务说明，不为普通内容站虚构融资、团队或公司身份。部分字段可能要求工作关系验证或由平台锁定；资料公开不代表 Crunchbase 背书。',requirements:['business'],allowedHosts:['crunchbase.com','www.crunchbase.com','support.crunchbase.com'],checkedAt:'2026-09-30'}),
  channel({id:'trustpilot-business',name:'Trustpilot 商家资料',domain:'trustpilot.com',submitUrl:'https://business.trustpilot.com/signup',categories:['business','finance'],languages:['*'],kind:'profile',free:'yes',freeNote:'拥有有效网站的真实商家可免费认领并管理基础资料；高级工具另行付费。',quality:'B',qualityReason:'经认领的公开商家资料可展示官网和真实顾客反馈；评分与链接价值均不作保证。',rulesUrl:'https://help.trustpilot.com/s/article/Claim-your-business-profile?language=en_US',notes:'仅认领本人有权管理、且提供真实产品或服务的网站；域名邮箱不匹配时需另做域名验证。不得制造、购买或诱导好评，不筛选只邀请满意顾客，不用奖励换评价。页面可能在认领前已存在，负面评价不会因付费而删除。',requirements:['business'],allowedHosts:['trustpilot.com','www.trustpilot.com','business.trustpilot.com','help.trustpilot.com'],checkedAt:'2026-09-30'}),
  channel({id:'bluesky-domain',name:'Bluesky 域名身份（仅参考）',domain:'bsky.app',submitUrl:'https://bsky.app/',categories:['content','education','finance','business'],languages:['*'],kind:'profile',free:'yes',freeNote:'基础账号和把已有域名设为用户名不收平台费用；域名本身需由用户持有。',quality:'B',qualityReason:'域名用户名把真实网站与社交身份双向关联，适合持续运营的作者或品牌。',rulesUrl:'https://bsky.social/about/blog/4-28-2023-domain-handle-tutorial',notes:'本工具中停用：匿名 HTML 未验证到可核验的外部直链，域名身份和可见网址文字不计为有效外链来源。仅为本人网站设置 DNS TXT 或 well-known 验证并维护真实账号。商业、赞助或联盟内容须清楚披露；禁止金融骗局、重复灌链接、批量账号、刷互动和封禁规避。域名用户名属于身份验证线索，不等同于平台认证徽章或搜索收录。',requirements:['publication'],enabled:false,allowedHosts:['bsky.app','bsky.social','www.bsky.social'],checkedAt:'2026-09-30'}),
  channel({id:'beehiiv',name:'beehiiv 出版物',domain:'beehiiv.com',submitUrl:'https://app.beehiiv.com/',categories:['content','education','finance','business'],languages:['*'],kind:'article',free:'conditional',freeNote:'Launch 免费方案可托管公开出版物；自定义页面、部分建站和增长功能需要付费。',quality:'B',qualityReason:'适合持续经营的原创通讯和公开文章，并可在导航中添加本人网站链接。',rulesUrl:'https://www.beehiiv.com/aup',notes:'只适合以原创编辑内容为主的出版物。平台允许合规的加密、区块链和 DeFi 教育，但禁止推广不受监管的金融服务、空投、推荐赚钱计划、误导性收益以及以联盟转化或导流为主要目的的内容；联盟关系必须披露。仅向明确订阅者发信，不导入购买名单，禁止缺乏实质人工投入的全 AI 出版物，也不创建 AI 内容农场或批量账号；发布前需由作者贡献原创判断并实质编辑。',articleRequired:true,requirements:['publication'],allowedHosts:['beehiiv.com','www.beehiiv.com','app.beehiiv.com'],checkedAt:'2026-09-30'}),
  channel({id:'kit-newsletter',name:'Kit 创作者通讯',domain:'kit.com',submitUrl:'https://app.kit.com/',categories:['content','education','finance','business'],languages:['*'],kind:'article',free:'conditional',freeNote:'可建立免费通讯和公开 Newsletter Site；高级自动化、规模和商业功能按方案收费。',quality:'B',qualityReason:'持续运营的创作者主页可承载原创通讯、文章和本人网站链接。',rulesUrl:'https://help.kit.com/en/articles/4881296-what-type-of-affiliate-marketing-is-and-isn-t-allowed-at-kit',notes:'必须先有联盟营销之外的真实业务和原创内容；官方参考比例为约 70–80% 自有内容、20–30% 相关联盟内容，并要求清楚说明外链去向。禁止纯联盟邮件、垃圾群发、快速致富及受限主题的联盟链接；官方特别列出教育、贷款、在线药房和快速致富软件。交易/加密教育另须遵守资金、收益承诺等限制，不能把内容类别视为联盟链接许可。只向自愿订阅者发送；加密或金融内容还须逐项满足目的地、地区与披露要求。',articleRequired:true,requirements:['publication'],allowedHosts:['kit.com','www.kit.com','app.kit.com','help.kit.com'],checkedAt:'2026-09-30'}),
  channel({id:'vocus',name:'方格子 vocus（人工原创）',domain:'vocus.cc',submitUrl:'https://vocus.cc/become_creator',categories:['content','education','finance','business'],languages:['zh'],kind:'article',free:'yes',freeNote:'创建沙龙和发布免费公开原创文章无需付费；订阅、商品与其他变现功能条件另计。',quality:'B',qualityReason:'面向繁体中文读者的原创出版平台，支持文章超链接、个人网站和投资理财提示。',rulesUrl:'https://vocus.cc/article/67d00720fd8978000179128c',notes:'本工具中停用：平台反对 AI 内容显著多于作者原创观点、将全 AI 内容冒充原创，并鼓励标注 AI 辅助。此渠道需人工原创，不使用本工具生成整篇稿件。人工发布本人拥有权利、言之有物的繁体中文内容；引用资料须标明来源。涉及投资理财必须启用平台提示，并另外加入清晰风险与联盟披露。官方资料确认支持公开文章和外部超链接，但不代表平台为加密返佣推广背书；不得复制站群稿、伪装独立体验或堆放邀请码。',articleRequired:true,requirements:['publication'],enabled:false,allowedHosts:['vocus.cc','www.vocus.cc'],checkedAt:'2026-09-30'}),
  channel({id:'flipboard-publisher',name:'Flipboard 出版者资料',domain:'flipboard.com',submitUrl:'https://flipboard.com/',categories:['content','education','finance','business'],languages:['*'],kind:'profile',free:'unknown',freeNote:'可以创建资料与 Magazine；官方指南未在本轮明确基础账号费用，RSS 出版资格需另行审核。',quality:'B',qualityReason:'合格出版者可把原创网站内容导向原始来源；展示、推荐和流量均无保证。',rulesUrl:'https://about.flipboard.com/rss-guidelines/',notes:'本人或组织必须持续发布原创内容，使用真实署名和可验证联系方式，并拥有提交的 RSS 与网站。先以资料和 Magazine 人工维护；RSS 接入需满足出版者资格和内容质量。补偿、赠品与商业关系须披露，禁止未获批准的促销、重复高频发布、误导标题和跳转。',requirements:['publication'],allowedHosts:['flipboard.com','www.flipboard.com','about.flipboard.com'],checkedAt:'2026-09-30'}),
  channel({id:'tradingview-profile',name:'TradingView 资料签名',domain:'tradingview.com',submitUrl:'https://www.tradingview.com/',categories:['finance','education'],languages:['*'],kind:'profile',free:'paid',freeNote:'任何付费方案可在状态栏放允许的推广与外链；签名需 Premium 或更高方案。价格和地区方案以购买页为准。',quality:'B',qualityReason:'适合持续发布原创市场分析的真实作者；资料链接不能替代有价值的观点或脚本。',rulesUrl:'https://www.tradingview.com/support/solutions/43000472770-am-i-allowed-to-include-links-to-3rd-party-sites-in-my-signature/',notes:'真实分析作者可在付费方案允许的状态栏或 Premium 及以上的签名放置相关官网。图表、标题、观点正文、评论不得放广告、站外链接、交易所邀请码或导流提示，也不得引导读者去看签名；状态栏与签名按官方许可另行核对。禁止收益保证、虚假业绩和冒充经纪商或交易所；客户端不购买方案。',requirements:['publication'],allowedHosts:['tradingview.com','www.tradingview.com'],checkedAt:'2026-09-30'}),
  channel({id:'publish0x',name:'Publish0x（仅人工原创）',domain:'publish0x.com',submitUrl:'https://www.publish0x.com/become',categories:['finance','content','education'],languages:['*'],kind:'article',free:'conditional',freeNote:'本人项目的内容可免费发布，但作者资格需申请；代客户营销另有条件。',quality:'B',qualityReason:'有加密货币读者，适合有独立价值的原创分享；作者资格并非自动批准。',rulesUrl:'https://www.publish0x.com/page/rules',notes:'本工具中停用：平台禁止 AI 写稿及任何自动发布，只允许本人纯人工原创。允许适度附带推荐链接，但禁止 SEO 外链文、引流落地页、内容搬运和多账号。不能用 AI 审核代替平台对人工创作的要求；保留规则记录供人工评估。',articleRequired:true,requirements:['publication'],enabled:false,allowedHosts:['publish0x.com','www.publish0x.com'],checkedAt:'2026-09-30'}),
  channel({id:'pinterest',name:'Pinterest（金融推广需预审）',domain:'pinterest.com',submitUrl:'https://www.pinterest.com/pin-creation-tool/',categories:['finance','content','education','design'],languages:['*'],kind:'profile',free:'unknown',freeNote:'普通内容与商业推广有不同条件；金融推广许可及费用需另行核对。',quality:'C',qualityReason:'适合原创图解，但联盟金融内容还有额外资格，不能视为通用返佣发布入口。',rulesUrl:'https://policy.pinterest.com/en/commercial-and-branded-content-guidelines',notes:'本工具中停用：联盟内容必须遵循商业合作及广告规则；加密产品服务受限，允许的交易所及钱包广告仍需资质、地区合规与平台预批准。不能把普通 Pin 当作规避金融推广限制的方法。禁止批量重复联盟 Pin、假账号和互刷。',requirements:['publication'],enabled:false,allowedHosts:['pinterest.com','www.pinterest.com'],checkedAt:'2026-09-30'}),

];

const related: Partial<Record<Category, Category[]>> = {
  ai:['software','developer'], software:['ai','developer','business'], developer:['software','ai','education'],
  design:['content','software'], business:['software','content'], content:['design','education','business'],
  education:['content','developer'], finance:['business'],
};

const categoryLabel: Record<Category, string> = {
  software:'软件', ai:'人工智能', developer:'开发者', design:'设计', business:'商业',
  content:'内容', education:'教育', finance:'金融', general:'综合',
};

export function matchChannels(site: Site, channels: Channel[]): Array<{channel: Channel; score: number; reason: string}> {
  return channels.flatMap(channel=>{
    const candidate=channelDiscoveryFor(site,channel);
    // Discovery and planning share relevance; real asset requirements remain hard.
    if(!candidate.canQueue||candidate.status==='needs_preparation')return [];
    return [{channel,score:candidate.score,reason:candidate.reason}];
  }).sort((a,b)=>b.score-a.score||a.channel.name.localeCompare(b.channel.name));
}
