import type { Category, Channel, Site } from '../shared/types.js';

const checkedAt = '2026-09-26';
type Entry = Pick<Channel, 'id'|'name'|'domain'|'submitUrl'|'categories'|'kind'|'free'|'freeNote'|'quality'|'qualityReason'|'rulesUrl'|'notes'> &
  Partial<Pick<Channel, 'languages'|'emailRequired'|'accountRequired'|'articleRequired'|'automation'|'allowedHosts'|'enabled'|'checkedAt'>>;

function channel(entry: Entry): Channel {
  return {
    url: `https://${entry.domain}/`,
    languages: ['en'],
    emailRequired: true,
    accountRequired: true,
    articleRequired: false,
    automation: 'manual',
    allowedHosts: [entry.domain],
    enabled: true,
    checkedAt,
    ...entry,
  };
}

// A channel is a relevant audience and a legitimate profile, product, or article
// placement. Grades describe editorial fit, not domain authority or expected SEO value.
export const CHANNELS: Channel[] = [
  channel({ id:'product-hunt', name:'Product Hunt', domain:'producthunt.com', submitUrl:'https://www.producthunt.com/posts/new', categories:['software','ai','developer','design','business'], kind:'directory', free:'yes', freeNote:'Regular product launches are free; a personal account must meet posting access rules.', quality:'A', qualityReason:'Human-reviewed launch surface for usable digital products.', rulesUrl:'https://help.producthunt.com/en/articles/479557-how-to-post-a-product', notes:'One meaningful product launch; personal account, onboarding and account age rules apply. No vote solicitation.', allowedHosts:['producthunt.com','www.producthunt.com'] }),
  channel({ id:'alternativeto', name:'AlternativeTo', domain:'alternativeto.net', submitUrl:'https://alternativeto.net/', categories:['software','ai','developer','design'], kind:'directory', free:'yes', freeNote:'Self-submission is available; editorial approval is required.', quality:'A', qualityReason:'Software comparison listing with a review queue and an actual product URL.', rulesUrl:'https://alternativeto.net/faq/', notes:'Use “Suggest new application” after email verification; pending entries are not public.' }),
  channel({ id:'g2', name:'G2', domain:'g2.com', submitUrl:'https://sell.g2.com/create-a-profile', categories:['software','ai','developer','business'], kind:'directory', free:'yes', freeNote:'Claiming a product profile is free; paid vendor upgrades exist.', quality:'A', qualityReason:'Product-specific software review marketplace.', rulesUrl:'https://sell.g2.com/create-a-profile', notes:'List a real software product; eligibility and review are platform-controlled.', allowedHosts:['g2.com','sell.g2.com','my.g2.com'] }),
  channel({ id:'saashub', name:'SaaSHub', domain:'saashub.com', submitUrl:'https://www.saashub.com/services/submit', categories:['software','ai','developer','business'], kind:'directory', free:'unknown', freeNote:'A live product submission form exists; its listing price is not stated there.', quality:'B', qualityReason:'Relevant software discovery directory with product approval.', rulesUrl:'https://www.saashub.com/services/submit', notes:'Released English-language software with its own domain only; no waitlist, agency, or free-hosting subdomain. Verify fee before submission.', allowedHosts:['saashub.com','www.saashub.com'] }),
  channel({ id:'github', name:'GitHub', domain:'github.com', submitUrl:'https://github.com/settings/profile', categories:['developer','software','ai','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'Public personal profile and repository links are available on free accounts.', quality:'A', qualityReason:'A real maintainer profile or repository gives developer visitors useful context.', rulesUrl:'https://docs.github.com/en/account-and-profile/tutorials/personalize-your-profile', notes:'Browser-assisted edit of the owner’s profile only; no empty repositories or generic posts.', automation:'browser' }),
  channel({ id:'gitlab', name:'GitLab', domain:'gitlab.com', submitUrl:'https://gitlab.com/-/profile', categories:['developer','software','ai','education'], languages:['*'], kind:'profile', free:'yes', freeNote:'Profiles are included in GitLab Free.', quality:'A', qualityReason:'Relevant developer profile or active repository with public project context.', rulesUrl:'https://docs.gitlab.com/user/profile/', notes:'Browser-assisted edit of the owner’s profile only; public visibility varies by settings.', automation:'browser' }),
  channel({ id:'npm', name:'npm', domain:'npmjs.com', submitUrl:'https://www.npmjs.com/signup', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'Public npm packages can be published with an account.', quality:'A', qualityReason:'Package metadata is valuable to users of an actual JavaScript package.', rulesUrl:'https://docs.npmjs.com/creating-and-publishing-unscoped-public-packages/', notes:'Only a real installable package with documentation; account and 2FA/token requirements apply.', allowedHosts:['npmjs.com','www.npmjs.com'] }),
  channel({ id:'pypi', name:'PyPI', domain:'pypi.org', submitUrl:'https://pypi.org/account/register/', categories:['developer','software','ai'], kind:'directory', free:'yes', freeNote:'Public Python package uploads are available with an account.', quality:'A', qualityReason:'A project homepage link helps users of a genuine Python package.', rulesUrl:'https://packaging.python.org/en/latest/tutorials/packaging-projects/', notes:'Only a real Python package; project URLs belong in package metadata.' }),
  channel({ id:'sourceforge', name:'SourceForge', domain:'sourceforge.net', submitUrl:'https://sourceforge.net/p/add_project', categories:['developer','software'], kind:'directory', free:'yes', freeNote:'The public open-source project creation flow is free.', quality:'B', qualityReason:'Open-source project directory with project pages and download context.', rulesUrl:'https://sourceforge.net/p/forge/documentation/Create%20a%20New%20Project/', notes:'Only for genuine open-source software with a valid license.' }),
  channel({ id:'huggingface', name:'Hugging Face', domain:'huggingface.co', submitUrl:'https://huggingface.co/new', categories:['ai','developer','education'], kind:'profile', free:'conditional', freeNote:'Public repositories and static Spaces have free options; compute Spaces may require a plan.', quality:'A', qualityReason:'Model, dataset, or demo page is useful to an AI audience when the artifact exists.', rulesUrl:'https://huggingface.co/docs/hub/spaces-overview', notes:'Only for an actual model, dataset, or demo; avoid empty repositories.' }),
  channel({ id:'dev', name:'DEV Community', domain:'dev.to', submitUrl:'https://dev.to/new', categories:['developer','software','ai','education'], kind:'article', free:'yes', freeNote:'Community publishing is available with an account.', quality:'B', qualityReason:'Original technical writing can give readers a useful contextual link.', rulesUrl:'https://dev.to/terms', notes:'Disabled by default: DEV forbids content designed primarily for promotion or backlinks. Only a human-led substantive technical article may be appropriate.', articleRequired:true, enabled:false }),
  channel({ id:'hashnode', name:'Hashnode', domain:'hashnode.com', submitUrl:'https://hashnode.com/onboard', categories:['developer','software','ai','education'], kind:'article', free:'yes', freeNote:'A publication on a Hashnode subdomain is free; some custom-domain features require Pro.', quality:'B', qualityReason:'Technical publication can support substantial tutorials or product explanations.', rulesUrl:'https://hashnode.com/code-of-conduct', notes:'Original useful writing; publication URLs may live on hashnode.dev.', articleRequired:true, allowedHosts:['hashnode.com','hashnode.dev'] }),
  channel({ id:'medium', name:'Medium', domain:'medium.com', submitUrl:'https://medium.com/new-story', categories:['content','education','business','design','software','ai'], kind:'article', free:'conditional', freeNote:'Publishing is possible on a free account; reader access depends on story paywall settings.', quality:'B', qualityReason:'A substantive original article can serve readers beyond the destination link.', rulesUrl:'https://help.medium.com/hc/en-us/articles/213477928-Medium-Rules', notes:'Disabled by default: Medium forbids stories made mainly to boost external traffic or search rankings. Human author review required.', articleRequired:true, enabled:false }),
  channel({ id:'substack', name:'Substack', domain:'substack.com', submitUrl:'https://substack.com/start', categories:['content','education','business','design'], kind:'profile', free:'conditional', freeNote:'A free publication can add homepage links; publication and audience setup still required.', quality:'B', qualityReason:'A genuine publication can point readers to related owned resources.', rulesUrl:'https://support.substack.com/hc/en-us/articles/360059181172-How-do-I-add-links-to-my-Substack-homepage', notes:'Browser-assisted edit of an existing owner publication’s homepage links; public pages may use a subdomain.', automation:'browser', allowedHosts:['substack.com'] }),
  channel({ id:'indie-hackers', name:'Indie Hackers', domain:'indiehackers.com', submitUrl:'https://www.indiehackers.com/products', categories:['business','software','ai','developer'], kind:'community', free:'unknown', freeNote:'The product directory offers “Add Your Product”; current account or price terms are not explicit.', quality:'B', qualityReason:'Founder and product community, useful for an authentic maker profile.', rulesUrl:'https://www.indiehackers.com/products', notes:'Manual submission and participation; no mass posting to threads.', allowedHosts:['indiehackers.com','www.indiehackers.com'] }),
  channel({ id:'behance', name:'Behance', domain:'behance.net', submitUrl:'https://www.behance.net/', categories:['design','content'], languages:['*'], kind:'profile', free:'yes', freeNote:'A standard creative profile provides a website URL field.', quality:'A', qualityReason:'A portfolio link is directly useful to visitors viewing actual creative work.', rulesUrl:'https://help.behance.net/hc/en-us/articles/360034538213-Guide-Fill-Out-Your-Profile', notes:'Browser-assisted edit of an owner portfolio only. Location is required in the profile.', automation:'browser', allowedHosts:['behance.net','www.behance.net'] }),
  channel({ id:'artstation', name:'ArtStation', domain:'artstation.com', submitUrl:'https://www.artstation.com/', categories:['design','content'], languages:['*'], kind:'profile', free:'yes', freeNote:'Artists receive a free portfolio website; some customization is paid.', quality:'A', qualityReason:'Portfolio with real artwork and an external personal-site link is relevant to visitors.', rulesUrl:'https://help.artstation.com/en/articles/16155273-what-s-the-difference-between-my-community-profile-and-my-website-why-are-there-2-profiles', notes:'Browser-assisted edit of an owner artist profile only; only work created by the artist or studio.', automation:'browser', allowedHosts:['artstation.com','www.artstation.com'] }),
  channel({ id:'clutch', name:'Clutch', domain:'clutch.co', submitUrl:'https://clutch.co/get-listed', categories:['business','design','developer','software'], kind:'directory', free:'yes', freeNote:'A basic service-provider company profile is free; paid upgrades exist.', quality:'A', qualityReason:'Reviewed agency/service profile includes website and service details.', rulesUrl:'https://help.clutch.co/en/knowledge/get-listed-on-clutch', notes:'Only genuine client-service companies; review before publication.', allowedHosts:['clutch.co','www.clutch.co'] }),
  channel({ id:'wellfound', name:'Wellfound', domain:'wellfound.com', submitUrl:'https://wellfound.com/onboarding/recruit', categories:['business','software','ai','developer'], kind:'profile', free:'yes', freeNote:'Company profiles are complimentary for recruiting companies.', quality:'B', qualityReason:'Startup company profile is useful to candidates and potential collaborators.', rulesUrl:'https://help.wellfound.com/article/1075-how-do-i-recruit-with-wellfound-for-free', notes:'For an actual startup/employer; personal login and company onboarding required.' }),
  channel({ id:'show-hn', name:'Show HN', domain:'news.ycombinator.com', submitUrl:'https://news.ycombinator.com/submit', categories:['developer','software','ai','design'], kind:'community', free:'yes', freeNote:'Community submission is free, but access may depend on account standing.', quality:'A', qualityReason:'A personally built, usable project may attract direct technical feedback.', rulesUrl:'https://news.ycombinator.com/showhn.html', notes:'Manual, one-time human decision only. Must be something people can try; no landing pages, newsletters, vote solicitation, or routine release posts.' }),
  channel({ id:'linktree', name:'Linktree', domain:'linktr.ee', submitUrl:'https://linktr.ee/register', categories:['general'], languages:['*'], kind:'profile', free:'yes', freeNote:'The free plan includes basic links; free pages may display ads.', quality:'C', qualityReason:'A personal link hub is useful for visitors already seeking the owner, but provides no editorial endorsement.', rulesUrl:'https://linktr.ee/s/pricing', notes:'Manual review: only add to an existing owner brand/creator profile used by an actual audience. Do not create profiles solely to generate links.' }),
];

const related: Partial<Record<Category, Category[]>> = {
  ai:['software','developer'], software:['ai','developer','business'], developer:['software','ai','education'],
  design:['content','software'], business:['software','content'], content:['design','education','business'],
  education:['content','developer'], finance:['business'],
};

export function matchChannels(site: Site, channels: Channel[]): Array<{channel: Channel; score: number; reason: string}> {
  return channels.flatMap(channel => {
    if (!channel.enabled) return [];
    const direct = channel.categories.includes(site.category);
    const adjacent = !direct && (related[site.category] ?? []).some(category => channel.categories.includes(category));
    const general = channel.categories.includes('general');
    const relevance = direct ? 70 : adjacent ? 42 : general ? (site.category === 'general' ? 55 : 20) : 0;
    if (relevance < 35) return [];
    const language = site.language.toLowerCase().split('-')[0];
    const languageFit = channel.languages.includes(language) || channel.languages.includes('*');
    // English-only editorial placements should not be recommended to an
    // unrelated-language site on a category match alone.
    if (!languageFit && language !== 'und') return [];
    const score = Math.min(100, relevance + (languageFit ? 15 : 0) +
      (channel.quality === 'A' ? 8 : channel.quality === 'B' ? 4 : 0) +
      (channel.free === 'yes' ? 5 : channel.free === 'conditional' ? 1 : 0));
    const reason = direct ? `Matches ${site.category} audience` : adjacent ? `Related to ${site.category} audience` : 'Broad audience; check fit manually';
    return [{ channel, score, reason: `${reason}; ${channel.qualityReason}` }];
  }).sort((a, b) => b.score - a.score || a.channel.name.localeCompare(b.channel.name));
}
