export type SiteStatus = 'analyzing'|'ready'|'paused'|'attention';
export type TaskStatus = 'queued'|'running'|'needs_input'|'review'|'live'|'failed'|'skipped'|'expired';
export type Category = 'software'|'ai'|'developer'|'design'|'business'|'content'|'education'|'finance'|'general';
export type Qualification = 'software'|'developer'|'portfolio'|'publication'|'business'|'localBusiness'|'techContent'|'wordpressPlugin'|'drupalProject'|'javascriptPackage'|'pythonPackage'|'dotnetPackage'|'rustCrate'|'phpPackage'|'dartPackage'|'rubyGem'|'containerImage'|'aiArtifact'|'firefoxExtension'|'vscodeExtension'|'jetbrainsPlugin'|'linuxApp'|'androidFoss'|'openSource'|'gameAsset';
export interface SearchReport {checkedAt:string;method:'api'|'csv';sources:string[];complete:boolean;message:string;targetUrl?:string;error?:boolean}
export interface Site {id:string;domain:string;url:string;email:string;publicEmail?:string;mailboxId?:string;name:string;description:string;category:Category;language:string;monthlyTarget:number;status:SiteStatus;createdAt:string;analyzedAt?:string;error?:string;qualifications?:Partial<Record<Qualification,string>>;searchReports?:{gsc?:SearchReport;bing?:SearchReport}}
export interface Channel {id:string;name:string;domain:string;url:string;submitUrl:string;categories:Category[];languages:string[];kind:'directory'|'profile'|'article'|'community';emailRequired:boolean;accountRequired:boolean;articleRequired:boolean;free:'yes'|'conditional'|'unknown'|'paid';freeNote:string;automation:'browser'|'api'|'manual';quality:'A'|'B'|'C';qualityReason:string;provenance?:'built-in'|'custom';requirements?:Qualification[];evidenceStatus?:'rules_checked'|'user_added';authority?:{name:string;value:number;source:string;asOf:string;scope?:'domain'|'subdomain'|'page'};traffic?:{monthly:number;source:string;asOf:string;region?:string;period?:string;metric?:'visits'|'organicVisits';estimated?:boolean};rulesUrl:string;checkedAt:string;notes:string;allowedHosts:string[];enabled:boolean}
export interface TaskHistoryEntry {at:string;status:TaskStatus;message:string;linkCheck?:'found'|'absent'|'unreachable'|'invalid'}
export interface TaskCost {aiCalls:number;durationMs?:number;inputTokens?:number;outputTokens?:number;amount?:number;currency?:string}
export interface Task {publicationMethod?:'client'|'external';id:string;siteId:string;channelId:string;accountId?:string;sourceDomain:string;status:TaskStatus;createdAt:string;scheduledAt:string;updatedAt:string;attempts:number;message:string;draft?:{title:string;description:string;body:string};draftRevision?:number;draftUpdatedAt?:string;publicUrl?:string;verifiedAt?:string;firstLiveAt?:string;linkRel?:string;reviewUntil?:string;reviewKind?:'publication'|'manual_url'|'lost_link';submittedAt?:string;lastCheckedAt?:string;nextCheckAt?:string;lostAt?:string;consecutiveMissing?:number;health?:'pending'|'healthy'|'missing'|'unknown';history?:TaskHistoryEntry[];cost?:TaskCost;checkpoint?:string;reason?:string;linkCheck?:'found'|'absent'|'unreachable'|'invalid';articleApprovedAt?:string}
export type AccountStatus='draft'|'needs_verification'|'registered'|'credentials_invalid'|'restricted'|'unknown';
export type AccountIssueCode='legacy_saved'|'password_missing'|'bad_password'|'email_exists'|'username_taken'|'verification_required'|'registration_failed'|'registration_unknown'|'restricted';
export interface AccountDiagnostic {code:AccountIssueCode;message:string;at:string;retryable:boolean}
export interface Account {credentialKind?:'password'|'api_token';id:string;channelId:string;email:string;username:string;mailboxId?:string;createdAt:string;status:AccountStatus;hasPassword:boolean;source?:'generated'|'imported';updatedAt?:string;lastUsedAt?:string;registeredAt?:string;verifiedAt?:string;registrationAttempts?:number;diagnostic?:AccountDiagnostic}
export interface SiteAccountBinding {id:string;siteId:string;channelId:string;accountId:string;createdAt:string;updatedAt:string}
export interface Mailbox {id:string;label:string;host:string;port:number;user:string;secure:boolean;hasPassword:boolean;aliases:string[];createdAt:string;updatedAt:string;verifiedAt?:string;lastError?:string}
// Service-reported identifiers may grow beyond the currently known display labels.
export type ReasoningEffort=string;
export function isReasoningEffort(value:unknown):value is ReasoningEffort {return typeof value==='string'&&/^[a-z0-9][a-z0-9._-]{0,63}$/i.test(value)}
export interface AiModelOption {id:string;label?:string;source:'api'|'codex';isDefault?:boolean;supportsReasoning?:ReasoningEffort[];defaultReasoningEffort?:ReasoningEffort}
export interface AiModelDiscovery {provider:'codex'|'api';models:AiModelOption[];defaultModel?:string;effectiveModel?:string;source:'remote'|'local-cli'|'configured'|'unavailable';discoveredAt:string;message:string}
export interface SiteCapacity {siteId:string;currentLive:number;firstVerifiedThisMonth:number;missing:number;eligibleUnused:number;automaticUnused:number;manualUnused:number;monthsAtTarget:number|null;reason?:string}
export interface Settings {hasBingKey?:boolean;monitorSearch?:boolean;provider:'codex'|'api';codexPath:string;model:string;reasoningEffort?:ReasoningEffort;preferredBrowser?:'system'|'chrome'|'edge';apiBase:string;hasApiKey:boolean;autoRun:boolean;launchAtLogin:boolean;notify:boolean;timezone:string;maxAttempts:number;maxSteps:number;dailyAiLimit:number;channelOverrides:Record<string,boolean>;mail:{host:string;port:number;user:string;secure:boolean;hasPassword:boolean};}
export interface Event {id:string;at:string;siteId?:string;taskId?:string;level:'info'|'warning'|'error';message:string}
export interface Runtime {busy:boolean;activeTaskId?:string;aiReady:boolean;vaultReady:boolean;mailReady:boolean;version:string;platform:string;dataPath:string;error?:string;aiCallsToday:number}
export interface Snapshot {sites:Site[];tasks:Task[];channels:Channel[];accounts:Account[];mailboxes:Mailbox[];accountBindings:SiteAccountBinding[];settings:Settings;events:Event[];runtime:Runtime;capacity?:SiteCapacity[];aiModels?:AiModelDiscovery;demo?:boolean}
export interface AddSiteInput {domain:string;email:string;monthlyTarget:number}
export interface AppApi {invoke<T=unknown>(command:string,payload?:unknown):Promise<T>;onChange(callback:()=>void):()=>void}
declare global {interface Window {linkflow?:AppApi}}
export interface SecretStore {get(key:string):Promise<string|undefined>;set(key:string,value:string):Promise<void>;delete(key:string):Promise<void>}
export interface AiPort {json<T>(instruction:string,data:unknown,schema?:Record<string,unknown>,signal?:AbortSignal):Promise<T>}
export interface ExecutionContext {site:Site;channel:Channel;task:Task;settings:Settings;mailbox?:Mailbox;secrets:SecretStore;ai:AiPort;signal:AbortSignal;getAccount:()=>Account|undefined;saveAccount:(account:Account,password?:string)=>Promise<void>;checkpoint:(partial:Partial<Task>)=>void;log:(message:string)=>void}
export interface ExecutionResult {status:TaskStatus;message:string;publicUrl?:string;checkpoint?:string;submittedAt?:string}
export interface LinkResult {outcome?:'found'|'absent'|'unreachable'|'invalid';found:boolean;url:string;rel:string;reason:string}
export const IPC_COMMANDS=['snapshot','site:add','site:update','site:delete','site:analyze','site:pause','site:queue-channel','site:adopt-gist','search:bing','search:import-gsc','search:save-key','task:retry','task:skip','task:verify','task:set-url','task:open','task:open-result','task:generate','task:update-draft','task:approve','plan:run','plan:pause','settings:save','settings:test-ai','settings:test-mail','settings:discover-models','mailbox:save','mailbox:test','mailbox:delete','mailbox:import','account:save','account:set-bindings','account:bind','account:unbind','account:connect-gist','account:retry','account:reveal','account:delete','channel:save','channel:delete','channel:import-metrics','backup:export','backup:import','backup:auto-status','backup:auto-configure','backup:auto-run','backup:auto-restore','app:update-status','app:check-update','app:download-update','app:cancel-update','app:install-update','data:export','external:open','app:quit'] as const;
