import { z } from 'zod';
import { category, SettingsPatch } from './validation';
import type { State } from './store';
import type { Account } from '../shared/types';
const id=z.string().uuid(),date=z.string().datetime(),text=z.string().max(30000);
const accountDiagnostic=z.object({code:z.enum(['legacy_saved','password_missing','bad_password','email_exists','username_taken','verification_required','registration_failed','registration_unknown','restricted']),message:z.string().max(1000),at:date,retryable:z.boolean()});
const account=z.object({id,channelId:z.string().max(100),email:z.email(),username:text,createdAt:date,status:z.enum(['saved','draft','registered','needs_verification','credentials_invalid','restricted','unknown']),hasPassword:z.boolean(),source:z.enum(['generated','imported']).optional(),updatedAt:date.optional(),lastUsedAt:date.optional(),registeredAt:date.optional(),verifiedAt:date.optional(),registrationAttempts:z.number().int().min(0).max(20).optional(),diagnostic:accountDiagnostic.optional()}).transform(value=>{
  if(value.status!=='saved')return value as Account;
  return {...value,status:'unknown',source:value.source??'imported',updatedAt:value.updatedAt??value.createdAt,diagnostic:value.diagnostic??{code:'legacy_saved',message:'旧版已保存账号，需登录核验后继续。',at:value.updatedAt??value.createdAt,retryable:false}} satisfies Account;
});
const backup=z.object({state:z.object({sites:z.array(z.object({id,domain:z.string().min(3).max(253),url:z.url(),email:z.email(),name:text,description:text,category,language:z.string(),monthlyTarget:z.number().int().min(1).max(20),status:z.enum(['analyzing','ready','paused','attention']),createdAt:date,analyzedAt:date.optional(),error:text.optional()})).max(10000),tasks:z.array(z.object({id,siteId:id,channelId:z.string().max(100),sourceDomain:z.string().max(253),status:z.enum(['queued','running','needs_input','review','live','failed','skipped','expired']),createdAt:date,scheduledAt:date,updatedAt:date,attempts:z.number().int().min(0).max(100),message:text,draft:z.object({title:text,description:text,body:text}).optional(),publicUrl:z.url().optional(),verifiedAt:date.optional(),firstLiveAt:date.optional(),linkRel:text.optional(),reviewUntil:date.optional(),submittedAt:date.optional(),lastCheckedAt:date.optional(),checkpoint:text.optional(),reason:text.optional()})).max(50000),accounts:z.array(account).max(10000),settings:SettingsPatch.omit({apiKey:true,mailPassword:true}).extend({hasApiKey:z.boolean(),mail:z.object({host:z.string().max(253),port:z.number().int().min(1).max(65535),user:z.string().max(254),secure:z.literal(true),hasPassword:z.boolean()})}).strict(),events:z.array(z.object({id,at:date,siteId:id.optional(),taskId:id.optional(),level:z.enum(['info','warning','error']),message:text})).max(500),usage:z.record(z.string().regex(/^\d{4}-\d{2}-\d{2}$/),z.number().int().nonnegative())}),secrets:z.record(z.string().regex(/^(apiKey|mailPassword|account:[0-9a-f-]{36})$/),z.string().max(4096))});
export function validateBackup(input:unknown):{state:State;secrets:Record<string,string>}{
  const out=backup.parse(input);const siteIds=new Set(out.state.sites.map(s=>s.id));
  if(siteIds.size!==out.state.sites.length||new Set(out.state.tasks.map(t=>t.id)).size!==out.state.tasks.length||out.state.tasks.some(t=>!siteIds.has(t.siteId)))throw Error('备份存在重复或孤立任务');
  if(new Set(out.state.accounts.map(a=>a.id)).size!==out.state.accounts.length)throw Error('备份账号重复');
  return out as {state:State;secrets:Record<string,string>};
}
