import {constants as fsConstants} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFile,spawn} from 'node:child_process';
import {dirname,isAbsolute,relative,resolve,sep} from 'node:path';
import type {UpdateHelperJob} from './update-install';
import {updateRawFs} from './update-files';
import {hashUpdateTree} from './update-tree';

const rawFs=updateRawFs(),{access,lstat,readFile,rename,rm,writeFile}=rawFs.promises;

export interface HelperPorts {isAlive?:(pid:number)=>boolean;wait?:(milliseconds:number)=>Promise<void>;executeInstaller?:(file:string,args:string[])=>Promise<void>;launch?:(file:string,args:string[])=>Promise<{pid:number}>;openMac?:(applicationPath:string)=>Promise<void>;findMacPid?:(executablePath:string)=>Promise<number|undefined>;verifyMac?:(applicationPath:string)=>Promise<void>;terminate?:(pid:number)=>void}
const versionPattern=/^\d{1,6}\.\d{1,6}\.\d{1,6}$/;
function inside(parent:string,child:string):boolean{const path=relative(resolve(parent),resolve(child));return !!path&&path!=='..'&&!path.startsWith('..'+sep)&&!isAbsolute(path)}
function cleanEnvironment():NodeJS.ProcessEnv{const environment={...process.env};delete environment.ELECTRON_RUN_AS_NODE;delete environment.LINKFLOW_UPDATE_HELPER;return environment}
function executeInstaller(file:string,args:string[]):Promise<void>{return new Promise((done,reject)=>execFile(file,args,{timeout:180_000,maxBuffer:1024*1024,windowsVerbatimArguments:process.platform==='win32',shell:false},error=>error?reject(error):done()))}
function launch(file:string,args:string[]):Promise<{pid:number}>{return new Promise((done,reject)=>{const child=spawn(file,args,{cwd:dirname(file),detached:true,stdio:'ignore',windowsHide:true,shell:false,env:cleanEnvironment()});child.once('error',reject);child.once('spawn',()=>{if(!child.pid){reject(Error('新版本进程未启动'));return}child.unref();done({pid:child.pid})})})}
function openMac(applicationPath:string):Promise<void>{return new Promise((done,reject)=>execFile('/usr/bin/open',['-n',applicationPath],{timeout:30_000,maxBuffer:1024*1024,shell:false,env:cleanEnvironment()},error=>error?reject(error):done()))}
function findMacPid(executablePath:string):Promise<number|undefined>{return new Promise((done,reject)=>execFile('/bin/ps',['-axo','pid=,command='],{timeout:10_000,maxBuffer:8*1024*1024,encoding:'utf8',shell:false},(error,stdout)=>{if(error){reject(error);return}for(const line of stdout.split('\n')){const match=/^\s*(\d+)\s+(.+)$/.exec(line);if(match&&(match[2]===executablePath||match[2].startsWith(executablePath+' '))){done(Number(match[1]));return}}done(undefined)}))}
async function verifyMac(applicationPath:string){await new Promise<void>((done,reject)=>execFile('/usr/bin/codesign',['--verify','--deep','--strict',applicationPath],{timeout:60_000,maxBuffer:1024*1024,shell:false},error=>error?reject(error):done()));await new Promise<void>((done,reject)=>execFile('/usr/bin/xattr',['-p','com.apple.quarantine',applicationPath],{timeout:10_000,maxBuffer:1024*1024,shell:false},(error,stdout)=>error||!stdout.length?reject(error??Error('缺少安全隔离属性')):done()))}
function alive(pid:number):boolean{try{process.kill(pid,0);return true}catch(error){return (error as NodeJS.ErrnoException).code==='EPERM'}}
function validateJob(value:unknown,jobPath:string):UpdateHelperJob{
  if(!value||typeof value!=='object'||Array.isArray(value))throw Error('更新任务无效');const job=value as Partial<UpdateHelperJob>;
  if(job.schemaVersion!==1||(job.platform!=='darwin-arm64'&&job.platform!=='win32-x64')||typeof job.token!=='string'||!/^[a-f0-9-]{16,64}$/i.test(job.token)||!Number.isSafeInteger(job.oldPid)||(job.oldPid??0)<1||typeof job.targetVersion!=='string'||!versionPattern.test(job.targetVersion))throw Error('更新任务无效');
  if(!Number.isSafeInteger(job.artifactSize)||(job.artifactSize??0)<1||typeof job.artifactSha256!=='string'||!/^[a-f0-9]{64}$/.test(job.artifactSha256))throw Error('更新安装包校验信息无效');
  for(const key of ['updatesDirectory','artifactPath','applicationPath','executablePath','backupPath','helperRuntimePath','readyPath','armPath','startupRequestPath','startupAckPath','receiptPath','errorPath'] as const)if(typeof job[key]!=='string'||!isAbsolute(job[key]!))throw Error('更新任务路径无效');
  if(resolve(dirname(jobPath))!==resolve(job.updatesDirectory!)||!inside(job.updatesDirectory!,jobPath)||!inside(job.updatesDirectory!,job.artifactPath!)||!inside(job.updatesDirectory!,job.helperRuntimePath!)||resolve(job.readyPath!)!==resolve(jobPath+'.ready')||resolve(job.armPath!)!==resolve(jobPath+'.armed')||resolve(job.startupRequestPath!)!==resolve(job.updatesDirectory!,'startup-request.json')||resolve(job.startupAckPath!)!==resolve(job.updatesDirectory!,'startup-ack')||resolve(dirname(job.receiptPath!))!==resolve(job.updatesDirectory!)||resolve(dirname(job.errorPath!))!==resolve(job.updatesDirectory!))throw Error('更新任务超出受控目录');
  if(job.platform==='darwin-arm64'){
    if(typeof job.stagedApplicationPath!=='string'||typeof job.stagedTreeSha256!=='string'||!/^[a-f0-9]{64}$/.test(job.stagedTreeSha256)||!isAbsolute(job.stagedApplicationPath)||resolve(job.applicationPath!)===resolve(job.backupPath!)||!basenameSafe(job.backupPath!).startsWith('.'+basenameSafe(job.applicationPath!)+'.linkflow-backup-')||resolve(dirname(job.applicationPath!))!==resolve(dirname(job.backupPath!))||resolve(dirname(dirname(job.stagedApplicationPath)))!==resolve(dirname(job.applicationPath!))||!basenameSafe(dirname(job.stagedApplicationPath)).startsWith('.linkflow-update-'))throw Error('macOS 更新任务路径无效');
  }else if(resolve(job.applicationPath!)===resolve(job.backupPath!)||resolve(job.applicationPath!)!==resolve(dirname(job.executablePath!))||resolve(dirname(job.applicationPath!))!==resolve(dirname(job.backupPath!))||!basenameSafe(job.backupPath!).startsWith('.linkflow-backup-'))throw Error('Windows 更新任务路径无效');
  return job as UpdateHelperJob;
}
function basenameSafe(path:string){const parts=path.split(/[\\/]/);return parts.at(-1)??''}
async function atomicJson(path:string,value:unknown){const temporary=path+'.tmp';await rm(temporary,{force:true});await writeFile(temporary,JSON.stringify(value),{mode:0o600,flag:'wx'});await rename(temporary,path)}
async function hashFile(path:string){const hash=createHash('sha256');for await(const chunk of rawFs.createReadStream(path))hash.update(chunk as Buffer);return hash.digest('hex')}
async function waitForExit(pid:number,isAlive:(pid:number)=>boolean,wait:(milliseconds:number)=>Promise<void>,timeoutMs:number,message:string){const deadline=Date.now()+timeoutMs;while(isAlive(pid)){if(Date.now()>=deadline)throw Error(message);await wait(100)}}
async function waitForToken(path:string,token:string,wait:(milliseconds:number)=>Promise<void>,timeoutMs:number,message:string){const deadline=Date.now()+timeoutMs;for(;;){try{if((await readFile(path,'utf8'))===token)return}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}if(Date.now()>=deadline)throw Error(message);await wait(50)}}
async function startNew(job:UpdateHelperJob,ports:{launch:(file:string,args:string[])=>Promise<{pid:number}>;openMac:(path:string)=>Promise<void>;findMacPid:(path:string)=>Promise<number|undefined>;wait:(ms:number)=>Promise<void>}):Promise<number>{
  if(job.platform==='win32-x64')return (await ports.launch(job.executablePath,[])).pid;await ports.openMac(job.applicationPath);const deadline=Date.now()+10_000;for(;;){const pid=await ports.findMacPid(job.executablePath);if(pid)return pid;if(Date.now()>=deadline)throw Error('macOS 未确认新版本进程已启动');await ports.wait(100)}
}
async function restartOld(job:UpdateHelperJob,launchApp:(file:string,args:string[])=>Promise<{pid:number}>,openApplication:(path:string)=>Promise<void>){if(job.platform==='darwin-arm64')await openApplication(job.applicationPath);else await launchApp(job.executablePath,[])}
export async function runUpdateHelper(jobPath:string,ports:HelperPorts={}):Promise<void>{
  const delay=ports.wait??(milliseconds=>new Promise(done=>setTimeout(done,milliseconds))),isAlive=ports.isAlive??alive,runInstaller=ports.executeInstaller??executeInstaller,start=ports.launch??launch,openApplication=ports.openMac??openMac,findPid=ports.findMacPid??findMacPid,verifyMacApplication=ports.verifyMac??verifyMac,terminate=ports.terminate??(pid=>process.kill(pid,'SIGTERM'));let job:UpdateHelperJob|undefined;
  try{
    if(!isAbsolute(jobPath))throw Error('更新任务路径无效');const info=await lstat(jobPath);if(!info.isFile()||info.isSymbolicLink()||info.size>64*1024)throw Error('更新任务文件无效');job=validateJob(JSON.parse(await readFile(jobPath,'utf8')),jobPath);
    await access(job.artifactPath,fsConstants.R_OK);await writeFile(job.readyPath,job.token,{mode:0o600,flag:'wx'});await waitForToken(job.armPath,job.token,delay,5000,'更新安装授权握手超时');await rm(job.armPath,{force:true});await waitForExit(job.oldPid,isAlive,delay,120_000,'等待旧版本退出超时');const artifactInfo=await lstat(job.artifactPath);if(!artifactInfo.isFile()||artifactInfo.isSymbolicLink()||artifactInfo.size!==job.artifactSize||await hashFile(job.artifactPath)!==job.artifactSha256)throw Error('安装前完整性复验失败');
    let backupReady=false,replacementMayExist=false,newPid:number|undefined;
    try{
      if(job.platform==='darwin-arm64'){if(await hashUpdateTree(job.stagedApplicationPath!)!==job.stagedTreeSha256)throw Error('macOS 更新应用树与已验证安装包不匹配');await verifyMacApplication(job.stagedApplicationPath!);await rename(job.applicationPath,job.backupPath);backupReady=true;await rename(job.stagedApplicationPath!,job.applicationPath);replacementMayExist=true}else{const backupExecutable=resolve(job.backupPath,relative(job.applicationPath,job.executablePath)),backupInfo=await lstat(backupExecutable);if(!backupInfo.isFile()||backupInfo.isSymbolicLink())throw Error('Windows 回滚副本不完整');backupReady=true;replacementMayExist=true;await runInstaller(job.artifactPath,['/S',`/D=${job.applicationPath}`])}
      await access(job.executablePath,fsConstants.X_OK);await rm(job.startupAckPath,{force:true});await atomicJson(job.startupRequestPath,{schemaVersion:1,targetVersion:job.targetVersion,token:job.token});newPid=await startNew(job,{launch:start,openMac:openApplication,findMacPid:findPid,wait:delay});await waitForToken(job.startupAckPath,job.token,delay,60_000,'新版本未能完成启动确认');
    }catch(error){
      if(!backupReady)throw error;if(!newPid&&job.platform==='darwin-arm64')newPid=await findPid(job.executablePath);if(newPid&&isAlive(newPid)){terminate(newPid);await waitForExit(newPid,isAlive,delay,10_000,'新版本未能退出，已保留回滚副本')}
      if(replacementMayExist){if(job.platform==='darwin-arm64'){await rm(job.stagedApplicationPath!,{recursive:true,force:true});await rename(job.applicationPath,job.stagedApplicationPath!)}else await rm(job.applicationPath,{recursive:true,force:true})}await rename(job.backupPath,job.applicationPath);await restartOld(job,start,openApplication);throw error;
    }
    await rm(job.backupPath,{recursive:true,force:true});await atomicJson(job.receiptPath,{schemaVersion:1,targetVersion:job.targetVersion,installedAt:new Date().toISOString(),cleanupPath:job.helperRuntimePath});await Promise.all([rm(job.startupRequestPath,{force:true}),rm(job.startupAckPath,{force:true}),rm(jobPath,{force:true})]);
  }catch(error){if(job){try{await atomicJson(job.errorPath,{schemaVersion:1,targetVersion:job.targetVersion,failedAt:new Date().toISOString(),message:'安装助手未能完成替换、启动确认或回滚',cleanupPath:job.helperRuntimePath})}catch{}await Promise.allSettled([rm(jobPath,{force:true}),rm(job.readyPath,{force:true}),rm(job.armPath,{force:true}),rm(job.startupRequestPath,{force:true}),rm(job.startupAckPath,{force:true})])}throw error}
}

if(process.env.LINKFLOW_UPDATE_HELPER==='1'&&process.argv[2])runUpdateHelper(process.argv[2]).then(()=>process.exit(0),()=>process.exit(1));
