import {constants as fsConstants} from 'node:fs';
import {createHash} from 'node:crypto';
import {execFile,spawn} from 'node:child_process';
import {basename,dirname,isAbsolute,join,relative,resolve} from 'node:path';
import {validateUpdateHelperJob,type UpdateHelperJob} from './update-install';
import {updateRawFs} from './update-files';
import {hashUpdateTree} from './update-tree';

const rawFs=updateRawFs(),{access,lstat,readFile,rename,rm,writeFile}=rawFs.promises;

interface StartupAck {schemaVersion:2;targetVersion:string;token:string;pid:number;applicationPath:string;executablePath:string}
interface MacProcess {pid:number;command:string}
export interface HelperPorts {isAlive?:(pid:number)=>boolean;wait?:(milliseconds:number)=>Promise<void>;executeInstaller?:(file:string,args:string[])=>Promise<void>;launch?:(file:string,args:string[])=>Promise<{pid:number}>;openMac?:(applicationPath:string)=>Promise<void>;listMacProcesses?:()=>Promise<MacProcess[]>;verifyMac?:(applicationPath:string)=>Promise<void>;verifyMacStartup?:(applicationPath:string,executablePath:string,targetVersion:string,treeSha256:string)=>Promise<void>;terminate?:(pid:number)=>void;startupTimeoutMs?:number}
function cleanEnvironment():NodeJS.ProcessEnv{const environment={...process.env};delete environment.ELECTRON_RUN_AS_NODE;delete environment.LINKFLOW_UPDATE_HELPER;return environment}
function executeInstaller(file:string,args:string[]):Promise<void>{return new Promise((done,reject)=>execFile(file,args,{timeout:180_000,maxBuffer:1024*1024,windowsVerbatimArguments:process.platform==='win32',shell:false},error=>error?reject(error):done()))}
function launch(file:string,args:string[]):Promise<{pid:number}>{return new Promise((done,reject)=>{const child=spawn(file,args,{cwd:dirname(file),detached:true,stdio:'ignore',windowsHide:true,shell:false,env:cleanEnvironment()});child.once('error',reject);child.once('spawn',()=>{if(!child.pid){reject(Error('新版本进程未启动'));return}child.unref();done({pid:child.pid})})})}
function openMac(applicationPath:string):Promise<void>{return new Promise((done,reject)=>execFile('/usr/bin/open',['-n',applicationPath],{timeout:30_000,maxBuffer:1024*1024,shell:false,env:cleanEnvironment()},error=>error?reject(error):done()))}
function listMacProcesses():Promise<MacProcess[]>{return new Promise((done,reject)=>execFile('/bin/ps',['-axo','pid=,command='],{timeout:10_000,maxBuffer:8*1024*1024,encoding:'utf8',shell:false},(error,stdout)=>{if(error){reject(error);return}done(stdout.split('\n').flatMap(line=>{const match=/^\s*(\d+)\s+(.+)$/.exec(line);return match?[{pid:Number(match[1]),command:match[2]}]:[]}))}))}
async function verifyMac(applicationPath:string){await new Promise<void>((done,reject)=>execFile('/usr/bin/codesign',['--verify','--deep','--strict',applicationPath],{timeout:60_000,maxBuffer:1024*1024,shell:false},error=>error?reject(error):done()));await new Promise<void>((done,reject)=>execFile('/usr/bin/xattr',['-p','com.apple.quarantine',applicationPath],{timeout:10_000,maxBuffer:1024*1024,shell:false},(error,stdout)=>error||!stdout.length?reject(error??Error('缺少安全隔离属性')):done()))}
function run(file:string,args:string[]):Promise<string>{return new Promise((done,reject)=>execFile(file,args,{timeout:60_000,maxBuffer:1024*1024,encoding:'utf8',shell:false},(error,stdout)=>error?reject(error):done(stdout)))}
async function verifyMacStartup(applicationPath:string,executablePath:string,targetVersion:string,treeSha256:string){
  const appInfo=await lstat(applicationPath),executableInfo=await lstat(executablePath);if(!appInfo.isDirectory()||appInfo.isSymbolicLink()||!executableInfo.isFile()||executableInfo.isSymbolicLink())throw Error('macOS 新版本进程路径无效');
  await run('/usr/bin/codesign',['--verify','--deep','--strict',applicationPath]);const plist=join(applicationPath,'Contents','Info.plist'),identifier=(await run('/usr/bin/plutil',['-extract','CFBundleIdentifier','raw','-o','-',plist])).trim(),version=(await run('/usr/bin/plutil',['-extract','CFBundleShortVersionString','raw','-o','-',plist])).trim(),architectures=(await run('/usr/bin/lipo',['-archs',executablePath])).trim();
  if(identifier!=='com.linkflow.personal'||version!==targetVersion||architectures!=='arm64'||await hashUpdateTree(applicationPath)!==treeSha256)throw Error('macOS 新版本进程身份校验失败');
}
function alive(pid:number):boolean{try{process.kill(pid,0);return true}catch(error){return (error as NodeJS.ErrnoException).code==='EPERM'}}
async function atomicJson(path:string,value:unknown){const temporary=path+'.tmp';await rm(temporary,{force:true});await writeFile(temporary,JSON.stringify(value),{mode:0o600,flag:'wx'});await rename(temporary,path)}
async function hashFile(path:string){const hash=createHash('sha256');for await(const chunk of rawFs.createReadStream(path))hash.update(chunk as Buffer);return hash.digest('hex')}
async function waitForExit(pid:number,isAlive:(pid:number)=>boolean,wait:(milliseconds:number)=>Promise<void>,timeoutMs:number,message:string){const deadline=Date.now()+timeoutMs;while(isAlive(pid)){if(Date.now()>=deadline)throw Error(message);await wait(100)}}
async function waitForToken(path:string,token:string,wait:(milliseconds:number)=>Promise<void>,timeoutMs:number,message:string){const deadline=Date.now()+timeoutMs;for(;;){try{if((await readFile(path,'utf8'))===token)return}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}if(Date.now()>=deadline)throw Error(message);await wait(50)}}
function parseAck(data:string):StartupAck|undefined{try{const value=JSON.parse(data) as Partial<StartupAck>;return value.schemaVersion===2&&typeof value.targetVersion==='string'&&typeof value.token==='string'&&Number.isSafeInteger(value.pid)&&(value.pid??0)>0&&typeof value.applicationPath==='string'&&isAbsolute(value.applicationPath)&&typeof value.executablePath==='string'&&isAbsolute(value.executablePath)?value as StartupAck:undefined}catch{return}}
function commandMatches(command:string,executablePath:string):boolean{return command===executablePath||command.startsWith(executablePath+' ')}
function macShape(job:UpdateHelperJob,applicationPath:string,executablePath:string):boolean{return relative(applicationPath,executablePath)===relative(job.applicationPath,job.executablePath)&&basename(applicationPath)===basename(job.applicationPath)}
async function authenticateMacProcess(job:UpdateHelperJob,ack:StartupAck,ports:{isAlive:(pid:number)=>boolean;listProcesses:()=>Promise<MacProcess[]>;verifyStartup:(applicationPath:string,executablePath:string,targetVersion:string,treeSha256:string)=>Promise<void>}):Promise<boolean>{
  if(ack.token!==job.token||ack.targetVersion!==job.targetVersion||ack.pid===job.oldPid||ack.pid===process.pid||!macShape(job,ack.applicationPath,ack.executablePath)||!ports.isAlive(ack.pid))return false;
  const processRecord=(await ports.listProcesses()).find(value=>value.pid===ack.pid);if(!processRecord||!commandMatches(processRecord.command,ack.executablePath))return false;
  try{await ports.verifyStartup(ack.applicationPath,ack.executablePath,job.targetVersion,job.stagedTreeSha256!);return ports.isAlive(ack.pid)}catch{return false}
}
async function waitForMacAck(job:UpdateHelperJob,ports:{isAlive:(pid:number)=>boolean;listProcesses:()=>Promise<MacProcess[]>;verifyStartup:(applicationPath:string,executablePath:string,targetVersion:string,treeSha256:string)=>Promise<void>;wait:(ms:number)=>Promise<void>;timeoutMs:number}):Promise<StartupAck>{
  const deadline=Date.now()+ports.timeoutMs;for(;;){try{const info=await lstat(job.startupAckPath);if(info.isFile()&&!info.isSymbolicLink()&&info.size<=16*1024){const ack=parseAck(await readFile(job.startupAckPath,'utf8'));if(ack&&await authenticateMacProcess(job,ack,ports))return ack}}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}if(Date.now()>=deadline)throw Error('macOS 新版本未在限时内完成启动身份确认');await ports.wait(100)}
}
async function restartOld(job:UpdateHelperJob,launchApp:(file:string,args:string[])=>Promise<{pid:number}>,openApplication:(path:string)=>Promise<void>){if(job.platform==='darwin-arm64')await openApplication(job.applicationPath);else await launchApp(job.executablePath,[])}
export async function runUpdateHelper(jobPath:string,ports:HelperPorts={}):Promise<void>{
  const delay=ports.wait??(milliseconds=>new Promise(done=>setTimeout(done,milliseconds))),isAlive=ports.isAlive??alive,runInstaller=ports.executeInstaller??executeInstaller,start=ports.launch??launch,openApplication=ports.openMac??openMac,listProcesses=ports.listMacProcesses??listMacProcesses,verifyMacApplication=ports.verifyMac??verifyMac,verifyStartup=ports.verifyMacStartup??verifyMacStartup,terminate=ports.terminate??(pid=>process.kill(pid,'SIGTERM'));let job:UpdateHelperJob|undefined,preserveRecovery=false;
  try{
    if(!isAbsolute(jobPath))throw Error('更新任务路径无效');const info=await lstat(jobPath);if(!info.isFile()||info.isSymbolicLink()||info.size>64*1024)throw Error('更新任务文件无效');job=validateUpdateHelperJob(JSON.parse(await readFile(jobPath,'utf8')),jobPath);
    await access(job.artifactPath,fsConstants.R_OK);await writeFile(job.readyPath,job.token,{mode:0o600,flag:'wx'});await waitForToken(job.armPath,job.token,delay,5000,'更新安装授权握手超时');await rm(job.armPath,{force:true});await waitForExit(job.oldPid,isAlive,delay,120_000,'等待旧版本退出超时');const artifactInfo=await lstat(job.artifactPath);if(!artifactInfo.isFile()||artifactInfo.isSymbolicLink()||artifactInfo.size!==job.artifactSize||await hashFile(job.artifactPath)!==job.artifactSha256)throw Error('安装前完整性复验失败');
    let backupReady=false,replacementMayExist=false,newPid:number|undefined,macAck:StartupAck|undefined;
    try{
      if(job.platform==='darwin-arm64'){if(await hashUpdateTree(job.stagedApplicationPath!)!==job.stagedTreeSha256)throw Error('macOS 更新应用树与已验证安装包不匹配');await verifyMacApplication(job.stagedApplicationPath!);await rename(job.applicationPath,job.backupPath);backupReady=true;preserveRecovery=true;await rename(job.stagedApplicationPath!,job.applicationPath);replacementMayExist=true}else{const backupExecutable=resolve(job.backupPath,relative(job.applicationPath,job.executablePath)),backupInfo=await lstat(backupExecutable);if(!backupInfo.isFile()||backupInfo.isSymbolicLink())throw Error('Windows 回滚副本不完整');backupReady=true;replacementMayExist=true;preserveRecovery=true;await runInstaller(job.artifactPath,['--updated','/S',`/D=${job.applicationPath}`])}
      await access(job.executablePath,fsConstants.X_OK);await rm(job.startupAckPath,{force:true});await atomicJson(job.startupRequestPath,{schemaVersion:1,targetVersion:job.targetVersion,token:job.token});
      if(job.platform==='win32-x64'){newPid=(await start(job.executablePath,[])).pid;await waitForToken(job.startupAckPath,job.token,delay,60_000,'新版本未能完成启动确认')}else{try{await openApplication(job.applicationPath)}catch{}macAck=await waitForMacAck(job,{isAlive,listProcesses,verifyStartup,wait:delay,timeoutMs:ports.startupTimeoutMs??15*60_000});newPid=macAck.pid}
    }catch(error){
      if(!backupReady)throw error;if(job.platform==='darwin-arm64'&&!macAck)throw Error('macOS 新版本进程身份不明，已保留新版本和恢复副本');
      if(newPid&&isAlive(newPid)){if(job.platform==='darwin-arm64'&&(!macAck||!await authenticateMacProcess(job,macAck,{isAlive,listProcesses,verifyStartup})))throw Error('macOS 新版本进程身份发生变化，已保留恢复副本');terminate(newPid);await waitForExit(newPid,isAlive,delay,10_000,'新版本未能退出，已保留回滚副本')}
      if(replacementMayExist){if(job.platform==='darwin-arm64'){await rm(job.stagedApplicationPath!,{recursive:true,force:true});await rename(job.applicationPath,job.stagedApplicationPath!)}else await rm(job.applicationPath,{recursive:true,force:true})}await rename(job.backupPath,job.applicationPath);await restartOld(job,start,openApplication);preserveRecovery=false;throw error;
    }
    if(job.platform==='darwin-arm64'&&(!newPid||!isAlive(newPid)))throw Error('macOS 新版本在完成前退出，已保留恢复副本');await atomicJson(job.receiptPath,{schemaVersion:1,targetVersion:job.targetVersion,installedAt:new Date().toISOString(),cleanupPath:job.helperRuntimePath,backupCleanupPath:job.backupPath});preserveRecovery=false;await Promise.allSettled([rm(job.backupPath,{recursive:true,force:true}),rm(job.startupRequestPath,{force:true}),rm(job.startupAckPath,{force:true}),rm(jobPath,{force:true})]);
  }catch(error){if(job){try{await atomicJson(job.errorPath,{schemaVersion:1,targetVersion:job.targetVersion,failedAt:new Date().toISOString(),message:preserveRecovery?'新版本启动身份未确认，已保留恢复副本':'安装助手未能完成替换、启动确认或回滚',cleanupPath:job.helperRuntimePath,...(preserveRecovery?{recoveryJobPath:jobPath}:{})})}catch{}const cleanup=[rm(job.readyPath,{force:true}),rm(job.armPath,{force:true})];if(!preserveRecovery)cleanup.push(rm(jobPath,{force:true}),rm(job.startupRequestPath,{force:true}),rm(job.startupAckPath,{force:true}));await Promise.allSettled(cleanup)}throw error}
}

if(process.env.LINKFLOW_UPDATE_HELPER==='1'&&process.argv[2])runUpdateHelper(process.argv[2]).then(()=>process.exit(0),()=>process.exit(1));
