import { app, session, BrowserWindow } from 'electron';
import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { runBrowserTask, closeTaskBrowser } from '../src/integrations/browser';
import type { ExecutionContext, Account } from '../src/shared/types';
app.setPath('userData', process.env.AUDIT_USER_DATA!);
const evidence:any[]=[];
let n=0;
async function scenario(name:string, pages:Record<string,string>, choose:(data:any,ctx:ExecutionContext)=>any, expected:(r:any,ctx:ExecutionContext,requests:any[],calls:any[])=>void, seed?:Account) {
 const id=`audit-${++n}`, controller=new AbortController(), requests:any[]=[], calls:any[]=[];
 let account=seed; const passwords=new Map<string,string>(); if(seed) passwords.set(`account:${seed.id}`,'fixture-only-password');
 const ctx:any={ site:{id,domain:'target.example',url:'https://target.example/',email:'audit@owner.example',name:'Audit Product',description:'Fixture description',category:'software',language:'en'}, channel:{id,name:'Fixture',domain:'fixture.example',submitUrl:'https://fixture.example/start',allowedHosts:['fixture.example'],automation:'browser',kind:'profile',emailRequired:false}, task:{id,createdAt:new Date().toISOString()}, settings:{maxSteps:15}, signal:controller.signal, secrets:{get:async(k:string)=>passwords.get(k),set:async()=>{},delete:async()=>{}}, ai:{json:async(_i:any,data:any)=>{calls.push(data); return choose(data,ctx);}},getAccount:()=>account,saveAccount:async(a:Account,p?:string)=>{account=a;if(p)passwords.set(`account:${a.id}`,p);},checkpoint:(p:any)=>Object.assign(ctx.task,p),log:()=>{}, abort:()=>controller.abort()};
 const partition=`persist:linkflow-${createHash('sha256').update(`${id}|${ctx.site.email}`).digest('hex').slice(0,20)}`;
 const s=session.fromPartition(partition);
 s.protocol.handle('https',async request=>{const url=new URL(request.url);const body=request.method==='POST'?new URLSearchParams(await request.text()):undefined;requests.push({host:url.host,path:url.pathname,method:request.method,...(request.method==='POST'?{checkpointAtWrite:ctx.task.checkpoint,submittedAtWrite:!!ctx.task.submittedAt}:{}),...(body?.has('email')?{emailMatched:body.get('email')===ctx.site.email,passwordNonempty:!!body.get('password')}:{}),...(body?.has('website')?{websiteMatched:body.get('website')===ctx.site.url,titleMatched:body.get('title')===ctx.site.name}:{})});return new Response(pages[url.pathname]??'<p>Not found</p>',{headers:{'content-type':'text/html'}});});
 const result=await runBrowserTask(ctx);
 try {expected(result,ctx,requests,calls); for(const password of passwords.values())assert(!JSON.stringify(calls).includes(password),'password leaked into AI data'); evidence.push({name,passed:true,result,requests,aiCalls:calls.length,accountStatus:account?.status});} catch(e){evidence.push({name,passed:false,result,requests,error:String(e),observedControls:calls.map(x=>x.page.controls.map((c:any)=>({label:c.label,filled:c.filled})))});process.exitCode=1;} finally {closeTaskBrowser(id);s.protocol.unhandle('https');}
}
const action=(kind:string,id=-1,ref='none',purpose='navigation')=>({kind,id,ref,purpose,option:0,reason:'deterministic fixture'});
const filling=(d:any)=> {const c=d.page.controls.find((c:any)=>!c.filled&&['input','textarea'].includes(c.tag)); if(c)return action('fill',c.id,c.type==='password'?'account.password':/email/i.test(c.label)?'account.email':/website/i.test(c.label)?'site.url':'site.title');return undefined;};
app.whenReady().then(async()=>{
 try{
 await scenario('register-fill-publish-observed-public-url',{
 '/start':'<form method="post" action="/editor"><label>Email<input name="email" type="email"></label><label>Password<input name="password" type="password"></label><button type="submit">Create account</button></form>',
 '/editor':'<a href="/logout">Log out</a><form method="post" action="/listing/123"><label>Website<input name="website" type="url"></label><label>Title<input name="title"></label><button type="submit">Publish listing</button></form>',
 '/listing/123':'<h1>Published successfully</h1><a href="https://target.example/">Audit Product</a>'
 },d=>filling(d)??action('click',d.page.controls.find((c:any)=>c.tag==='button').id,'none',d.page.url.endsWith('/start')?'register':'final_submit'),(r,c,req,calls)=>{assert.equal(r.status,'review');assert.equal(r.publicUrl,'https://fixture.example/listing/123');assert.equal(c.getAccount().status,'registered');assert.equal(req.filter(x=>x.method==='POST').length,2);assert(req.some(x=>x.emailMatched&&x.passwordNonempty));assert(req.some(x=>x.websiteMatched&&x.titleMatched));const p=calls.map(x=>JSON.stringify(x)).join('');assert(!p.includes('fixture-only-password'));});
 await scenario('captcha-pauses-before-ai',{'/start':'<div class="g-recaptcha" style="width:100px;height:100px">Captcha</div>'},()=>{throw new Error('AI should not run')},(r,c,req,calls)=>{assert.equal(r.status,'needs_input');assert.match(r.message,/验证码/);assert.equal(calls.length,0);});
 await scenario('abort-closes-browser-before-action',{'/start':'<button>Proceed</button>'},(d,c)=>{(c as any).abort();return action('click',0)},r=>{assert.equal(r.status,'queued');});
 await scenario('external-password-form-guard',{'/start':'<form method="post" action="https://external.example/capture"><label>Password<input name="password" type="password"></label><button>Continue</button></form>'},d=>filling(d),(r,c,req)=>{assert.equal(r.status,'needs_input');assert.match(r.message,/表单目标被阻止/);assert(!req.some(x=>x.host==='external.example'));});
 await scenario('external-final-submit-blocked-without-submission',{'/start':'<form method="post" action="https://external.example/capture"><label>Title<input value="fixture"></label><button type="submit">Publish</button></form>'},d=>action('click',1,'none','final_submit'),(r,c,req)=>{assert.equal(r.status,'needs_input');assert.equal(r.checkpoint,undefined);assert.equal(r.submittedAt,undefined);assert.equal(c.task.checkpoint,undefined);assert.equal(c.task.submittedAt,undefined);assert.match(r.message,/未执行提交/);assert(!req.some(x=>x.method==='POST'));});
 await scenario('delete-action-pauses-without-request',{'/start':'<button type="button" onclick="fetch(\'/delete-account\',{method:\'POST\'})">Delete account</button>','/delete-account':'OK'},d=>d.step===0?action('click',0):action('needs_input'),(r,c,req)=>{assert.equal(r.status,'needs_input');assert(!req.some(x=>x.path==='/delete-account'));assert.equal(c.task.checkpoint,undefined);});
 await scenario('publish-anchor-tracks-checkpoint-before-write',{'/start':'<a href="/published" onclick="fetch(\'/write\',{method:\'POST\'})">Publish listing</a>','/published':'<a href="https://target.example/">View</a>','/write':'OK'},d=>d.step===0?action('click',0,'none','final_submit'):action('needs_input'),(r,c,req)=>{assert(req.some(x=>x.path==='/published'));assert(req.some(x=>x.path==='/write'&&x.method==='POST'&&x.checkpointAtWrite==='submitting'&&x.submittedAtWrite));assert.equal(c.task.checkpoint,'submitting');assert.equal(r.status,'review');assert(r.submittedAt);assert.equal(r.publicUrl,'https://fixture.example/published');});
 await scenario('existing-dashboard-link-skipped-without-submission',{'/start':'<a href="/dashboard">Continue</a>','/dashboard':'<nav><a href="https://target.example/">Existing target link</a></nav><p>No submission performed</p>'},d=>d.step===0?action('click',0):action('done'),(r,c,req)=>{assert.equal(r.publicUrl,'https://fixture.example/dashboard');assert.equal(r.status,'skipped');assert.equal(r.checkpoint,'existing_link');assert.equal(r.submittedAt,undefined);assert.equal(c.task.submittedAt,undefined);assert.equal(c.task.firstLiveAt,undefined);assert(!req.some(x=>x.method==='POST'));});
 }catch(e){process.exitCode=1;evidence.push({fatal:String(e)});}finally{writeFileSync('.evidence/integration-electron.json',JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));app.exit(process.exitCode??0);}
});
