const { app,BrowserWindow,safeStorage }=require('electron');
const { chmodSync,mkdirSync,writeFileSync }=require('node:fs');
const { join }=require('node:path');
const assert=require('node:assert/strict');
const { DatabaseSync }=require('node:sqlite');
const evidence=join(process.cwd(),'.evidence');
mkdirSync(evidence,{recursive:true});
// Prevent external execution during deterministic UI and persistence checks.
mkdirSync(process.env.LINKFLOW_DATA_DIR,{recursive:true});
// Use the npm entry layout understood by the real Windows launcher as well as
// a shebang on macOS. This synthetic package never leaves the isolated profile.
const mockPackage=join(process.env.LINKFLOW_DATA_DIR,'mock-cli','node_modules','@openai','codex');
mkdirSync(join(mockPackage,'bin'),{recursive:true});
writeFileSync(join(mockPackage,'package.json'),JSON.stringify({name:'@openai/codex',bin:{codex:'bin/codex.js'}}));
const mockCodex=join(mockPackage,'bin','codex.js');
writeFileSync(mockCodex,`#!/usr/bin/env node
if(process.argv.includes('login')){console.log('Logged in');process.exit(0)}
const readline=require('node:readline');
const input=readline.createInterface({input:process.stdin});
input.on('line',line=>{const message=JSON.parse(line);if(message.method==='initialize')console.log(JSON.stringify({id:message.id,result:{}}));if(message.method==='model/list')console.log(JSON.stringify({id:message.id,result:{data:[{id:'reasoning-wide',displayName:'Reasoning Wide',isDefault:true,defaultReasoningEffort:'low',supportedReasoningEfforts:[{reasoningEffort:'minimal'},{reasoningEffort:'low'},{reasoningEffort:'high'}]},{id:'reasoning-compact',displayName:'Reasoning Compact',defaultReasoningEffort:'minimal',supportedReasoningEfforts:[{reasoningEffort:'none'},{reasoningEffort:'minimal'}]}]}}))});
input.on('close',()=>process.exit(0));
`);chmodSync(mockCodex,0o755);
const db=new DatabaseSync(join(process.env.LINKFLOW_DATA_DIR,'linkflow.sqlite'));
db.exec('CREATE TABLE state (id INTEGER PRIMARY KEY, body TEXT NOT NULL)');
db.prepare('INSERT INTO state VALUES(1,?)').run(JSON.stringify({sites:[],tasks:[],accounts:[],events:[],usage:{},settings:{autoRun:false,provider:'codex',codexPath:mockCodex,model:'',hasApiKey:false,timezone:'Asia/Singapore'}}));db.close();
require('../dist-electron/main.cjs');
const delay=ms=>new Promise(r=>setTimeout(r,ms));
const results=[];let win;
const check=(name,condition)=>{assert(condition,name);results.push({name,passed:true})};
const evaluate=js=>win.webContents.executeJavaScript(js,true);
const command=(name,p={})=>evaluate(`window.linkflow.invoke(${JSON.stringify(name)},${JSON.stringify(p)})`);
const waitForUi=async expression=>{const until=Date.now()+10000;while(Date.now()<until){if(await evaluate(expression))return;await delay(50)}throw Error('UI readiness deadline exceeded')};
const clickText=async text=>{const found=await evaluate(`(()=>{const b=[...document.querySelectorAll('button')].find(x=>x.innerText.trim()===${JSON.stringify(text)});if(!b)return false;b.click();return true})()`);assert(found,'button: '+text);await delay(150)};
(async()=>{
  await app.whenReady();
  for(let i=0;i<150;i++){win=BrowserWindow.getAllWindows().find(w=>w.getTitle().includes('LINKFLOW')||w.webContents.getURL().includes('/dist/index.html'));if(win&&!win.webContents.isLoading()&&await evaluate('!!window.linkflow && !!document.querySelector("h1")').catch(()=>false))break;await delay(100)}
  check('native app starts with secured IPC bridge',!!win&&await evaluate('!!window.linkflow'));
  check('renderer cannot access Node',await evaluate('typeof require === "undefined" && typeof process === "undefined"'));
  let snapshot=await command('snapshot');const builtinChannelCount=snapshot.channels.length;check('new profile has zero fake websites',snapshot.sites.length===0);check('initial snapshot does not unlock keychain',snapshot.runtime.vaultReady===false);check('isolated test execution remains paused',snapshot.settings.autoRun===false);
  check('legacy profile does not gain automatic publication permission',snapshot.settings.articleReviewMode==='manual');
  await clickText('更新中心');
  await waitForUi('document.body.innerText.includes("此平台无法自动更新")');
  check('update center reads real service without checking external network in development', (await command('app:update-status')).phase==='unsupported');
  check('update IPC rejects renderer-controlled download addresses',await evaluate('window.linkflow.invoke("app:download-update",{url:"https://untrusted.example/update.exe"}).then(()=>false,()=>true)'));
  check('install without prepared artifact fails without quitting or changing settings',await evaluate('window.linkflow.invoke("app:install-update").then(()=>false,()=>true)')&&(await command('snapshot')).settings.autoRun===false);
  await clickText('总览');
  await clickText('添加网站');check('add dialog opens',await evaluate('!!document.querySelector("[role=dialog]")'));await evaluate('document.querySelector("[aria-label=关闭]").click()');await delay(150);
  await clickText('设置');
  check('reasoning level is visible before opening advanced settings',await evaluate('!!document.querySelector("[aria-label=填写思考等级]")&&document.querySelector(".reasoning-control")?.offsetParent!==null'));
  await evaluate('(()=>{const e=document.querySelector("[aria-label=填写思考等级]");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"bad value");e.dispatchEvent(new Event("input",{bubbles:true}))})()');await delay(80);
  check('unknown model allows manual effort but rejects malformed identifiers before save',await evaluate('document.querySelector("[role=alert]")?.innerText.includes("只能包含")&&[...document.querySelectorAll("button")].find(b=>b.innerText.trim()==="保存设置")?.disabled'));
  await evaluate('(()=>{const e=document.querySelector("[aria-label=填写思考等级]");Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(e,"");e.dispatchEvent(new Event("input",{bubbles:true}))})()');await delay(80);
  await clickText('刷新可用模型');await waitForUi('!!document.querySelector("[aria-label=选择模型]")');
  check('empty model remains explicitly unfixed after refresh',await evaluate('(()=>{const e=document.querySelector("[aria-label=选择模型]");return e?.value===""&&e.selectedOptions[0]?.textContent.includes("未固定模型")})()'));
  check('reasoning level remains visible with advanced settings closed',await evaluate('document.querySelector(".advanced-settings")?.open===false&&document.querySelector(".reasoning-control")?.offsetParent!==null'));
  check('discovered model list renders without implicitly applying its capabilities',await evaluate('document.body.innerText.includes("Reasoning Wide")&&document.body.innerText.includes("未明确选择模型，思考能力由连接实际使用的默认模型决定")'));
  await evaluate('(()=>{const e=document.querySelector("[aria-label=选择模型]");e.value="reasoning-wide";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(100);
  check('explicit model uses its dynamic reported reasoning list and suggestion',await evaluate('(()=>{const e=document.querySelector("[aria-label=选择思考等级]");return e&&[...e.options].some(o=>o.value==="minimal")&&[...e.options].some(o=>o.value==="high")&&![...e.options].some(o=>o.value==="none")&&e.parentElement.innerText.includes("建议 低（low）")})()'));
  await evaluate('(()=>{const e=document.querySelector("[aria-label=选择思考等级]");e.value="high";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(80);
  await evaluate('(()=>{const e=document.querySelector("[aria-label=选择模型]");e.value="reasoning-compact";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(100);
  check('switching to an incompatible model preserves the effort and blocks both saves',await evaluate('(()=>{const e=document.querySelector("[aria-label=选择思考等级]");const buttons=[...document.querySelectorAll("button")];return e?.value==="high"&&document.querySelector("[role=alert]")?.innerText.includes("原值尚未改变")&&buttons.find(b=>b.innerText.trim()==="保存设置")?.disabled&&buttons.find(b=>b.innerText.trim()==="保存并测试")?.disabled})()'));
  await evaluate('(()=>{const e=document.querySelector("[aria-label=选择思考等级]");e.value="minimal";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(80);
  await clickText('保存设置');await delay(250);snapshot=await command('snapshot');
  check('model and reasoning level persist in the actual settings payload',snapshot.settings.model==='reasoning-compact'&&snapshot.settings.reasoningEffort==='minimal');
  await clickText('总览');await clickText('设置');await clickText('刷新可用模型');await waitForUi('!!document.querySelector("[aria-label=选择模型]")');
  check('saved model and reasoning level reopen without implicit changes',await evaluate('document.querySelector("[aria-label=选择模型]")?.value==="reasoning-compact"&&document.querySelector("[aria-label=选择思考等级]")?.value==="minimal"'));
  await clickText('运行偏好');
  check('manual publication is selected by default in the real settings UI',await evaluate('document.querySelectorAll("input[name=article-review-mode]")[0]?.checked===true'));
  await evaluate('document.querySelectorAll("input[name=article-review-mode]")[1].click()');await delay(80);
  check('selecting AI review does not grant publication permission before save',(await command('snapshot')).settings.articleReviewMode==='manual');
  await clickText('保存设置');await waitForUi('document.querySelectorAll("input[name=article-review-mode]")[1]?.checked===true');snapshot=await command('snapshot');
  check('explicit saved AI review permission preserves the paused plan',snapshot.settings.articleReviewMode==='ai'&&snapshot.settings.autoRun===false);
  await clickText('总览');await clickText('设置');await clickText('运行偏好');
  check('AI review permission persists when reopening settings',await evaluate('document.querySelectorAll("input[name=article-review-mode]")[1]?.checked===true'));
  await evaluate('document.querySelectorAll("input[name=article-review-mode]")[0].click()');await delay(80);await clickText('保存设置');
  check('manual publication can be restored without starting task execution',(await command('snapshot')).settings.articleReviewMode==='manual'&&(await command('snapshot')).settings.autoRun===false);
  await clickText('总览');
  await evaluate('document.querySelector(".demo-switch").click()');await delay(200);
  check('explicit demo shows sample websites',await evaluate('document.body.innerText.includes("studio.example")'));
  win.webContents.debugger.attach('1.3');
  async function capture(name,width=1487,height=1058){
    await win.webContents.debugger.sendCommand('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:1,mobile:false});await delay(180);
    const {data}=await win.webContents.debugger.sendCommand('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(join(evidence,name),Buffer.from(data,'base64'));
  }
  await capture('overview-1487x1058.png');
  await clickText('设置');check('settings page renders',await evaluate('document.body.innerText.includes("AI")'));
  await capture('settings.png');
  await clickText('数据与备份');await delay(200);check('maintenance UI explains local automatic backup boundaries',await evaluate('document.body.innerText.includes("本机自动加密备份")&&document.body.innerText.includes("每 24 小时")&&document.body.innerText.includes("默认关闭")&&document.body.innerText.includes("应用更新")'));
  await clickText('邮箱池');await clickText('添加邮箱');
  check('mailbox drawer starts with Gmail and populated TLS server',await evaluate('(()=>{const s=document.querySelector(".side-drawer select");return s?.value==="gmail"&&[...document.querySelectorAll(".side-drawer input")].some(x=>x.value==="imap.gmail.com")})()'));
  await evaluate('(()=>{const e=document.querySelector(".side-drawer select");e.value="qq";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(150);
  check('selecting QQ automatically fills IMAP host and port',await evaluate('(()=>{const values=[...document.querySelectorAll(".side-drawer input")].map(x=>x.value);return values.includes("imap.qq.com")&&values.includes("993")})()'));
  await evaluate('(()=>{const e=document.querySelector(".side-drawer select");e.value="outlook";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(150);
  check('unsupported Outlook clearly explains OAuth requirement',await evaluate('(()=>{const values=[...document.querySelectorAll(".side-drawer input")].map(x=>x.value);return values.includes("outlook.office365.com")&&document.body.innerText.includes("需要 OAuth2")&&document.body.innerText.includes("暂不支持")})()'));
  await evaluate('(()=>{const e=document.querySelector(".side-drawer select");e.value="gmail";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(150);await capture('mail-presets.png');await evaluate('document.querySelector(".side-drawer [aria-label=关闭]").click()');await delay(100);await clickText('导入 JSON');check('mailbox import accepts structured local input without exposing credentials',await evaluate('document.body.innerText.includes("批量导入邮箱")&&!!document.querySelector(".side-drawer textarea")'));await evaluate('document.querySelector(".side-drawer [aria-label=关闭]").click()');await delay(100);
  await clickText('账号');check('accounts page renders',await evaluate('document.body.innerText.includes("账号与绑定")'));await capture('accounts.png');check('accounts list is primary and import remains available',await evaluate('document.body.innerText.includes("先看账号")&&document.body.innerText.includes("导入账号")'));
  await clickText('连接 GitHub');check('Gist connection UI uses a masked token and honest identity reuse',await evaluate('document.body.innerText.includes("连接新的 Gist 身份")&&document.body.innerText.includes("不会自动注册账号")&&!!document.querySelector(".side-drawer input[type=password]")'));await evaluate('document.querySelector(".side-drawer [aria-label=关闭]").click()');await delay(100);
  await clickText('渠道');check('channel directory renders',await evaluate('document.body.innerText.includes("渠道")'));
  check('channel directory displays every built-in entry',await evaluate('document.querySelectorAll(".channel-table tbody tr:not(.channel-details-row)").length')===builtinChannelCount);
  await clickText('API');check('API filter only shows API-backed channels',await evaluate('document.querySelectorAll(".channel-table tbody tr:not(.channel-details-row)").length===2&&document.body.innerText.includes("GitHub Gist")&&document.body.innerText.includes("Telegraph")'));
  await clickText('资料页');check('profile filter does not claim article automation',await evaluate('document.querySelectorAll(".channel-table tbody tr:not(.channel-details-row)").length===4&&document.body.innerText.includes("仅资料页操作")'));
  await clickText('全部');await delay(100);await capture('channels.png');
  await evaluate(`document.querySelector('[aria-label="查看 GitHub 详情"]').click()`);await delay(150);
  check('list rows disclose capability boundaries and honest unknown metrics',await evaluate('document.body.innerText.includes("资格与执行边界")&&document.body.innerText.includes("权威未知")&&document.body.innerText.includes("不会以 0 代替")'));

  await clickText('金融 / 加密内容');await delay(100);
  check('finance filter shows conditional financial candidates and keeps restrictions visible',await evaluate('document.body.innerText.includes("WordPress.com")&&document.body.innerText.includes("Publish0x（仅人工原创）")&&!document.body.innerText.includes("Product Hunt")&&document.body.innerText.includes("不表示可以自动发布")&&document.body.innerText.includes("当前停用")'));
  await clickText('金融 / 加密内容');
  await evaluate('(()=>{const e=document.querySelector("[aria-label=按网站筛选相关渠道]");e.value="demo-studio";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(100);
  await clickText('查看未匹配原因');
  check('unmatched candidates explain missing real qualifications instead of disappearing',await evaluate('document.body.innerText.includes("GitHub")&&document.body.innerText.includes("需要确认本人维护的开发项目")&&document.body.innerText.includes("该渠道目前停用")'));
  await evaluate(`(()=>{const b=document.querySelector('[aria-label="查看 GitHub 详情"]');if(b.closest('tr').nextElementSibling.hidden)b.click()})()`);await delay(80);
  check('expanded catalog details render inherited qualification requirements',await evaluate('document.querySelector(".channel-details-row:not([hidden])")?.innerText.includes("本人维护的开发项目")'));
  await evaluate('(()=>{const e=document.querySelector("[aria-label=按网站筛选相关渠道]");e.value="all";e.dispatchEvent(new Event("change",{bubbles:true}))})()');await delay(80);
  await clickText('任务');check('task center separates public result and continuation actions',await evaluate('document.body.innerText.includes("从待办到公开成果")&&document.querySelectorAll(".work-table tbody tr").length>0'));await capture('tasks.png');
  await clickText('总览');await evaluate('document.querySelector(".site-name").click()');await delay(200);check('site details expose eligibility and separate search reports',await evaluate('document.body.innerText.includes("这个网站适合哪些渠道")&&document.body.innerText.includes("GSC 导入样本")&&document.body.innerText.includes("Bing API 样本")'));await evaluate('document.querySelector(".site-tools").scrollIntoView()');await capture('site-tools.png');await clickText('总览');await capture('overview-1080x760.png',1080,760);check('compact desktop has no horizontal viewport overflow',await evaluate('document.documentElement.scrollWidth<=document.documentElement.clientWidth+1'));
  await win.webContents.debugger.sendCommand('Emulation.clearDeviceMetricsOverride');win.webContents.debugger.detach();
  await clickText('演示模式 · 返回真实数据');snapshot=await command('snapshot');check('demo never mutates real state',snapshot.sites.length===0);

  const autoBackups=await command('backup:auto-status');check('automatic backup defaults to disabled without touching keychain',autoBackups.enabled===false&&autoBackups.backups.length===0);
  await command('mailbox:save',{label:'Synthetic inbox',host:'imap.example.com',port:993,user:'smoke@example.com',secure:true,aliases:['hello@example.com']});
  const mailbox=(await command('snapshot')).mailboxes.find(item=>item.label==='Synthetic inbox');check('new mailbox pool roundtrips through IPC',!!mailbox&&!mailbox.hasPassword&&mailbox.aliases.includes('hello@example.com'));
  await command('mailbox:delete',{id:mailbox.id});check('unused mailbox can be removed',(await command('snapshot')).mailboxes.length===0);
  await command('channel:save',{channel:{name:'Synthetic channel',domain:'directory.example.com',submitUrl:'https://directory.example.com/submit',categories:['software'],languages:['en'],kind:'directory',free:'unknown',freeNote:'Needs review',rulesUrl:'https://directory.example.com/rules',notes:'Synthetic local entry'}});
  const custom=(await command('snapshot')).channels.find(item=>item.name==='Synthetic channel');check('custom channel stays manual in actual IPC',!!custom&&custom.automation==='manual'&&custom.evidenceStatus==='user_added');
  await command('channel:delete',{id:custom.id});check('unused custom channel can be removed',(await command('snapshot')).channels.length===builtinChannelCount);
  let denied=false;try{await command('account:save',{channelId:'github-gist',email:'smoke@example.com',username:'smoke',password:'synthetic'})}catch{denied=true}check('Gist credentials cannot bypass verified connection through password import',denied);
  denied=false;try{await command('site:add',{domain:'127.0.0.1',email:'hello@example.com',monthlyTarget:2})}catch{denied=true}check('private-domain input rejected by main process',denied);
  denied=false;try{await command('settings:save',{dailyAiLimit:0})}catch{denied=true}check('invalid execution budget rejected',denied);
  await command('settings:save',{dailyAiLimit:12,notify:false});check('settings persist through actual IPC',(await command('snapshot')).settings.dailyAiLimit===12);
  check('new mailbox defaults to Gmail', (await command('snapshot')).settings.mail.host==='imap.gmail.com');
  const testMail={host:'imap.gmail.com',port:993,user:'smoke@example.com',secure:true};
  await command('settings:save',{mail:testMail,mailPassword:'Synthetic-Mail-Only-7!'});
  check('synthetic mailbox password is saved without appearing in snapshot', (await command('snapshot')).settings.mail.hasPassword&&!JSON.stringify(await command('snapshot')).includes('Synthetic-Mail-Only-7!'));
  await command('settings:save',{mail:{...testMail,host:'imap.qq.com',hasPassword:true}});
  check('changing mailbox clears old secret and ignores forged hasPassword',!(await command('snapshot')).settings.mail.hasPassword);
  const mailDb=new DatabaseSync(join(process.env.LINKFLOW_DATA_DIR,'linkflow.sqlite'));
  check('old mailbox credential is removed from vault before changing destination',!mailDb.prepare('SELECT value FROM secrets WHERE key=?').get('mailPassword'));mailDb.close();
  await command('settings:save',{mail:{host:'imap.gmail.com',port:993,user:'',secure:true}});
  await command('site:add',{domain:'example.com',email:'hello@example.com',monthlyTarget:2});snapshot=await command('snapshot');check('website can be created through real IPC',snapshot.sites.length===1);const id=snapshot.sites[0].id;
  denied=false;try{await command('site:add',{domain:'www.example.com',email:'hello@example.com',monthlyTarget:2})}catch{denied=true}check('normalized duplicate websites rejected',denied);
  for(let i=0;i<200&&(await command('snapshot')).sites[0]?.status==='analyzing';i++)await delay(100);
  await command('site:update',{id,monthlyTarget:3,name:'Example'});check('website settings update',(await command('snapshot')).sites[0].monthlyTarget===3);
  await command('site:pause',{id,paused:true});check('website pause persists',(await command('snapshot')).sites[0].status==='paused');
  await command('site:delete',{id});check('site delete removes associated local tasks',(await command('snapshot')).sites.length===0);
  const syntheticPassword='Linkflow-Smoke-Only-7!';
  await command('account:save',{channelId:'github',email:'smoke@example.com',username:'linkflow-smoke',password:syntheticPassword});
  const account=(await command('snapshot')).accounts.find(a=>a.email==='smoke@example.com');
  check('account can be saved without exposing password in snapshot',!!account&&!JSON.stringify(await command('snapshot')).includes(syntheticPassword));
  const vaultDb=new DatabaseSync(join(process.env.LINKFLOW_DATA_DIR,'linkflow.sqlite'));
  const cipher=vaultDb.prepare('SELECT value FROM secrets WHERE key=?').get('account:'+account.id).value;vaultDb.close();
  check('system vault encrypts and recovers the synthetic password',!cipher.includes(syntheticPassword)&&safeStorage.decryptString(Buffer.from(cipher,'base64'))===syntheticPassword);
  await command('account:delete',{id:account.id});check('account delete removes saved account',(await command('snapshot')).accounts.length===0);
  denied=false;try{await command('external:open',{url:'file:///etc/passwd'})}catch{denied=true}check('external file protocol denied',denied);
  denied=false;try{await command('unknown:command',{})}catch{denied=true}check('arbitrary IPC command denied',denied);
  writeFileSync(join(evidence,'desktop-smoke.json'),JSON.stringify({passed:true,checks:results,dataPath:process.env.LINKFLOW_DATA_DIR},null,2));console.log('DESKTOP SMOKE PASSED: '+results.length+' checks');
  await command('app:quit').catch(()=>{});
})().catch(error=>{writeFileSync(join(evidence,'desktop-smoke.json'),JSON.stringify({passed:false,error:String(error),checks:results},null,2));console.error(error);app.exit(1)});
